Repository lmc-eu/spirit-design-system, pull requests merged in 2021-12, with the labels that each got.

#97 Feat: Synchronize color scales with designers and remove border main selected color
  packages/design-tokens/src/scss/_colors.scss
Labels: feature, BC

#99 Fix: Change for the default color property value in the implementatio…
  packages/web-react/src/components/Tag/Tag.tsx
Labels: bug

#102 Docs(license): Include license file
  LICENSE.md
  README.md
  packages/design-tokens/LICENSE.md
  packages/design-tokens/README.md
  packages/web-react/LICENSE.md
  packages/web-react/README.md
  packages/web/LICENSE.md
  packages/web/README.md
Labels: maintenance

#103 Docs: Introduce column with package versions in root readme
  README.md
Labels: documentation
