Repository lmc-eu/spirit-design-system, pull requests merged in 2022-04, with the labels that each got.

#230 Feat(web-react): Introduce Link component (refs #DS-167)
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Link/Link.stories.tsx
  packages/web-react/src/components/Link/Link.tsx
  packages/web-react/src/components/Link/README.md
  packages/web-react/src/components/Link/__tests__/Link.test.tsx
  packages/web-react/src/components/Link/__tests__/linkPropsDataProvider.ts
  packages/web-react/src/components/Link/__tests__/useLinkStyleProps.test.tsx
  packages/web-react/src/components/Link/index.ts
  packages/web-react/src/components/Link/stories/DisabledLink.tsx
  packages/web-react/src/components/Link/stories/DisabledUnderlinedLink.tsx
  packages/web-react/src/components/Link/stories/Link.tsx
  packages/web-react/src/components/Link/stories/LinkColors.tsx
  packages/web-react/src/components/Link/stories/LinkProps.tsx
  packages/web-react/src/components/Link/stories/UnderlinedLink.tsx
  packages/web-react/src/components/Link/useLinkStyleProps.tsx
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/link.ts
Labels: feature

#239 Chore(repo): Add json schema url to lerna configuration file
  lerna.json
Labels: maintenance

#225 Feat(web): Add text and background color utilities #DS-189
  examples/web/index.html
  examples/web/jobs.html
  packages/web/src/settings/_utilities.scss
  packages/web/src/tools/_utilities.scss
Labels: feature

#229 Feat(web-react): Introduce Heading component (refs #DS-167)
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Heading/Heading.stories.tsx
  packages/web-react/src/components/Heading/Heading.tsx
  packages/web-react/src/components/Heading/README.md
  packages/web-react/src/components/Heading/__tests__/Heading.test.tsx
  packages/web-react/src/components/Heading/__tests__/headingSizeDataProvider.ts
  packages/web-react/src/components/Heading/__tests__/useHeadingStyleProps.tsx
  packages/web-react/src/components/Heading/index.ts
  packages/web-react/src/components/Heading/stories/Heading.tsx
  packages/web-react/src/components/Heading/stories/HeadingLinks.tsx
  packages/web-react/src/components/Heading/stories/HeadingProps.tsx
  packages/web-react/src/components/Heading/stories/HeadingSizes.tsx
  packages/web-react/src/components/Heading/useHeadingStyleProps.tsx
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/heading.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/shared/index.ts
  packages/web-react/src/types/shared/typography.ts
Labels: feature

#251 Fix(web): Make the TextField fluid again
  packages/web/src/components/TextField/_TextField.scss
  packages/web/src/components/TextField/_theme.scss
Labels: bug

#263 Chore(ci): Fix uncommited changes when publishing (refs #259)
  .github/workflows/publish.yaml
  package.json
  yarn.lock
Labels: maintenance

#228 Feat(web-react): Introduce Text component (refs #DS-167)
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Text/README.md
  packages/web-react/src/components/Text/Text.stories.tsx
  packages/web-react/src/components/Text/Text.tsx
  packages/web-react/src/components/Text/__tests__/Text.test.tsx
  packages/web-react/src/components/Text/__tests__/textPropsDataProvider.ts
  packages/web-react/src/components/Text/__tests__/useTextStyleProps.test.tsx
  packages/web-react/src/components/Text/index.tsx
  packages/web-react/src/components/Text/stories/Text.tsx
  packages/web-react/src/components/Text/stories/TextAllCombinations.tsx
  packages/web-react/src/components/Text/stories/TextEmphasis.tsx
  packages/web-react/src/components/Text/stories/TextProps.tsx
  packages/web-react/src/components/Text/stories/TextSizes.tsx
  packages/web-react/src/components/Text/useTextStyleProps.tsx
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/text.ts
Labels: feature

#262 Refactor(web): Move SASS styles into `scss` directory
  .storybook/assets/stylesheets/index.scss
  packages/web/package.json
  packages/web/src/scss/components/Alert/Alert.scss
  packages/web/src/scss/components/Alert/README.md
  packages/web/src/scss/components/Alert/_theme.scss
  packages/web/src/scss/components/Alert/index.scss
  packages/web/src/scss/components/Button/README.md
  packages/web/src/scss/components/Button/_Button.scss
  packages/web/src/scss/components/Button/_theme.scss
  packages/web/src/scss/components/Button/_tools.scss
  packages/web/src/scss/components/Button/index.scss
  packages/web/src/scss/components/CheckboxField/README.md
  packages/web/src/scss/components/CheckboxField/_CheckboxField.scss
  packages/web/src/scss/components/CheckboxField/_theme.scss
  packages/web/src/scss/components/CheckboxField/index.scss
  packages/web/src/scss/components/Container/README.md
  packages/web/src/scss/components/Container/_Container.scss
  packages/web/src/scss/components/Container/_theme.scss
  packages/web/src/scss/components/Container/_tools.scss
  packages/web/src/scss/components/Container/index.scss
  packages/web/src/scss/components/Grid/README.md
  packages/web/src/scss/components/Grid/_Grid.scss
  packages/web/src/scss/components/Grid/_theme.scss
  packages/web/src/scss/components/Grid/_tools.scss
  packages/web/src/scss/components/Grid/index.scss
  packages/web/src/scss/components/Stack/README.md
  packages/web/src/scss/components/Stack/_Stack.scss
  packages/web/src/scss/components/Stack/_theme.scss
  packages/web/src/scss/components/Stack/index.scss
  packages/web/src/scss/components/Tag/README.md
  packages/web/src/scss/components/Tag/_Tag.scss
  packages/web/src/scss/components/Tag/_theme.scss
  packages/web/src/scss/components/Tag/_tools.scss
  packages/web/src/scss/components/Tag/index.scss
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/_theme.scss
  packages/web/src/scss/components/TextField/index.scss
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/foundation/_box-sizing.scss
  packages/web/src/scss/foundation/_links.scss
  packages/web/src/scss/foundation/_reset.scss
  packages/web/src/scss/foundation/_shared.scss
  packages/web/src/scss/foundation/index.scss
  packages/web/src/scss/helpers/_links.scss
  packages/web/src/scss/helpers/_typography.scss
  packages/web/src/scss/helpers/index.scss
  packages/web/src/scss/settings/_cursors.scss
  packages/web/src/scss/settings/_links.scss
  packages/web/src/scss/settings/_svg.scss
  packages/web/src/scss/settings/_utilities.scss
  packages/web/src/scss/tools/_accessibility.scss
  packages/web/src/scss/tools/_breakpoint.scss
  packages/web/src/scss/tools/_links.scss
  packages/web/src/scss/tools/_string.scss
  packages/web/src/scss/tools/_svg.scss
  packages/web/src/scss/tools/_typography.scss
  packages/web/src/scss/tools/_utilities.scss
  packages/web/src/scss/utilities/_utilities.scss
  packages/web/src/scss/utilities/index.scss
Labels: maintenance

#249 Docs(design-tokens): Add missing node_modules in sass loader configur…
  packages/design-tokens/README.md
  packages/web/README.md
Labels: documentation

#275 Fix(web-react): Export Link component from library
  packages/web-react/src/components/index.ts
Labels: bug

#253 Feat(web): Add focus shadow to CheckboxField and TextField
  packages/web/src/scss/components/CheckboxField/_CheckboxField.scss
  packages/web/src/scss/components/CheckboxField/_theme.scss
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/_theme.scss
Labels: feature

#252 Feat(web): Style password toggle #DS-192
  examples/web/index.html
  examples/web/jobs.html
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/_theme.scss
Labels: feature

#273 Feat: Move CheckboxField label #DS-179
  examples/web/index.html
  examples/web/jobs.html
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/CheckboxField/README.md
  packages/web-react/src/components/CheckboxField/__tests__/CheckboxField.test.tsx
  packages/web/src/scss/components/CheckboxField/README.md
  packages/web/src/scss/components/CheckboxField/_CheckboxField.scss
Labels: feature

#279 Docs(web): Document prefixing of CSS class names
  examples/web/postcss.config.js
  packages/web-react/README.md
  packages/web/README.md
Labels: documentation

#286 Feat(web): Add Image css helpers
  packages/web/src/scss/helpers/_image.scss
  packages/web/src/scss/helpers/index.scss
Labels: feature

#293 Chore(ci): Publish code coverage from multiple packages at once
  .github/workflows/test.yaml
Labels: maintenance

#294 BREAKING CHANGES: Set correct grid narrow span on tablet, should spre…
  examples/web/index.html
  examples/web/jobs.html
  packages/web/src/scss/components/Grid/_Grid.scss
Labels: bug

#295 Feat(web): Introduce text helper for truncating single- and multiline texts #DS-209
  packages/web/src/scss/helpers/_text.scss
  packages/web/src/scss/helpers/index.scss
Labels: feature

#296 Feat(web): Supported TextField's type attribute values #DS-155
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
Labels: feature

#299 Docs(web): Better way to describe how to use JS plugins individually
  packages/web/README.md
Labels: documentation
