Repository lmc-eu/spirit-design-system, pull requests merged in 2022-09, with the labels that each got.

#436 Chore(repo): Schedule dependency updates on every two weeks
  .renovaterc.json
Labels: maintenance

#452 Feat(web): Update Breadcrumbs' last item's theme color (refs #DS-313)
  packages/web-react/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/web-react/src/components/Breadcrumbs/README.md
  packages/web-twig/src/Resources/components/Breadcrumbs/README.md
  packages/web-twig/src/Resources/components/Breadcrumbs/index.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsCustom.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/breadcrumbsCustom.twig
  packages/web/src/scss/components/Breadcrumbs/README.md
  packages/web/src/scss/components/Breadcrumbs/_Breadcrumbs.scss
  packages/web/src/scss/components/Breadcrumbs/_theme.scss
  packages/web/src/scss/components/Breadcrumbs/index.html
Labels: feature

#459 Fix invisible `RadioField` state in forced-colors mode
  packages/web/src/scss/components/RadioField/_RadioField.scss
Labels: bug

#458 Refactor(repo): Makefile now uses better self-documented structure
  Makefile
Labels: maintenance

#478 Fix(web-twig): Remove Icon name first letter upper-casing
  packages/web-twig/src/Resources/components/Icon/Icon.twig
  packages/web-twig/src/Resources/components/Icon/README.md
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set alertDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set iconDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tooltipDefaultPure.twig__1.html
Labels: bug

#468 Feat(web): Use Icon in TextField #DS-305
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/_theme.scss
  packages/web/src/scss/components/TextField/index.html
Labels: feature

#484 BREAKING CHANGES(web): Remove `Button__icon` class as we don't use it…
  packages/web/src/scss/components/Button/_Button.scss
Labels: BC

#488 Fix(web-twig): Set correct order of filters in TabPane
  packages/web-twig/src/Resources/components/Tabs/TabPane.twig
Labels: bug

#492 Feat(web): Add basic spin animation helper
  packages/web/src/scss/helpers/_animation.scss
  packages/web/src/scss/helpers/index.html
  packages/web/src/scss/helpers/index.scss
Labels: feature

#490 Feat(exporter-scss): Implement Unitless property and fix style property
  exporters/scss/exporter.json
  exporters/scss/generated/functions.js
  exporters/scss/src/js/generators/simple.ts
Labels: feature

#499 Fix(web-twig): Variable props does not exist
  packages/web-twig/src/Resources/components/Alert/Alert.twig
  packages/web-twig/src/Resources/components/Breadcrumbs/index.twig
  packages/web-twig/src/Resources/components/Button/Button.twig
  packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.twig
  packages/web-twig/src/Resources/components/CheckboxField/CheckboxField.twig
  packages/web-twig/src/Resources/components/Container/Container.twig
  packages/web-twig/src/Resources/components/Grid/Grid.twig
  packages/web-twig/src/Resources/components/Heading/Heading.twig
  packages/web-twig/src/Resources/components/Icon/Icon.twig
  packages/web-twig/src/Resources/components/Link/Link.twig
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/src/Resources/components/Pill/Pill.twig
  packages/web-twig/src/Resources/components/Stack/Stack.twig
  packages/web-twig/src/Resources/components/Tabs/TabItem.twig
  packages/web-twig/src/Resources/components/Tabs/TabLink.twig
  packages/web-twig/src/Resources/components/Tabs/TabList.twig
  packages/web-twig/src/Resources/components/Tabs/TabPane.twig
  packages/web-twig/src/Resources/components/Tabs/TabsItem.twig
  packages/web-twig/src/Resources/components/Tabs/TabsLink.twig
  packages/web-twig/src/Resources/components/Tabs/TabsPane.twig
  packages/web-twig/src/Resources/components/Tag/Tag.twig
  packages/web-twig/src/Resources/components/Text/Text.twig
  packages/web-twig/src/Resources/components/TextField/TextField.twig
  packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig
  packages/web-twig/src/Resources/components/Tooltip/TooltipWrapper.twig
  packages/web-twig/src/Twig/PropsExtension.php
  packages/web-twig/tests/Twig/PropsExtensionTest.php
Labels: bug

#467 Fix(web): Fix underlined Link
  packages/web/src/scss/helpers/_links.scss
Labels: bug

#474 BREAKING CHANGES: Remove `narrow` preset of `Grid` in favour of product-specific layouts
  packages/web-react/docs/stories/Installation.stories.mdx
  packages/web-react/docs/stories/examples/LoginForm.stories.tsx
  packages/web-react/src/components/Grid/Grid.stories.tsx
  packages/web-react/src/components/Grid/README.md
  packages/web-react/src/components/Grid/__tests__/Grid.test.tsx
  packages/web-react/src/components/Grid/__tests__/useGridStyleProps.test.tsx
  packages/web-react/src/components/Grid/useGridStyleProps.tsx
  packages/web-react/src/types/grid.ts
  packages/web-twig/src/Resources/components/Grid/Grid.twig
  packages/web-twig/src/Resources/components/Grid/README.md
  packages/web/src/scss/components/Grid/README.md
  packages/web/src/scss/components/Grid/_Grid.scss
  packages/web/src/scss/components/Grid/index.html
Labels: BC

#503 Web: Introduce Grid Span
  packages/web/partials/layout/base.hbs
  packages/web/src/scss/components/Grid/README.md
  packages/web/src/scss/components/Grid/_Grid.scss
  packages/web/src/scss/components/Grid/_theme.scss
  packages/web/src/scss/components/Grid/_tools.scss
  packages/web/src/scss/components/Grid/index.html
Labels: feature

#509 Chore(ci): Remove `ci-skip` from publish message
  lerna.json
Labels: maintenance

#508 Chore(web-twig): Add changes done by version script to VCS
  packages/web-twig/package.json
Labels: maintenance

#513 Refactor(web): Compose toggle triggers from event handlers
  packages/web/src/js/Collapse.ts
  packages/web/src/js/utils/ComponentFunctions.ts
Labels: refactoring

#514 Chore(repo): Use schedule extension from the renovate-config than a d…
  .renovaterc.json
Labels: maintenance
