Repository lmc-eu/spirit-design-system, pull requests merged in 2022-08, with the labels that each got.

#410 Docs(web-twig): Display package version on main README file
  README.md
Labels: documentation

#411 Fix(web-twig): Remove unexpected files
  packages/web-twig/src/Compiler/ComponentLexer.php
  packages/web-twig/src/Compiler/ComponentTagCompiler.php
  packages/web-twig/src/DependencyInjection/TwigComponentsExtension.php
  packages/web-twig/src/TwigComponentsBundle.php
  packages/web-twig/tests/DependencyInjection/AerospikeExtensionTest.php
  packages/web-twig/tests/DependencyInjection/CompilerPass/LoggerValidationPassTest.php
  packages/web-twig/tests/DependencyInjection/TwigComponentsExtensionTest.php
Labels: bug

#412 Fix(web-twig): Default components path in spirit alias
  packages/web-twig/src/DependencyInjection/CompilerPass/OverrideServiceCompilerPass.php
Labels: bug

#417 Feat(icons): Add script to process SVGs in Icons package
  packages/icons/package.json
  packages/icons/scripts/build.js
Labels: feature

#418 Feat: Add shx package to cross-platform commands
  packages/design-tokens/package.json
  packages/icons/package.json
  packages/web-react/package.json
  packages/web/package.json
  yarn.lock
Labels: feature

#397 Feat(web-twig): Introduce Modal component
  packages/web-twig/CHANGELOG.md
  packages/web-twig/README.md
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/twig-components/modal.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/modalDefault.twig
Labels: feature

#428 Fix(web-twig): TooltipWrapper does not use additional classes
  packages/web-twig/src/Resources/components/Tooltip/TooltipWrapper.twig
Labels: bug

#423 Feat(web): Introduce `Breadcrumbs` component (refs #DS-302)
  packages/web/index.html
  packages/web/src/scss/components/Breadcrumbs/README.md
  packages/web/src/scss/components/Breadcrumbs/_Breadcrumbs.scss
  packages/web/src/scss/components/Breadcrumbs/_theme.scss
  packages/web/src/scss/components/Breadcrumbs/index.html
  packages/web/src/scss/components/Breadcrumbs/index.scss
  packages/web/src/scss/components/index.scss
Labels: feature

#425 Docs(web): Improve READMEs to work better in Supernova context
  packages/web/src/scss/components/Alert/README.md
  packages/web/src/scss/components/Button/README.md
  packages/web/src/scss/components/CheckboxField/README.md
  packages/web/src/scss/components/Container/README.md
  packages/web/src/scss/components/Grid/README.md
  packages/web/src/scss/components/Header/README.md
  packages/web/src/scss/components/Modal/README.md
  packages/web/src/scss/components/Pill/README.md
  packages/web/src/scss/components/Stack/README.md
  packages/web/src/scss/components/Tabs/README.md
  packages/web/src/scss/components/Tabs/index.html
  packages/web/src/scss/components/Tag/README.md
  packages/web/src/scss/components/TextField/README.md
Labels: documentation

#424 Docs(web): Improve previews for both development and Supernova context
  .prettierignore
  .storybook/assets/stylesheets/index.scss
  packages/web-react/src/components/Button/stories/ButtonBlock.tsx
  packages/web-react/src/components/Button/stories/ButtonColors.tsx
  packages/web-react/src/components/Button/stories/ButtonDisabled.tsx
  packages/web-react/src/components/Button/stories/ButtonSquare.tsx
  packages/web-react/src/components/Grid/Grid.stories.tsx
  packages/web-react/src/components/Link/stories/DisabledLink.tsx
  packages/web-react/src/components/Link/stories/DisabledUnderlinedLink.tsx
  packages/web-react/src/components/Link/stories/LinkColors.tsx
  packages/web-react/src/components/Link/stories/UnderlinedLink.tsx
  packages/web-react/src/components/Stack/Stack.stories.tsx
  packages/web/CONTRIBUTING.md
  packages/web/index.html
  packages/web/partials/header.hbs
  packages/web/partials/layout/base.hbs
  packages/web/partials/layout/default.hbs
  packages/web/partials/layout/plain.hbs
  packages/web/src/scss/components/Alert/index.html
  packages/web/src/scss/components/Breadcrumbs/index.html
  packages/web/src/scss/components/Button/index.html
  packages/web/src/scss/components/CheckboxField/index.html
  packages/web/src/scss/components/Container/index.html
  packages/web/src/scss/components/Grid/index.html
  packages/web/src/scss/components/Header/index.html
  packages/web/src/scss/components/Modal/index.html
  packages/web/src/scss/components/Pill/index.html
  packages/web/src/scss/components/Stack/index.html
  packages/web/src/scss/components/Tabs/index.html
  packages/web/src/scss/components/Tag/index.html
  packages/web/src/scss/components/TextField/index.html
  packages/web/src/scss/components/Tooltip/index.html
  packages/web/src/scss/helpers/index.html
  packages/web/vite.config.ts
Labels: documentation

#433 Fix(web-twig): TooltipWrapper double closure of the component
  packages/web-twig/src/Resources/components/Tooltip/TooltipWrapper.twig
Labels: bug

#434 Fix(web-twig): Tooltip raw id attribute
  packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tooltipDefaultPure.twig__1.html
Labels: bug

#419 Feat(web): Introduce Icon component #DS-286
  packages/icons/README.md
  packages/web/.gitignore
  packages/web/package.json
  packages/web/src/scss/components/Icon/README.md
  packages/web/src/scss/components/Icon/_Icon.scss
  packages/web/src/scss/components/Icon/_theme.scss
  packages/web/src/scss/components/Icon/index.html
  packages/web/src/scss/components/Icon/index.scss
  packages/web/src/scss/components/index.scss
  packages/web/vite.config.ts
Labels: feature

#405 Feat(web-twig): Introduce RadioField component
  packages/web-twig/CHANGELOG.md
  packages/web-twig/src/Resources/components/RadioField/README.md
  packages/web-twig/src/Resources/components/RadioField/RadioField.twig
  packages/web-twig/src/Resources/twig-components/radioField.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set radioFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set radioFieldDefaultPure.twig__1.html
  packages/web-twig/tests/components-fixtures/radioFieldDefault.twig
  packages/web-twig/tests/components-fixtures/radioFieldDefaultPure.twig
Labels: feature

#435 Chore(repo): Introduce nvm config file to fix Node.js version (refs #…
  .nvmrc
Labels: maintenance

#443 Style(repo): Ignore `vendor` directory
  .eslintignore
Labels: maintenance

#438 Docs(web-react): Enable SVG React components in Storybook using SVGR
  .storybook/main.js
  package.json
  yarn.lock
Labels: maintenance

#444 Feat(web-twig): Add size prop to Icon component #DS-288
  packages/web-twig/src/Resources/components/Icon/Icon.twig
  packages/web-twig/src/Resources/components/Icon/README.md
  packages/web-twig/src/Twig/SvgExtension.php
  packages/web-twig/tests/Twig/SvgExtensionTest.php
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set iconDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/iconDefault.twig
  packages/web-twig/tests/fixtures/test_with_size.svg
Labels: feature

#431 Feat(web-twig): Introduce `Breadcrumbs` component (refs #DS-302)
  .editorconfig
  packages/web-twig/src/Resources/components/Breadcrumbs/README.md
  packages/web-twig/src/Resources/components/Breadcrumbs/index.twig
  packages/web-twig/src/Resources/twig-components/breadcrumbs.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsCustom.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/breadcrumbsCustom.twig
  packages/web-twig/tests/components-fixtures/breadcrumbsDefault.twig
Labels: feature

#439 Feat(icons): Generate Icons as a React Component in Typescript
  packages/icons/README.md
  packages/icons/package.json
  packages/icons/scripts/build.js
  packages/icons/scripts/buildSvg.js
  packages/icons/scripts/prepareSvgReact.js
  yarn.lock
Labels: feature

#430 Feat(web-react): Introduce `Breadcrumbs` component (refs #DS-302)
  .storybook/assets/stylesheets/index.scss
  packages/web-react/.eslintrc.js
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/web-react/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/web-react/src/components/Breadcrumbs/README.md
  packages/web-react/src/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx
  packages/web-react/src/components/Breadcrumbs/__tests__/useBreadcrumbsStyleProps.test.tsx
  packages/web-react/src/components/Breadcrumbs/index.ts
  packages/web-react/src/components/Breadcrumbs/stories/Breadcrumbs.tsx
  packages/web-react/src/components/Breadcrumbs/stories/BreadcrumbsHtml.tsx
  packages/web-react/src/components/Breadcrumbs/stories/BreadcrumbsProps.tsx
  packages/web-react/src/components/Breadcrumbs/useBreadcrumbsStyleProps.tsx
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/breadcrumbs.ts
  packages/web-react/src/types/index.ts
Labels: feature
