Repository lmc-eu/spirit-design-system, pull requests merged in 2022-11, with the labels that each got.

#548 Feat(web): Add utility classes for border radius using radii tokens
  packages/web/src/scss/settings/_utilities.scss
Labels: feature

#547 Feature/ds 394 dropdown web react
  .storybook/assets/stylesheets/index.scss
  packages/web-react/src/components/Collapse/useCollapseAriaProps.ts
  packages/web-react/src/components/Dropdown/Dropdown.stories.tsx
  packages/web-react/src/components/Dropdown/Dropdown.tsx
  packages/web-react/src/components/Dropdown/README.md
  packages/web-react/src/components/Dropdown/__tests__/Dropdown.test.tsx
  packages/web-react/src/components/Dropdown/__tests__/useDropdown.test.ts
  packages/web-react/src/components/Dropdown/__tests__/useDropdownAriaProps.test.ts
  packages/web-react/src/components/Dropdown/__tests__/useDropdownStyleProps.ts
  packages/web-react/src/components/Dropdown/index.ts
  packages/web-react/src/components/Dropdown/stories/DisableAutoClose.tsx
  packages/web-react/src/components/Dropdown/stories/Dropdown.tsx
  packages/web-react/src/components/Dropdown/useDropdown.ts
  packages/web-react/src/components/Dropdown/useDropdownAriaProps.ts
  packages/web-react/src/components/Dropdown/useDropdownStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/hooks/index.tsx
  packages/web-react/src/hooks/useClickOutside.ts
  packages/web-react/src/types/dropdown.ts
  packages/web-react/src/types/index.ts
Labels: feature

#549 Chore(web-twig): Introduce `.gitattributes` to lower download size
  packages/web-twig/.gitattributes
Labels: maintenance

#551 Docs(web-twig): Documenting Collapse examples in twig syntax
  packages/web-twig/src/Resources/components/Collapse/README.md
Labels: documentation

#542 Feat(web-twig): Introduce Dropdown component (refs #DS-395)
  packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig
  packages/web-twig/src/Resources/components/Dropdown/DropdownWrapper.twig
  packages/web-twig/src/Resources/components/Dropdown/README.md
  packages/web-twig/src/Resources/twig-components/dropdown.twig
  packages/web-twig/src/Resources/twig-components/dropdownWrapper.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set dropdownDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set dropdownFull.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set dropdownWrapperDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/dropdownDefault.twig
  packages/web-twig/tests/components-fixtures/dropdownFull.twig
  packages/web-twig/tests/components-fixtures/dropdownWrapperDefault.twig
Labels: feature

#555 Feat(exporter-scss): Sort radii tokens by number in name
  exporters/scss/exporter.json
  exporters/scss/src/radii.pr
Labels: feature

#556 Fix(web-twig): Add missing default value for optional breakpoint prop
  packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set dropdownDefault.twig__1.html
Labels: bug

#554 Fix(web): Incorrect naming and sorting of assets in preview #DS-421
  packages/web/assets/demo.css
  packages/web/partials/layout/base.hbs
  packages/web/vite.config.ts
Labels: bug

#559 Fix(web): Order top-level CSS layers by selector specificity
  packages/web/src/scss/index.scss
Labels: bug

#561 Chore(web-react): Speed up Storybook run and build
  .storybook/main.js
Labels: maintenance
