Repository lmc-eu/spirit-design-system, pull requests merged in 2022-07, with the labels that each got.

#346 Feature/ds 232 react tabs
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Tabs/README.md
  packages/web-react/src/components/Tabs/Tab.stories.tsx
  packages/web-react/src/components/Tabs/TabContent.tsx
  packages/web-react/src/components/Tabs/TabContext.tsx
  packages/web-react/src/components/Tabs/TabItem.tsx
  packages/web-react/src/components/Tabs/TabLink.tsx
  packages/web-react/src/components/Tabs/TabList.tsx
  packages/web-react/src/components/Tabs/TabPane.tsx
  packages/web-react/src/components/Tabs/Tabs.tsx
  packages/web-react/src/components/Tabs/__tests__/TabContent.test.tsx
  packages/web-react/src/components/Tabs/__tests__/TabItem.test.tsx
  packages/web-react/src/components/Tabs/__tests__/TabLink.test.tsx
  packages/web-react/src/components/Tabs/__tests__/TabList.test.tsx
  packages/web-react/src/components/Tabs/__tests__/TabPane.test.tsx
  packages/web-react/src/components/Tabs/__tests__/useTab.test.tsx
  packages/web-react/src/components/Tabs/__tests__/useTabsStyleProps.test.tsx
  packages/web-react/src/components/Tabs/index.ts
  packages/web-react/src/components/Tabs/stories/TabContentProps.tsx
  packages/web-react/src/components/Tabs/stories/TabHtml.tsx
  packages/web-react/src/components/Tabs/stories/TabItemProps.tsx
  packages/web-react/src/components/Tabs/stories/TabLinkProps.tsx
  packages/web-react/src/components/Tabs/stories/TabLinks.tsx
  packages/web-react/src/components/Tabs/stories/TabListProps.tsx
  packages/web-react/src/components/Tabs/stories/TabPaneProps.tsx
  packages/web-react/src/components/Tabs/stories/Tabs.tsx
  packages/web-react/src/components/Tabs/stories/TabsProps.tsx
  packages/web-react/src/components/Tabs/useTabs.tsx
  packages/web-react/src/components/Tabs/useTabsStyleProps.tsx
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/tabs.ts
  packages/web-react/tests/testUtils/withTabsContext.tsx
Labels: feature

#382 Fix(web-react): Add missing default export of Tabs component
  packages/web-react/src/components/Alert/index.ts
  packages/web-react/src/components/Button/index.ts
  packages/web-react/src/components/Header/index.ts
  packages/web-react/src/components/Pill/index.ts
  packages/web-react/src/components/Tabs/index.ts
Labels: bug

#389 Docs(web-react): Typo in CheckboxField README
  packages/web-react/src/components/CheckboxField/README.md
Labels: documentation

#402 Feat(icons): Introduce `@lmc-eu/spirit-icons` package (refs #DS-282)
  .commitlintrc.js
  .github/CODEOWNERS
  README.md
  packages/icons/CHANGELOG.md
  packages/icons/LICENSE.md
  packages/icons/README.md
  packages/icons/package.json
Labels: feature

#407 Docs(web-react): Introduce instructions for contributors
  packages/web-react/CONTRIBUTING.md
Labels: documentation

#408 Docs(web-twig): How to publish changes to package readonly repository
  packages/web-twig/CONTRIBUTING.md
Labels: documentation
