Repository lmc-eu/spirit-design-system, pull requests merged in 2022-03, with the labels that each got.

#181 Feat(web): Add Stack component for vertical spacing #DS-165
  examples/web/index.html
  examples/web/jobs.html
  examples/web/src/jobs/jobs.scss
  packages/web/src/components/Stack/README.md
  packages/web/src/components/Stack/_Stack.scss
  packages/web/src/components/Stack/_theme.scss
  packages/web/src/components/Stack/index.scss
  packages/web/src/components/index.scss
Labels: feature

#184 Feat: Update Button variant colors and add new inverted variant #DS-148
  examples/web-react/src/demo.jsx
  examples/web/index.html
  examples/web/jobs.html
  packages/web-react/src/components/Button/Button.stories.tsx
  packages/web-react/src/components/Button/ButtonLink.stories.tsx
  packages/web-react/src/types/button.ts
  packages/web/src/components/Button/README.md
  packages/web/src/components/Button/_theme.scss
Labels: feature

#183 Feat(web): Introduce helpers and add typography classes #DS-167
  examples/web/index.html
  examples/web/jobs.html
  examples/web/package.json
  examples/web/src/jobs/jobs.scss
  packages/web/package.json
  packages/web/src/helpers/_typography.scss
  packages/web/src/helpers/index.scss
Labels: feature

#186 Feat(web): Introduce foundation CSS layer #DS-173
  .storybook/assets/stylesheets/index.scss
  examples/web-react/index.html
  examples/web-react/package.json
  examples/web-react/src/demo.jsx
  examples/web/index.html
  examples/web/jobs.html
  examples/web/package.json
  examples/web/src/jobs/jobs.scss
  packages/web/package.json
  packages/web/src/components/Container/_Container.scss
  packages/web/src/components/TextField/_TextField.scss
  packages/web/src/foundation/_box-sizing.scss
  packages/web/src/foundation/_reset.scss
  packages/web/src/foundation/_shared.scss
  packages/web/src/foundation/index.scss
  yarn.lock
Labels: feature

#179 Feat(web): Introduce CheckboxField component (refs #DS-136)
  examples/web/index.html
  examples/web/jobs.html
  examples/web/src/jobs/jobs.scss
  packages/web/src/components/CheckboxField/README.md
  packages/web/src/components/CheckboxField/_CheckboxField.scss
  packages/web/src/components/CheckboxField/_theme.scss
  packages/web/src/components/CheckboxField/index.scss
  packages/web/src/components/TextField/README.md
  packages/web/src/components/TextField/_TextField.scss
  packages/web/src/components/index.scss
  packages/web/src/tools/_accessibility.scss
Labels: feature

#197 Chore(repo): Format changelog when releasing new version
  package.json
Labels: maintenance

#198 Chore/publish using npx
  Makefile
Labels: maintenance

#209 Feat(web): Add svg escape tool and use non base64 encoded svg in Chec…
  packages/web/src/components/CheckboxField/_CheckboxField.scss
  packages/web/src/components/CheckboxField/_theme.scss
  packages/web/src/settings/_svg.scss
  packages/web/src/tools/_string.scss
  packages/web/src/tools/_svg.scss
Labels: feature

#207 Fix/normalize path
  .storybook/main.js
  packages/web/README.md
  packages/web/package.json
  packages/web/src/foundation/index.scss
Labels: bug

#180 Feat/ds 136 web react checkbox
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/CheckboxField/CheckboxField.stories.tsx
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/CheckboxField/README.md
  packages/web-react/src/components/CheckboxField/__tests__/CheckboxField.test.tsx
  packages/web-react/src/components/CheckboxField/__tests__/useCheckboxFieldStyleProps.test.tsx
  packages/web-react/src/components/CheckboxField/index.tsx
  packages/web-react/src/components/CheckboxField/useCheckboxFieldStyleProps.tsx
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/checkboxField.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/label.ts
  packages/web-react/src/types/message.ts
  packages/web-react/src/types/shared/index.ts
  packages/web-react/src/types/shared/inputs.ts
  packages/web-react/src/types/textField.ts
Labels: feature

#205 Feat(web-react): Introduce PasswordField component (refs …
  .storybook/assets/stylesheets/index.scss
  packages/web-react/src/components/TextField/PasswordField.stories.tsx
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/components/TextField/TextField.stories.tsx
  packages/web-react/src/components/TextField/TextField.tsx
  packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
  packages/web-react/src/components/TextField/__tests__/useTextFieldStyleProps.test.tsx
  packages/web-react/src/components/TextField/useTextFieldStyleProps.tsx
  packages/web-react/src/types/shared/inputs.ts
  packages/web-react/src/types/textField.ts
  packages/web-react/src/utils/__tests__/capitalize.test.ts
  packages/web-react/src/utils/capitalize.ts
Labels: feature

#206 Feat(web): Introduce Alert component (refs #DS-164)
  examples/web/index.html
  examples/web/jobs.html
  examples/web/src/jobs/jobs.scss
  packages/web/src/components/Alert/Alert.scss
  packages/web/src/components/Alert/README.md
  packages/web/src/components/Alert/_theme.scss
  packages/web/src/components/Alert/index.scss
  packages/web/src/components/index.scss
Labels: feature

#208 Feat(web): Add Utilities classes for display, margins, paddings and t…
  examples/web/index.html
  examples/web/jobs.html
  examples/web/src/jobs/jobs.scss
  packages/web/package.json
  packages/web/src/settings/_utilities.scss
  packages/web/src/tools/_utilities.scss
  packages/web/src/utilities/_utilities.scss
  packages/web/src/utilities/index.scss
Labels: feature

#213 Fix(web-react): Typo in TextField doc
  packages/web-react/src/components/TextField/README.md
Labels: bug

#217 BREAKING CHANGES(web-react): Remove `className` from all components r…
  packages/web-react/src/components/Button/ButtonLink.tsx
  packages/web-react/src/components/Container/Container.tsx
  packages/web-react/src/components/Grid/Grid.tsx
  packages/web-react/src/components/Grid/README.md
  packages/web-react/src/components/Stack/Stack.tsx
  packages/web-react/src/components/Tag/Tag.tsx
Labels: BC

#218 Feat/ds 160 filter out unwanted props
  packages/web-react/README.md
  packages/web-react/src/components/Button/Button.tsx
  packages/web-react/src/components/Button/ButtonLink.tsx
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/Container/Container.tsx
  packages/web-react/src/components/Grid/Grid.tsx
  packages/web-react/src/components/Stack/Stack.tsx
  packages/web-react/src/components/Tag/Tag.tsx
  packages/web-react/src/components/TextField/TextField.tsx
  packages/web-react/src/utils/__tests__/filterProps.test.ts
  packages/web-react/src/utils/filterProps.ts
Labels: feature

#219 BREAKING CHANGES(web-react): Use `is` prefix for boolean props (refs …
  packages/web-react/src/components/Button/Button.stories.tsx
  packages/web-react/src/components/Button/Button.tsx
  packages/web-react/src/components/Button/ButtonLink.stories.tsx
  packages/web-react/src/components/Button/__tests__/ButtonLink.test.tsx
  packages/web-react/src/components/Button/__tests__/useButtonStyleProps.test.tsx
  packages/web-react/src/components/Button/useButtonAriaProps.tsx
  packages/web-react/src/components/Button/useButtonStyleProps.tsx
  packages/web-react/src/components/CheckboxField/CheckboxField.stories.tsx
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/CheckboxField/README.md
  packages/web-react/src/components/CheckboxField/__tests__/CheckboxField.test.tsx
  packages/web-react/src/components/CheckboxField/__tests__/useCheckboxFieldStyleProps.test.tsx
  packages/web-react/src/components/CheckboxField/useCheckboxFieldStyleProps.tsx
  packages/web-react/src/components/Stack/Stack.stories.tsx
  packages/web-react/src/components/TextField/PasswordField.stories.tsx
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/components/TextField/TextField.stories.tsx
  packages/web-react/src/components/TextField/TextField.tsx
  packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
  packages/web-react/src/components/TextField/__tests__/useTextFieldStyleProps.test.tsx
  packages/web-react/src/components/TextField/useTextFieldStyleProps.tsx
  packages/web-react/src/types/button.ts
  packages/web-react/src/types/checkboxField.ts
  packages/web-react/src/types/shared/inputs.ts
  packages/web-react/src/types/textField.ts
Labels: BC

#220 Feat(web-react): Introduce Alert component (refs #DS-164)
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Alert/Alert.stories.tsx
  packages/web-react/src/components/Alert/Alert.tsx
  packages/web-react/src/components/Alert/README.md
  packages/web-react/src/components/Alert/__tests__/Alert.test.tsx
  packages/web-react/src/components/Alert/__tests__/useAlertStyleProps.test.tsx
  packages/web-react/src/components/Alert/index.ts
  packages/web-react/src/components/Alert/useAlertStyleProps.tsx
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/alert.ts
  packages/web-react/src/types/index.ts
Labels: feature

#235 BREAKING CHANGES(web-react): Build library for ES6
  packages/web-react/config/tsconfig.json
Labels: BC
