Repository lmc-eu/spirit-design-system, pull requests merged in 2022-10, with the labels that each got.

#495 BREAKING CHANGES(web-react): Do not provide non-existing CSS class `Tabs-content` in `Tabs` hook
  packages/web-react/src/components/Tabs/TabContent.tsx
  packages/web-react/src/components/Tabs/__tests__/TabContent.test.tsx
  packages/web-react/src/components/Tabs/__tests__/useTabsStyleProps.test.tsx
  packages/web-react/src/components/Tabs/useTabsStyleProps.tsx
Labels: BC

#497 Chore(repo): Introduce @tomassychra into codeowners
  .github/CODEOWNERS
Labels: maintenance

#511 Style(web): Upgrade stylelint config and fix errors #DS-322
  .stylelintrc.js
  packages/design-tokens/package.json
  packages/web-react/src/components/Tabs/__tests__/TabPane.test.tsx
  packages/web-react/src/components/Tabs/__tests__/useTabsStyleProps.test.tsx
  packages/web-react/src/components/Tabs/useTabsStyleProps.tsx
  packages/web-twig/src/Resources/components/Tabs/TabPane.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tabsDefault.twig__1.html
  packages/web/.prettierignore
  packages/web/package.json
  packages/web/src/js/__tests__/Tabs.test.ts
  packages/web/src/scss/components/Button/_Button.scss
  packages/web/src/scss/components/Button/_tools.scss
  packages/web/src/scss/components/CheckboxField/_CheckboxField.scss
  packages/web/src/scss/components/Container/_Container.scss
  packages/web/src/scss/components/Grid/_tools.scss
  packages/web/src/scss/components/Header/_Header.scss
  packages/web/src/scss/components/Header/_tools.scss
  packages/web/src/scss/components/Modal/_Modal.scss
  packages/web/src/scss/components/Pagination/_Pagination.scss
  packages/web/src/scss/components/RadioField/_RadioField.scss
  packages/web/src/scss/components/Stack/_Stack.scss
  packages/web/src/scss/components/Tabs/README.md
  packages/web/src/scss/components/Tabs/_Tabs.scss
  packages/web/src/scss/components/Tabs/_TabsPane.scss
  packages/web/src/scss/components/Tabs/index.html
  packages/web/src/scss/components/Tabs/index.scss
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/Tooltip/_Tooltip.scss
  packages/web/src/scss/components/Tooltip/_tools.scss
  packages/web/src/scss/foundation/_box-sizing.scss
  packages/web/src/scss/helpers/_links.scss
  packages/web/src/scss/helpers/_text.scss
  packages/web/src/scss/tools/_accessibility.scss
  packages/web/src/scss/tools/_links.scss
  packages/web/src/scss/tools/_reset.scss
  packages/web/src/scss/tools/_typography.scss
  yarn.lock
Labels: refactoring

#510 Fix(web-twig): Omit viewBox in reused SVGs to avoid scaling bug #JALL-7
  packages/web-twig/src/Twig/SvgExtension.php
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set alertDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set gridLayoutDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tabsDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldBaseMultiline.twig__1.html
  packages/web-twig/tests/fixtures/test_reusable.svg
Labels: bug

#512 Feature/svg stroke react icon
  packages/web-react/src/components/Icon/Icon.tsx
Labels: feature, BC

#516 Feat(web): Introduce `Dropdown` component (refs #DS-326)
  packages/web/src/scss/components/Dropdown/README.md
  packages/web/src/scss/components/Dropdown/_Dropdown.scss
  packages/web/src/scss/components/Dropdown/_theme.scss
  packages/web/src/scss/components/Dropdown/index.html
  packages/web/src/scss/components/Dropdown/index.scss
  packages/web/src/scss/components/index.scss
Labels: feature

#534 Feat(web): Add display grid utility classes (refs #FP-2166)
  packages/web/src/scss/settings/_utilities.scss
Labels: feature

#535 Fix(web): Collapse style linter fix #DS-275
  packages/web/src/scss/components/Collapse/_Collapse.scss
Labels: bug

#541 Feat(web): Add brand colors to text and background utilities
  packages/web/src/scss/settings/_utilities.scss
Labels: feature

#545 Fix(web-twig): Revert reuse icon viewBox, but set it to correct value…
  packages/web-twig/src/Twig/SvgExtension.php
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set alertDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
  packages/web-twig/tests/fixtures/test_reusable.svg
Labels: bug

#546 Feat(web): Update Button variants colors - disabled text colors and s…
  packages/web/src/scss/components/Button/_theme.scss
  packages/web/src/scss/components/Button/index.html
Labels: feature
