Repository lmc-eu/spirit-design-system, pull requests merged in 2022-06, with the labels that each got.

#349 Chore(ci): Set test pipeline timeout to 10 minutes
  .github/workflows/test.yaml
Labels: maintenance

#352 Fix(web): Find related header nav element base on data target attribute
  packages/web/src/js/Header.ts
Labels: bug

#348 Feat(web): Add `list-unstyled` helper class for unstyled lists
  packages/web/src/scss/helpers/_list.scss
  packages/web/src/scss/helpers/index.html
  packages/web/src/scss/helpers/index.scss
Labels: feature

#358 Deps(web-react): Add React 18 into peer dependencies (refs #333)
  packages/web-react/package.json
Labels: maintenance

#357 Chore(web): Fix deploy to GH pages by making links relative to root
  .github/workflows/deploy.yaml
  packages/web/index.html
  packages/web/package.json
Labels: maintenance

#339 Feat(web): Introduce Tab component #DS-230
  packages/web/index.html
  packages/web/src/scss/components/Tabs/README.md
  packages/web/src/scss/components/Tabs/_Tabs.scss
  packages/web/src/scss/components/Tabs/_theme.scss
  packages/web/src/scss/components/Tabs/index.html
  packages/web/src/scss/components/Tabs/index.scss
  packages/web/src/scss/components/index.scss
Labels: feature

#360 Chore(web): Fix missing helpers example on github pages
  packages/web/vite.config.ts
Labels: maintenance

#354 Fix(web): Trick to start animation when inject backdrop (refs #DS-218)
  packages/web/src/js/Header.ts
  packages/web/src/js/Modal.ts
  packages/web/src/js/utils/__tests__/index.test.ts
  packages/web/src/js/utils/index.ts
Labels: bug

#359 Chore: Move tsconfigs to package root
  packages/web-react/config/tsconfig.eslint.json
  packages/web-react/config/tsconfig.prod.json
  packages/web-react/package.json
  packages/web-react/scripts/resolveModuleIds.ts
  packages/web-react/tsconfig.json
  packages/web/config/rollup.config.js
  packages/web/config/tsconfig.eslint.json
  packages/web/package.json
  packages/web/tsconfig.json
Labels: maintenance
