Repository lmc-eu/spirit-design-system, pull requests merged in 2022-12, with the labels that each got.

#589 Feat(web-twig): Collapse Twig properties updates, tests, documentation
  packages/web-twig/src/Resources/components/Collapse/Collapse.twig
  packages/web-twig/src/Resources/components/Collapse/README.md
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set collapseDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set collapseOpened.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set collapseWithParentProp.twig__1.html
  packages/web-twig/tests/components-fixtures/collapseDefault.twig
  packages/web-twig/tests/components-fixtures/collapseOpened.twig
  packages/web-twig/tests/components-fixtures/collapseWithParentProp.twig
  packages/web/src/scss/components/Collapse/README.md
Labels: feature

#592 Make `Pagination` component inline to enable horizontal alignment #JALL-37
  packages/web/src/scss/components/Pagination/_Pagination.scss
  packages/web/src/scss/components/Pagination/index.html
Labels: feature

#594 Feat(web-react): Introduce React Accordion component #DS-447
  .storybook/assets/stylesheets/index.scss
  .storybook/decorators/IconGlobalDecorator.js
  .storybook/preview.js
  packages/web-react/src/components/Accordion/Accordion.stories.tsx
  packages/web-react/src/components/Accordion/Accordion.tsx
  packages/web-react/src/components/Accordion/AccordionContent.tsx
  packages/web-react/src/components/Accordion/AccordionContext.ts
  packages/web-react/src/components/Accordion/AccordionHeader.tsx
  packages/web-react/src/components/Accordion/AccordionItem.tsx
  packages/web-react/src/components/Accordion/AccordionItemContext.ts
  packages/web-react/src/components/Accordion/README.md
  packages/web-react/src/components/Accordion/__tests__/Accordion.test.tsx
  packages/web-react/src/components/Accordion/__tests__/AccordionContent.test.tsx
  packages/web-react/src/components/Accordion/__tests__/AccordionHeader.test.tsx
  packages/web-react/src/components/Accordion/__tests__/AccordionItem.test.tsx
  packages/web-react/src/components/Accordion/__tests__/useAccordionAriaProps.test.ts
  packages/web-react/src/components/Accordion/__tests__/useAccordionStyleProps.test.ts
  packages/web-react/src/components/Accordion/index.ts
  packages/web-react/src/components/Accordion/stories/Accordion.tsx
  packages/web-react/src/components/Accordion/stories/AccordionStayOpen.tsx
  packages/web-react/src/components/Accordion/stories/toggleValueByType.ts
  packages/web-react/src/components/Accordion/useAccordionAriaProps.ts
  packages/web-react/src/components/Accordion/useAccordionStyleProps.ts
  packages/web-react/src/components/Accordion/useOpenItem.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/accordion.ts
  packages/web-react/src/types/index.ts
Labels: feature

#595 Fix(web-react): Module `Transition` was not found while using Collapse
  packages/web-react/src/components/Collapse/Collapse.tsx
Labels: bug

#593 Feat(web-react): Introduce on auto close callback prop for Dropdown
  packages/web-react/src/components/Dropdown/Dropdown.tsx
  packages/web-react/src/components/Dropdown/README.md
  packages/web-react/src/components/Dropdown/useDropdown.ts
  packages/web-react/src/types/dropdown.ts
Labels: feature

#598 Feat(web-react): Introduce Uncontrolled Accordion #DS-459
  packages/web-react/src/components/Accordion/Accordion.stories.tsx
  packages/web-react/src/components/Accordion/Accordion.tsx
  packages/web-react/src/components/Accordion/AccordionContent.tsx
  packages/web-react/src/components/Accordion/AccordionContext.ts
  packages/web-react/src/components/Accordion/AccordionHeader.tsx
  packages/web-react/src/components/Accordion/AccordionItem.tsx
  packages/web-react/src/components/Accordion/AccordionItemContext.ts
  packages/web-react/src/components/Accordion/README.md
  packages/web-react/src/components/Accordion/UncontrolledAccordion.tsx
  packages/web-react/src/components/Accordion/__tests__/Accordion.test.tsx
  packages/web-react/src/components/Accordion/__tests__/AccordionItem.test.tsx
  packages/web-react/src/components/Accordion/__tests__/UncontrolledAccordion.test.tsx
  packages/web-react/src/components/Accordion/__tests__/useAccordion.test.ts
  packages/web-react/src/components/Accordion/index.ts
  packages/web-react/src/components/Accordion/stories/Accordion.tsx
  packages/web-react/src/components/Accordion/stories/AccordionHtml.tsx
  packages/web-react/src/components/Accordion/stories/AccordionProps.tsx
  packages/web-react/src/components/Accordion/stories/AccordionStayOpen.tsx
  packages/web-react/src/components/Accordion/stories/AccordionUncontrolled.tsx
  packages/web-react/src/components/Accordion/stories/AccordionUncontrolledProps.tsx
  packages/web-react/src/components/Accordion/stories/AccordionUncontrolledStayOpen.tsx
  packages/web-react/src/components/Accordion/useAccordion.ts
  packages/web-react/src/types/accordion.ts
Labels: feature

#603 Fix(web): Remove block margin from form field of type Item
  packages/web/src/scss/tools/_form-fields.scss
Labels: bug

#557 Fix(web): Prevent from dropdown content overflow outside its container
  packages/web/src/scss/components/Dropdown/_Dropdown.scss
Labels: bug

#602 Fix(web): Fix Accordion styles
  packages/web/src/scss/components/Accordion/_Accordion.scss
  packages/web/src/scss/components/Accordion/_theme.scss
  packages/web/src/scss/components/Accordion/index.html
Labels: bug

#608 Fix(web-react): Fix export of the ButtonLink component #DS-519
  packages/web-react/src/components/Button/index.ts
Labels: bug

#614 Docs(web-twig): Document the missing input types of `TextField`: `number`, `search`, `tel`, `url`
  packages/web-twig/src/Resources/components/TextArea/README.md
  packages/web-twig/src/Resources/components/TextField/README.md
  packages/web-twig/src/Resources/components/TextFieldBase/README.md
Labels: documentation

#612 Fix(web-react): Add missing component exports
  packages/web-react/src/components/index.ts
Labels: bug

#613 Feat(web-react): Introduce the missing input types of `TextField`: `number`, `search`, `tel`, `url`
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/components/TextField/stories/TextFieldType.tsx
  packages/web-react/src/components/TextFieldBase/README.md
  packages/web-react/src/types/textField.ts
Labels: feature

#615 Fix(web): Only show `Item` background during interactions on hover-enabled devices
  packages/web/src/scss/tools/_form-fields.scss
Labels: bug
