Repository lmc-eu/spirit-design-system, pull requests merged in 2022-05, with the labels that each got.

#282 Feat(web): Add support for TextField's size attribute #DS-154
  examples/web/index.html
  examples/web/jobs.html
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/_theme.scss
Labels: feature

#292 Refactor/dom content loaded
  packages/web/src/js/Header.ts
  packages/web/src/js/Password.ts
  packages/web/src/js/utils/ComponentFunctions.ts
  packages/web/src/js/utils/__tests__/ComponentFunctions.test.ts
Labels: refactoring

#310 Fix(web): Update `TextField` label color according to design changes
  packages/web/src/scss/components/TextField/_theme.scss
Labels: bug

#320 Chore(ci): Try to fix segmentation fault on github actions
  package.json
Labels: maintenance

#316 Fix(web): Load script using defer instead of async in examples
  examples/web/index.html
Labels: bug

#318 Feat(web): Add `.link-stretched` helper class and mixin
  packages/web/src/scss/helpers/_links.scss
  packages/web/src/scss/tools/_links.scss
Labels: feature

#319 Refactor(web): Reduce specificity of shared bottom margin to make overrides easier
  packages/web/src/scss/foundation/_shared.scss
Labels: refactoring

#314 Docs(web): Remove examples because we have new dev-stack (refs #DS-237)
  examples/web/.gitignore
  examples/web/index.html
  examples/web/jobs.html
  examples/web/package.json
  examples/web/postcss.config.js
  examples/web/src/jobs/@tokens.scss
  examples/web/src/jobs/jobs.scss
  package.json
Labels: feature

#324 Chore(ci): Use @swc to speed up Jest tests
  packages/web-react/config/jest/config.js
  packages/web-react/package.json
  packages/web/config/jest.config.js
  packages/web/package.json
  yarn.lock
Labels: maintenance

#327 Feat(web): Introduce breakout helper and mixin to expand content out of `Container`
  packages/web/src/scss/helpers/_breakout.scss
  packages/web/src/scss/helpers/index.html
  packages/web/src/scss/helpers/index.scss
  packages/web/src/scss/tools/_breakout.scss
Labels: feature

#307 Feat(web): Add simple Modal component #DS-211
  packages/web/index.html
  packages/web/partials/layout.hbs
  packages/web/src/js/Modal.ts
  packages/web/src/js/index.esm.ts
  packages/web/src/js/index.umd.ts
  packages/web/src/scss/components/Modal/README.md
  packages/web/src/scss/components/Modal/_Modal.scss
  packages/web/src/scss/components/Modal/_theme.scss
  packages/web/src/scss/components/Modal/index.html
  packages/web/src/scss/components/Modal/index.scss
  packages/web/src/scss/components/index.scss
Labels: feature

#342 Chore(ci): Introduce Netlify config for Storybook documentation
  netlify.toml
Labels: maintenance
