Repository lmc-eu/spirit-design-system, pull requests merged in 2022-02, with the labels that each got.

#136 Chore: Prefer javascript for configuration if possible
  .stylelintrc.js
  packages/design-tokens/package.json
  packages/web/package.json
Labels: maintenance

#134 Chore: Remove dependency updates by Dependabot
  .github/dependabot.yaml
Labels: maintenance

#145 Feat(web-react): Pass down an access to button dom via ref prop
  packages/web-react/src/components/Button/Button.tsx
Labels: feature

#146 Chore: Schedule code quality checks to run every day even on main branch
  .github/workflows/test.yaml
Labels: maintenance

#123 DS-124 Feat: Add background interactive color tokens and update disabled color
  packages/design-tokens/src/scss/_colors.scss
Labels: feature

#154 Fix(web-react): Add missing children prop in buttons
  packages/web-react/src/components/Button/Button.tsx
  packages/web-react/src/components/Button/ButtonLink.tsx
  packages/web-react/src/components/Button/__tests__/Button.test.tsx
  packages/web-react/src/components/Button/__tests__/ButtonLink.test.tsx
Labels: bug

#148 DS-80 Feat: Implement Grid component to spirit-web and showcase it in…
  examples/web/index.html
  examples/web/jobs.html
  examples/web/src/jobs/jobs.scss
  packages/design-tokens/src/scss/_layout.scss
  packages/web/src/components/Grid/README.md
  packages/web/src/components/Grid/_Grid.scss
  packages/web/src/components/Grid/_theme.scss
  packages/web/src/components/Grid/_tools.scss
  packages/web/src/components/Grid/index.scss
  packages/web/src/components/index.scss
Labels: feature

#155 Chore(web-react): Change codeowners for web-react package
  .github/CODEOWNERS
Labels: maintenance

#167 Docs(web-react): Add missing jsdoc blocks in build scripts
  packages/web-react/config/rollup.config.js
  packages/web-react/scripts/entryPoints.js
Labels: documentation

#166 Refactor(web-react): Hook `useClassNamePrefix` now accept argument cl…
  packages/web-react/src/components/Button/useButtonStyleProps.tsx
  packages/web-react/src/components/Tag/Tag.tsx
  packages/web-react/src/hooks/useClassNamePrefix.tsx
Labels: refactoring

#144 Feat/react container
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Container/Container.stories.tsx
  packages/web-react/src/components/Container/Container.tsx
  packages/web-react/src/components/Container/README.md
  packages/web-react/src/components/Container/__tests__/Container.test.tsx
  packages/web-react/src/components/Container/index.tsx
  packages/web-react/src/components/index.tsx
Labels: feature

#169 Chore: Set up storybook to use Webpack 5
  .storybook/main.js
  package.json
  yarn.lock
Labels: maintenance

#170 Chore: Publish code coverage report to coveralls.io
  .github/workflows/test.yaml
  README.md
Labels: maintenance

#172 Feat(web-react): Introduce TextField component (refs #DS-120)
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/components/TextField/TextField.stories.tsx
  packages/web-react/src/components/TextField/TextField.tsx
  packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
  packages/web-react/src/components/TextField/__tests__/useTextFieldStyleProps.test.tsx
  packages/web-react/src/components/TextField/index.tsx
  packages/web-react/src/components/TextField/useTextFieldStyleProps.tsx
  packages/web-react/src/components/index.tsx
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/textField.ts
Labels: feature
