Repository lmc-eu/spirit-design-system, pull requests merged in 2023-06, with the labels that each got.

#870 Docs(web-twig): Fix developer preview title
  apps/web-twig-demo/templates/layout/base.html.twig
  apps/web-twig-demo/templates/partials/header.html.twig
Labels: documentation

#848 Chore(ci): Test builds also on Node.js v20
  .github/workflows/build.yaml
Labels: maintenance

#876 Docs(web): Document how to add a placeholder to the Select #DS-810
  packages/web/src/scss/components/Select/README.md
  packages/web/src/scss/components/Select/index.html
Labels: documentation

#873 Feat(web-twig): Introduce Select component #DS-790
  packages/web-twig/src/Resources/components/Select/README.md
  packages/web-twig/src/Resources/components/Select/Select.stories.twig
  packages/web-twig/src/Resources/components/Select/Select.twig
  packages/web-twig/src/Resources/components/Select/stories/Select.twig
  packages/web-twig/src/Resources/components/Select/stories/SelectDisabled.twig
  packages/web-twig/src/Resources/components/Select/stories/SelectFluid.twig
  packages/web-twig/src/Resources/components/Select/stories/SelectHelperText.twig
  packages/web-twig/src/Resources/components/Select/stories/SelectLabelHidden.twig
  packages/web-twig/src/Resources/components/Select/stories/SelectValidationState.twig
  packages/web-twig/src/Resources/twig-components/select.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectDisabled.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectFluid.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectHelperText.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectLabelHidden.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set selectValidationState.twig__1.html
  packages/web-twig/tests/components-fixtures/selectDefault.twig
  packages/web-twig/tests/components-fixtures/selectDisabled.twig
  packages/web-twig/tests/components-fixtures/selectFluid.twig
  packages/web-twig/tests/components-fixtures/selectHelperText.twig
  packages/web-twig/tests/components-fixtures/selectLabelHidden.twig
  packages/web-twig/tests/components-fixtures/selectValidationState.twig
Labels: feature

#874 Fix(web-react): Set `hasSpacing` default value as `false` in the Stack component
  packages/web-react/src/components/Stack/README.md
  packages/web-react/src/components/Stack/Stack.tsx
  packages/web-react/src/components/Stack/stories/argTypes.ts
Labels: bug

#871 Feat(web): Enable customization of `ScrollView` shadows via custom properties
  packages/web/src/scss/components/ScrollView/README.md
  packages/web/src/scss/components/ScrollView/_ScrollView.scss
  packages/web/src/scss/components/ScrollView/index.html
Labels: feature

#884 Refactor(web): Use inset in CSS instead of separate values
  packages/web/src/scss/components/Header/_HeaderDialog.scss
  packages/web/src/scss/components/Header/_tools.deprecated.scss
  packages/web/src/scss/components/TextField/_TextField.scss
Labels: refactoring

#885 Feat(web-twig): Make the preferred height and max height of `Modal` customizable #DS-723
  packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
  packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/stories/ModalBasic.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalStacking.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalComposedDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/modalComposedDefault.twig
Labels: feature

#893 Chore(repo): Add missing dependency `react-syntax-higlighter`
  package.json
  yarn.lock
Labels: maintenance

#867 Chore(repo): Introduce pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: maintenance

#879 Feat(web-react): Introduce Pagination component #DS-329
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Pagination/Pagination.stories.ts
  packages/web-react/src/components/Pagination/Pagination.tsx
  packages/web-react/src/components/Pagination/PaginationButtonLink.tsx
  packages/web-react/src/components/Pagination/PaginationItem.tsx
  packages/web-react/src/components/Pagination/PaginationLink.tsx
  packages/web-react/src/components/Pagination/PaginationLinkNext.tsx
  packages/web-react/src/components/Pagination/PaginationLinkPrevious.tsx
  packages/web-react/src/components/Pagination/README.md
  packages/web-react/src/components/Pagination/__tests__/Pagination.test.tsx
  packages/web-react/src/components/Pagination/__tests__/PaginationButtonLink.test.tsx
  packages/web-react/src/components/Pagination/__tests__/PaginationItem.test.tsx
  packages/web-react/src/components/Pagination/__tests__/PaginationLink.test.tsx
  packages/web-react/src/components/Pagination/__tests__/PaginationLinkNext.test.tsx
  packages/web-react/src/components/Pagination/__tests__/PaginationLinkPrevious.test.tsx
  packages/web-react/src/components/Pagination/__tests__/usePaginationStyleProps.test.ts
  packages/web-react/src/components/Pagination/constants.ts
  packages/web-react/src/components/Pagination/demo/index.tsx
  packages/web-react/src/components/Pagination/index.html
  packages/web-react/src/components/Pagination/index.ts
  packages/web-react/src/components/Pagination/stories/PaginationCurrentFirst.tsx
  packages/web-react/src/components/Pagination/stories/PaginationCurrentFirstCentered.tsx
  packages/web-react/src/components/Pagination/stories/PaginationCurrentLast.tsx
  packages/web-react/src/components/Pagination/stories/PaginationCurrentMiddle.tsx
  packages/web-react/src/components/Pagination/stories/argTypes.ts
  packages/web-react/src/components/Pagination/usePaginationStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/pagination.ts
Labels: feature

#898 Chore(web-react): Set correct path according to the base directory
  packages/web-react/netlify.toml
Labels: maintenance

#894 Improve documentation of the TextArea
  packages/web-twig/src/Resources/components/TextArea/README.md
Labels: documentation

#892 Fix(web): Modal close on mobile safari #DS-824
  packages/web/src/js/Modal.ts
  packages/web/src/js/dom/EventHandler.ts
  packages/web/src/js/utils/__tests__/ComponentFunctions.test.ts
Labels: bug

#891 Fix(web-react): Stacked Modal Composed closes both dialog #DS-740
  packages/web-react/docs/stories/examples/ModalComposedStacked.stories.tsx
  packages/web-react/src/components/ModalComposed/README.md
  packages/web-react/src/hooks/useClickOutside.ts
Labels: bug

#903 Docs(web): Why is the event listener not passive by default
  packages/web/src/js/dom/EventHandler.ts
Labels: bug

#897 Feat(web-twig): Allow pass `translate` attribute to the `Heading` and `Text` components
  packages/web-twig/src/Resources/components/Heading/Heading.twig
  packages/web-twig/src/Resources/components/Text/Text.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set headingDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/headingDefault.twig
  packages/web-twig/tests/components-fixtures/textDefault.twig
Labels: feature

#896 Fix(web-react): TextArea is using native maxlength attribute
  packages/web-react/src/components/TextArea/stories/argTypes.ts
  packages/web-react/src/types/textArea.ts
Labels: bug

#906 Docs(repo): Clean up of unused examples
  .renovaterc.json
  examples/index.html
  examples/web-react/.browserslistrc
  examples/web-react/.gitignore
  examples/web-react/babel.config.js
  examples/web-react/index.html
  examples/web-react/package.json
  examples/web-react/src/demo.jsx
  examples/web-react/webpack.config.js
  package.json
Labels: maintenance

#916 Fix(web-twig): Do not render space after label #DS-842
  packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig
Labels: bug

#907 Chore(demo): Display only web-twig dirs where stories exists
  apps/web-twig-demo/src/Controller/DefaultController.php
Labels: documentation

#913 Fix(web): FileUploader cannot remove files with same names
  packages/web/src/js/FileUploader.ts
Labels: bug

#921 Fix(web): Escape attachment file name in FileUploader
  packages/web/src/js/FileUploader.ts
Labels: bug
