Repository lmc-eu/spirit-design-system, pull requests merged in 2023-12, with the labels that each got.

#1169 Fix(web-react): HeaderDialog demo missed closeOnBackdropClick prop #DS-1075
  packages/web-react/src/components/Dialog/Dialog.tsx
  packages/web-react/src/components/Modal/Modal.tsx
Labels: bug

#1172 Chore(repo): Introduce Omlet analysis config file
  .omletrc.js
Labels: maintenance

#1164 Feat(web): Extend Tooltip Floating UI example, deprecate CSS modifier…
  packages/web/src/scss/components/Tooltip/README.md
  packages/web/src/scss/components/Tooltip/_Tooltip.scss
  packages/web/src/scss/components/Tooltip/floating-ui-example.mjs
  packages/web/src/scss/components/Tooltip/index.html
  packages/web/src/scss/settings/_dictionaries.scss
  packages/web/src/scss/settings/_feature-flags.scss
  packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
  packages/web/src/scss/tools/__tests__/_placement.test.scss
  packages/web/src/scss/tools/_dictionaries.scss
  packages/web/src/scss/tools/_placement.scss
Labels: feature

#1178 Feat(web-twig): Introduce Full Floating UI demo to Tooltip, update internal implementation #DS-1084
  packages/web-twig/src/Resources/components/Tooltip/Tooltip.stories.twig
  packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__fixtures__/tooltip.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltip.twig.snap.html
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipFloatingUI.twig
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipPlacements.twig
Labels: feature

#1180 Feat(analytics): Add a timestamp to the scanner result files
  packages/analytics/src/constants.ts
  packages/analytics/src/processors/spiritAdoptionProcessor.ts
  packages/analytics/src/scanners/twig-scanner.config.ts
Labels: feature

#1177 Fix(web-react): Mock window.scrollTo in test of useScrollControl hook
  packages/web-react/src/hooks/__tests__/useScrollControl.test.ts
Labels: bug

#1182 Fix(analytics): HTML element is not the PascalCase component
  packages/analytics/src/scanners/__tests__/twigScanner.test.ts
  packages/analytics/src/scanners/twigScanner.ts
Labels: bug
