Repository lmc-eu/spirit-design-system, pull requests merged in 2023-02, with the labels that each got.

#660 Chore(ci): Make package version independently
  Makefile
  bin/ci/semver.sh
Labels: maintenance

#647 Chore(ci): Test builds on multiple Node.js versions
  .github/workflows/build.yaml
Labels: maintenance

#659 Chore(web-react): Add missing package entry points for distribution
  packages/web-react/scripts/entryPoints.js
Labels: maintenance

#671 Fix(web-react): Tabs transfer properties #DS-401
  packages/web-react/src/components/Tabs/README.md
  packages/web-react/src/components/Tabs/TabContent.tsx
  packages/web-react/src/components/Tabs/TabContext.tsx
  packages/web-react/src/components/Tabs/TabItem.tsx
  packages/web-react/src/components/Tabs/TabLink.tsx
  packages/web-react/src/components/Tabs/TabList.tsx
  packages/web-react/src/components/Tabs/Tabs.tsx
  packages/web-react/src/components/Tabs/UncontrolledTabs.tsx
Labels: bug

#676 Fix(web-twig): Remove `data-component` attribute from Modal
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
Labels: bug

#678 Fix(web-twig): Deprecated `size` prop on Icon cannot modify dimensions
  packages/web-twig/src/Resources/components/Icon/Icon.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set alertDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set iconDefault.twig__1.html
Labels: bug

#677 Fix(web-react): Add missing id prop for TextFieldBase input element
  packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
  packages/web-react/src/components/TextFieldBase/__tests__/TextFieldBase.test.tsx
Labels: bug

#690 Fix(web-react): Make `size` prop on Heading component optional
  packages/web-react/src/types/heading.ts
Labels: bug

#698 Docs(web-react): Fix comment in ChildrenProps interface
  packages/web-react/src/types/shared/index.ts
Labels: documentation

#675 Feat(web-twig): Introduce Modal Composed with subcomponents #DS-507
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/src/Resources/components/Modal/ModalBody.twig
  packages/web-twig/src/Resources/components/Modal/ModalComposed.twig
  packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
  packages/web-twig/src/Resources/components/Modal/ModalFooter.twig
  packages/web-twig/src/Resources/components/Modal/ModalHeader.twig
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/twig-components/modalBody.twig
  packages/web-twig/src/Resources/twig-components/modalComposed.twig
  packages/web-twig/src/Resources/twig-components/modalDialog.twig
  packages/web-twig/src/Resources/twig-components/modalFooter.twig
  packages/web-twig/src/Resources/twig-components/modalHeader.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalComposedDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/modalComposedDefault.twig
Labels: feature

#696 Chore(exporter-scss): Rebuild generated functions with updated Vite
  exporters/scss/generated/functions.js
Labels: bug

#701 Fix(web): In `Modal`, make only text selectable to prevent interaction glitches in Chrome
  packages/web/src/scss/components/Modal/_Modal.scss
Labels: bug

#694 Feat(web-react): Introduction ModalComposed component #DS-506
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Modal/Modal.tsx
  packages/web-react/src/components/ModalComposed/ModalComposed.stories.tsx
  packages/web-react/src/components/ModalComposed/ModalComposed.tsx
  packages/web-react/src/components/ModalComposed/ModalComposedBody.tsx
  packages/web-react/src/components/ModalComposed/ModalComposedContext.ts
  packages/web-react/src/components/ModalComposed/ModalComposedDialog.tsx
  packages/web-react/src/components/ModalComposed/ModalComposedFooter.tsx
  packages/web-react/src/components/ModalComposed/ModalComposedHeader.tsx
  packages/web-react/src/components/ModalComposed/README.md
  packages/web-react/src/components/ModalComposed/__tests__/ModalComposed.test.tsx
  packages/web-react/src/components/ModalComposed/__tests__/ModalComposedBody.test.tsx
  packages/web-react/src/components/ModalComposed/__tests__/ModalComposedDialog.test.tsx
  packages/web-react/src/components/ModalComposed/__tests__/ModalComposedFooter.test.tsx
  packages/web-react/src/components/ModalComposed/__tests__/ModalComposedHeader.test.tsx
  packages/web-react/src/components/ModalComposed/__tests__/useModalComposedStyleProps.test.ts
  packages/web-react/src/components/ModalComposed/index.ts
  packages/web-react/src/components/ModalComposed/stories/ModalComposed.tsx
  packages/web-react/src/components/ModalComposed/stories/ModalComposedHtml.tsx
  packages/web-react/src/components/ModalComposed/stories/ModalComposedProps.tsx
  packages/web-react/src/components/ModalComposed/stories/ModalComposedWithLongText.tsx
  packages/web-react/src/components/ModalComposed/useModalComposedStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/hooks/useDeprecatedMessage.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/modalComposed.ts
  packages/web-react/src/types/shared/element.ts
  packages/web-react/src/types/shared/index.ts
  packages/web-react/src/types/shared/style.ts
Labels: feature

#697 Refactor(web-react): Introduce `SizeProps` type as generic for size prop
  packages/web-react/src/types/heading.ts
  packages/web-react/src/types/shared/dictionaries.ts
  packages/web-react/src/types/text.ts
Labels: refactoring

#711 Fix(web): Component event handler missing target
  packages/web/src/js/Password.ts
Labels: bug

#706 Feat(web): Introduce new `Offcanvas` plugin derived from the `Header`plugin (refs #DS-240)
  packages/web/src/js/Offcanvas.ts
  packages/web/src/js/__tests__/Offcanvas.test.ts
  packages/web/src/js/dom/SelectorEngine.ts
  packages/web/src/js/index.esm.ts
  packages/web/src/js/index.umd.ts
Labels: feature

#707 Feat(web): Introduce new `Header` with subcomponents #DS-424
  packages/web/src/js/dom/SelectorEngine.ts
  packages/web/src/scss/components/Header/README.md
  packages/web/src/scss/components/Header/_Header.deprecated.scss
  packages/web/src/scss/components/Header/_Header.scss
  packages/web/src/scss/components/Header/_HeaderDesktopActions.scss
  packages/web/src/scss/components/Header/_HeaderDialog.scss
  packages/web/src/scss/components/Header/_HeaderDialogActions.scss
  packages/web/src/scss/components/Header/_HeaderDialogCloseButton.scss
  packages/web/src/scss/components/Header/_HeaderDialogLink.scss
  packages/web/src/scss/components/Header/_HeaderDialogNav.scss
  packages/web/src/scss/components/Header/_HeaderDialogNavItem.scss
  packages/web/src/scss/components/Header/_HeaderDialogText.scss
  packages/web/src/scss/components/Header/_HeaderLink.scss
  packages/web/src/scss/components/Header/_HeaderMobileActions.scss
  packages/web/src/scss/components/Header/_HeaderNav.scss
  packages/web/src/scss/components/Header/_HeaderNavItem.scss
  packages/web/src/scss/components/Header/_theme.deprecated.scss
  packages/web/src/scss/components/Header/_theme.scss
  packages/web/src/scss/components/Header/_tools.deprecated.scss
  packages/web/src/scss/components/Header/_tools.scss
  packages/web/src/scss/components/Header/index.html
  packages/web/src/scss/components/Header/index.scss
Labels: feature
