Repository lmc-eu/spirit-design-system, pull requests merged in 2023-05, with the labels that each got.

#820 Chore/ci cache
  .github/workflows/build.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/component-analysis.yaml
  .github/workflows/deploy.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: maintenance

#827 Fix(web): Remove additional whitespace added by template tag
  packages/web/src/js/FileUploader.ts
Labels: bug

#804 Feat(web-react): Introduction of FileUploader component #DS-683
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/FileUploader/AttachmentDismissButton.tsx
  packages/web-react/src/components/FileUploader/FileUploader.stories.ts
  packages/web-react/src/components/FileUploader/FileUploader.tsx
  packages/web-react/src/components/FileUploader/FileUploaderAttachment.tsx
  packages/web-react/src/components/FileUploader/FileUploaderContext.ts
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
  packages/web-react/src/components/FileUploader/FileUploaderList.tsx
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/components/FileUploader/UncontrolledFileUploader.stories.tsx
  packages/web-react/src/components/FileUploader/UncontrolledFileUploader.tsx
  packages/web-react/src/components/FileUploader/__tests__/FileUploader.test.tsx
  packages/web-react/src/components/FileUploader/__tests__/FileUploaderInput.test.tsx
  packages/web-react/src/components/FileUploader/__tests__/FileUploaderList.test.tsx
  packages/web-react/src/components/FileUploader/__tests__/useFileQueue.test.ts
  packages/web-react/src/components/FileUploader/__tests__/useFileUploaderStyleProps.test.ts
  packages/web-react/src/components/FileUploader/constants.ts
  packages/web-react/src/components/FileUploader/index.ts
  packages/web-react/src/components/FileUploader/stories/FileUploader.tsx
  packages/web-react/src/components/FileUploader/stories/FileUploaderAccept.tsx
  packages/web-react/src/components/FileUploader/stories/FileUploaderUncontrolled.tsx
  packages/web-react/src/components/FileUploader/stories/FileUploaderValidationState.tsx
  packages/web-react/src/components/FileUploader/stories/FormWithFileUploader.tsx
  packages/web-react/src/components/FileUploader/stories/FormWithUncontrolledFileUploader.tsx
  packages/web-react/src/components/FileUploader/stories/argTypesUncontrolled.ts
  packages/web-react/src/components/FileUploader/useFileQueue.ts
  packages/web-react/src/components/FileUploader/useFileUploaderAttachment.ts
  packages/web-react/src/components/FileUploader/useFileUploaderInput.ts
  packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts
  packages/web-react/src/components/FileUploader/utils.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/hooks/index.ts
  packages/web-react/src/hooks/useDragAndDrop.ts
  packages/web-react/src/hooks/useValidationText.tsx
  packages/web-react/src/types/fileUploader.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/shared/dragAndDrop.ts
  packages/web-react/src/types/shared/index.ts
  packages/web-react/src/types/shared/inputs.ts
Labels: feature

#829 Feat(exporter-scss): Improve Gradients, angle variable and unify naming, but leave JDS exception
  exporters/scss/README.md
  exporters/scss/exporter.json
  exporters/scss/generated/functions.js
  exporters/scss/src/colors.pr
  exporters/scss/src/gradients.pr
  exporters/scss/src/js/generators/simple.ts
Labels: feature

#817 Fix(web): Maximum number of files in the queue during drag and drop
  packages/web/src/js/FileUploader.ts
Labels: bug

#832 Docs(web-react): Remove viewMode in Storybook causing preview bugs #DS-733
  .storybook/preview.js
Labels: documentation

#833 Feat(web-react): Add iconName prop to FileUploader components #DS-752
  packages/web-react/src/components/FileUploader/FileUploaderAttachment.tsx
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/components/FileUploader/UncontrolledFileUploader.tsx
  packages/web-react/src/components/FileUploader/stories/FileUploaderUncontrolled.tsx
  packages/web-react/src/components/FileUploader/stories/argTypesUncontrolled.ts
  packages/web-react/src/types/fileUploader.ts
Labels: feature

#835 Feat(web,web-react,web-twig): Allow multiline message in TextArea #DS-738
  packages/web-react/src/components/TextArea/README.md
  packages/web-react/src/components/TextArea/__tests__/TextArea.test.tsx
  packages/web-react/src/components/TextArea/stories/TextAreaValidationState.tsx
  packages/web-react/src/components/TextArea/stories/argTypes.ts
  packages/web-twig/src/Resources/components/TextArea/README.md
  packages/web-twig/src/Resources/components/TextArea/TextArea.stories.twig
  packages/web-twig/src/Resources/components/TextArea/stories/TextAreaMessageMultiple.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textAreaWithMultilineMessage.twig__1.html
  packages/web-twig/tests/components-fixtures/textAreaWithMultilineMessage.twig
  packages/web/src/scss/components/TextArea/README.md
  packages/web/src/scss/components/TextArea/index.html
Labels: feature

#837 Feat(web,web-react,web-twig): Allow multiline validationText in FileUploaderInput #DS-737
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/components/FileUploader/__tests__/FileUploaderInput.test.tsx
  packages/web-react/tests/providerTests/validationTextPropsTest.tsx
  packages/web-twig/src/Resources/components/FileUploader/FileUploaderInput.twig
  packages/web-twig/src/Resources/components/FileUploader/README.md
  packages/web-twig/src/Resources/components/FileUploader/stories/FileUploaderInputValidationStates.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set fileUploaderInput.twig__1.html
  packages/web/src/scss/components/FileUploader/index.html
Labels: feature

#836 Feat(web,web-react,web-twig): Allow multiline message in CheckboxField #DS-735
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/CheckboxField/README.md
  packages/web-react/src/components/CheckboxField/__tests__/CheckboxField.test.tsx
  packages/web-react/src/components/CheckboxField/stories/CheckboxFieldValidationState.tsx
  packages/web-react/src/components/CheckboxField/stories/argTypes.ts
  packages/web-react/tests/providerTests/validationTextPropsTest.tsx
  packages/web-twig/src/Resources/components/CheckboxField/CheckboxField.twig
  packages/web-twig/src/Resources/components/CheckboxField/README.md
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldValidationState.twig
  packages/web/src/scss/components/CheckboxField/README.md
  packages/web/src/scss/components/CheckboxField/index.html
Labels: feature

#853 Fix(web-react): Fix missing property for hiding label on input
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/components/FileUploader/UncontrolledFileUploader.tsx
  packages/web-react/src/components/FileUploader/stories/argTypesUncontrolled.ts
  packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts
  packages/web-react/src/types/fileUploader.ts
Labels: bug

#844 Feat(web): Introduce `ScrollView` component #DS-449
  packages/web/src/js/ScrollView.ts
  packages/web/src/js/index.esm.ts
  packages/web/src/js/index.umd.ts
  packages/web/src/js/utils/Debounce.ts
  packages/web/src/js/utils/__tests__/Debounce.test.ts
  packages/web/src/js/utils/index.ts
  packages/web/src/scss/components/ScrollView/README.md
  packages/web/src/scss/components/ScrollView/_ScrollView.scss
  packages/web/src/scss/components/ScrollView/_theme.scss
  packages/web/src/scss/components/ScrollView/index.html
  packages/web/src/scss/components/ScrollView/index.scss
  packages/web/src/scss/components/index.scss
Labels: feature

#854 Feat(web): Enhance `ScrollView` scrolling indicators to be shadows, borders, or both #DS-796
  packages/web/src/scss/components/ScrollView/README.md
  packages/web/src/scss/components/ScrollView/_ScrollView.scss
  packages/web/src/scss/components/ScrollView/_theme.scss
  packages/web/src/scss/components/ScrollView/index.html
Labels: feature

#845 Feat(web-twig): Add ScrollView component #DS-465
  packages/web-twig/src/Resources/components/ScrollView/README.md
  packages/web-twig/src/Resources/components/ScrollView/ScrollView.stories.twig
  packages/web-twig/src/Resources/components/ScrollView/ScrollView.twig
  packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewDefault.twig
  packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewHiddenScrollbar.twig
  packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewHorizontal.twig
  packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewHorizontalBreakout.twig
  packages/web-twig/src/Resources/components/ScrollView/stories/ScrollViewScrollingIndicators.twig
  packages/web-twig/src/Resources/twig-components/scrollView.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set scrollViewDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/scrollViewDefault.twig
Labels: feature

#849 Feat(web-react): Introduce ScrollView component #DS-464
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/ScrollView/README.md
  packages/web-react/src/components/ScrollView/ScrollView.stories.ts
  packages/web-react/src/components/ScrollView/ScrollView.tsx
  packages/web-react/src/components/ScrollView/__tests__/ScrollView.test.tsx
  packages/web-react/src/components/ScrollView/__tests__/useScrollViewStyleProps.test.ts
  packages/web-react/src/components/ScrollView/constants.ts
  packages/web-react/src/components/ScrollView/index.ts
  packages/web-react/src/components/ScrollView/stories/ScrollView.tsx
  packages/web-react/src/components/ScrollView/stories/ScrollViewHorizontal.tsx
  packages/web-react/src/components/ScrollView/stories/ScrollViewScrollbarDisabled.tsx
  packages/web-react/src/components/ScrollView/stories/argTypes.ts
  packages/web-react/src/components/ScrollView/useScrollPosition.ts
  packages/web-react/src/components/ScrollView/useScrollViewStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/constants/alignment.ts
  packages/web-react/src/constants/direction.ts
  packages/web-react/src/constants/index.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/scrollView.ts
  packages/web-react/src/types/shared/alignments.ts
  packages/web-react/src/types/shared/dictionaries.ts
  packages/web-react/src/types/shared/directions.ts
  packages/web-react/src/types/shared/index.ts
  packages/web-react/src/utils/debounce.ts
  packages/web-react/src/utils/index.ts
Labels: feature

#856 Fix(web-react): Unexported `Tabs` components
  packages/web-react/src/components/Tabs/index.ts
Labels: bug

#857 Fix(web-react): Storybook argument for ScrollView edgeIndicators
  packages/web-react/src/components/ScrollView/stories/argTypes.ts
Labels: bug

#858 Feat(web-react): CheckboxField and RadioField reference element feature
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/CheckboxField/README.md
  packages/web-react/src/components/RadioField/README.md
  packages/web-react/src/components/RadioField/RadioField.tsx
  packages/web-react/src/types/checkboxField.ts
  packages/web-react/src/types/radioField.ts
  packages/web-react/src/types/shared/element.ts
  packages/web-react/src/types/textArea.ts
  packages/web-react/src/types/textField.ts
Labels: feature

#860 Feat(web-react): Link and Tag reference polymorph element feature
  packages/web-react/src/components/Link/Link.tsx
  packages/web-react/src/components/Link/README.md
  packages/web-react/src/components/Link/useLinkStyleProps.ts
  packages/web-react/src/components/Tag/README.md
  packages/web-react/src/components/Tag/Tag.tsx
  packages/web-react/src/types/link.ts
  packages/web-react/src/types/tag.ts
Labels: feature

#852 Feat(web): Let link in Alert inherit its color
  packages/web/src/scss/components/Alert/_Alert.scss
  packages/web/src/scss/components/Alert/_theme.scss
  packages/web/src/scss/components/Alert/index.html
  packages/web/src/scss/tools/_dictionaries.scss
Labels: feature

#866 Chore(web-react): Deploy storybook when stories in docs change
  netlify.toml
Labels: maintenance
