Repository lmc-eu/spirit-design-system, pull requests merged in 2023-09, with the labels that each got.

#1027 Docs(web-twig): Introduce `DocsSection` and `DocsBox` components
  apps/web-twig-demo/config/packages/spirit_web_twig.yaml
  apps/web-twig-demo/public/css/demo.css
  packages/web-twig/docs/components/DocsBox/DocsBox.twig
  packages/web-twig/docs/components/DocsBox/__tests__/DocsBoxSnapshotTest.php
  packages/web-twig/docs/components/DocsBox/__tests__/__fixtures__/docsBoxDefault.twig
  packages/web-twig/docs/components/DocsBox/__tests__/__snapshots__/docsBoxDefault.twig.snap.html
  packages/web-twig/docs/components/DocsSection/DocsSection.twig
  packages/web-twig/docs/components/DocsSection/__tests__/DocsSectionSnapshotTest.php
  packages/web-twig/docs/components/DocsSection/__tests__/__fixtures__/docsSectionDefault.twig
  packages/web-twig/docs/components/DocsSection/__tests__/__snapshots__/docsSectionDefault.twig.snap.html
  packages/web-twig/docs/twig-components/docsBox.twig
  packages/web-twig/docs/twig-components/docsSection.twig
  packages/web-twig/phpunit.xml.dist
  packages/web-twig/src/Resources/components/Pill/__tests__/PillSnapshotTest.php
  packages/web-twig/tests/Helper/TwigHelper.php
Labels: documentation

#1022 Docs(web-react): Add Checkbox demo #DS-889
  packages/web-react/src/components/Checkbox/demo/CheckboxDefault.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxDisabled.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxHelperText.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxHiddenLabel.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxIndeterminate.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxItem.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxRequired.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxValidation.tsx
  packages/web-react/src/components/Checkbox/demo/CheckboxValidationState.tsx
  packages/web-react/src/components/Checkbox/demo/index.tsx
Labels: documentation

#1030 Docs(web-react): Add Accordion demo #DS-890
  packages/web-react/src/components/Accordion/demo/AccordionBasic.tsx
  packages/web-react/src/components/Accordion/demo/AccordionOneItemOpenAtATime.tsx
  packages/web-react/src/components/Accordion/demo/AccordionStayOpen.tsx
  packages/web-react/src/components/Accordion/demo/AccordionUncontrolledStayOpen.tsx
  packages/web-react/src/components/Accordion/demo/index.tsx
Labels: documentation

#1039 Fix(web): FileUploader drag and drop fix #DS-938
  packages/web/src/js/FileUploader.ts
Labels: bug

#1038 Fix(web-react): Handle event capturing correctly in Dialog
  packages/web-react/src/components/Dialog/Dialog.tsx
  packages/web-react/src/components/Modal/ModalHeader.tsx
  packages/web-react/src/components/Modal/demo/ModalStacked.tsx
  packages/web-react/src/hooks/__tests__/useClickOutside.test.ts
  packages/web-react/src/hooks/useClickOutside.ts
Labels: bug

#1025 Docs(web-twig, web-react): Improve `Modal` documentation regarding `ScrollView` and optional title
  packages/web-react/docs/stories/examples/ModalWithScrollView.stories.tsx
  packages/web-react/src/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
Labels: documentation

#1044 Test(web-react): Ignore module pattern for `dist` directory
  packages/web-react/config/jest/config.js
Labels: maintenance

#1056 Docs(web, web-react, web-twig): Unify `Modal` READMEs
  packages/web-react/src/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web/src/scss/components/Modal/README.md
Labels: documentation

#1073 Chore(web-twig): Ignore tests and stories from exported package
  packages/web-twig/.gitattributes
Labels: maintenance

#1053 Docs(web-react, web): Add Heading demo #DS-899
  packages/web-react/src/components/Heading/demo/HeadingDefault.tsx
  packages/web-react/src/components/Heading/demo/HeadingLinks.tsx
  packages/web-react/src/components/Heading/demo/HeadingSizes.tsx
  packages/web-react/src/components/Heading/demo/index.tsx
Labels: documentation

#1042 Fix(web,web-twig): Fix `Button` flickering during spinner animation in Firefox
  packages/web-twig/src/Resources/components/Button/Button.twig
  packages/web-twig/src/Resources/components/Button/__tests__/__snapshots__/buttonLoadingDefault.twig.snap.html
  packages/web/src/scss/components/Button/_Button.scss
Labels: bug

#1074 Fix some code styl problem on Button components
  packages/web-react/src/components/Button/Button.tsx
  packages/web-react/src/components/Button/ButtonLink.tsx
Labels: bug

#1041 Fix(web): Prevent from removing spacing from Stack first child element
  packages/web/src/scss/components/Stack/_Stack.scss
Labels: bug

#1058 Refactor(web-react): Introduce `ModalCloseButton` component
  packages/web-react/src/components/Modal/ModalCloseButton.tsx
  packages/web-react/src/components/Modal/ModalHeader.tsx
  packages/web-react/src/components/Modal/__tests__/ModalCloseButton.test.tsx
  packages/web-react/src/components/Modal/index.ts
  packages/web-react/src/types/modal.ts
Labels: refactoring
