Repository lmc-eu/spirit-design-system, pull requests merged in 2023-11, with the labels that each got.

#1131 Docs(web-react): Corrected the example for Dropdown #DS-601
  packages/web-react/src/components/Dropdown/README.md
Labels: bug, documentation

#1133 Fix(web-react): FileUploader hidden input were not added without meta
  packages/web-react/src/components/FileUploader/useFileUploaderAttachment.ts
Labels: bug

#1121 Feat(web): Add breakpoint tokens to root CSS variables
  packages/web/src/scss/foundation/_tokens.scss
  packages/web/src/scss/foundation/index.scss
Labels: feature

#1128 Fix(web-react): Icon component supports SSR
  packages/web-react/package.json
  packages/web-react/src/components/Icon/Icon.tsx
  packages/web-react/src/components/Icon/README.md
  packages/web-react/src/utils/htmlParser.ts
  yarn.lock
Labels: bug

#1126 Docs(web, web-twig, web-react): Document ModalHeader and ModalFooter …
  packages/web-react/src/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web/src/scss/components/Modal/README.md
Labels: documentation

#1135 Chore(ci): Introduce Supernova documentation publishing
  .github/workflows/supernova.yaml
Labels: maintenance

#1138 Chore(ci): Remove condition for refs/tags on Supernova workflow
  .github/workflows/supernova.yaml
Labels: maintenance

#1134 Feat(icons): Do not remove colors from icons with `-colored` suffix #DS-990
  packages/icons/README.md
  packages/icons/scripts/buildSvg.js
Labels: feature

#1149 Chore(ci): Disable component analysis on every push to main
  .github/workflows/component-analysis.yaml
Labels: maintenance

#1153 Chore(repo): Update lockfile
  yarn.lock
Labels: maintenance

#1154 Chore(repo): Remove lerna option for disabling verification
  Makefile
Labels: maintenance

#1158 Fix(design-tokens): Use `sass` condition in `exports` field
  packages/design-tokens/package.json
Labels: bug

#1159 Fix(web-react): Check `htmlParser` for function type
  packages/web-react/src/components/Icon/Icon.tsx
Labels: bug

#1152 Fix(web-react): Accordion DOM errors #DS-948
  packages/web-react/src/components/Accordion/demo/AccordionBasic.tsx
  packages/web-react/src/components/Accordion/demo/AccordionOneItemOpenAtATime.tsx
Labels: bug

#1156 Docs(web-react): Fix typo in README.md of Icon component
  packages/web-react/src/components/Icon/README.md
Labels: documentation

#1140 Fix(web-react): Add useScrollControl hook and block scrolling when Dialog open #DS-1052
  packages/web-react/src/components/Dialog/useDialog.ts
  packages/web-react/src/hooks/__tests__/useScrollControl.test.ts
  packages/web-react/src/hooks/index.ts
  packages/web-react/src/hooks/useScrollControl.ts
Labels: bug

#1162 Fix(web): Refactor `Accordion` styles to fully support theming via design tokens #DS-1074
  packages/web/src/scss/components/Accordion/_Accordion.scss
Labels: bug

#1161 Fix(design-tokens): Exports field blocks build on product applications
  packages/design-tokens/package.json
Labels: maintenance

#1163 Feat(web-react): Introduce Item component #DS-1049
  .storybook/assets/stylesheets/index.scss
  packages/web-react/config/vite/app.ts
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Item/Item.tsx
  packages/web-react/src/components/Item/README.md
  packages/web-react/src/components/Item/__tests__/Item.test.tsx
  packages/web-react/src/components/Item/__tests__/useItemStyleProps.ts
  packages/web-react/src/components/Item/demo/CheckboxItem.tsx
  packages/web-react/src/components/Item/demo/ItemDefault.tsx
  packages/web-react/src/components/Item/demo/ItemDisabled.tsx
  packages/web-react/src/components/Item/demo/ItemHelperText.tsx
  packages/web-react/src/components/Item/demo/ItemIcon.tsx
  packages/web-react/src/components/Item/demo/ItemSelected.tsx
  packages/web-react/src/components/Item/demo/RadioItem.tsx
  packages/web-react/src/components/Item/demo/index.tsx
  packages/web-react/src/components/Item/index.html
  packages/web-react/src/components/Item/index.ts
  packages/web-react/src/components/Item/stories/Item.stories.tsx
  packages/web-react/src/components/Item/useItemStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/item.ts
Labels: feature

#1171 Chore(ci): Disable Nx cloud cache for CI runs
  nx.json
  package.json
  yarn.lock
Labels: maintenance
