Repository lmc-eu/spirit-design-system, pull requests merged in 2023-10, with the labels that each got.

#1076 Fix(exporter-scss): Fix exporter to make it work again after Supernov…
  exporters/scss/exporter.json
  exporters/scss/generated/functions.js
  exporters/scss/src/js/constants/weight.ts
  exporters/scss/src/js/generators/__fixtures__/typographyTokens.json
  exporters/scss/src/js/generators/__tests__/__snapshots__/typography.test.ts.snap
  exporters/scss/src/js/generators/__tests__/typography.test.ts
  exporters/scss/src/js/generators/simple.ts
  exporters/scss/src/js/generators/typography.ts
  exporters/scss/src/js/normalizers/__tests__/names.test.js
  exporters/scss/src/js/normalizers/__tests__/weight.test.js
  exporters/scss/src/js/normalizers/names.ts
  exporters/scss/src/js/normalizers/weight.ts
  exporters/scss/src/js/sorters/localeSort.ts
  exporters/scss/src/measures.pr
  exporters/scss/src/radii.pr
Labels: bug

#1095 Style(web-react): Ignore `build` directory from linting
  packages/web-react/.eslintignore
Labels: maintenance

#1096 Docs(web): Add CDN links for quick usage of the `spirit-web` package
  packages/web/README.md
Labels: documentation

#717 Chore(repo): Enable distributed caching of builds using Nx Cloud
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  .gitignore
  CONTRIBUTING.md
  nx.json
  package.json
  yarn.lock
Labels: maintenance

#1092 Feat(web): Introduce Placement dictionary and use it in `Dropdown` and `Tooltip` #DS-923
  docs/DICTIONARIES.md
  packages/web/src/scss/components/Dropdown/README.md
  packages/web/src/scss/components/Dropdown/_Dropdown.scss
  packages/web/src/scss/components/Dropdown/_DropdownWrapper.scss
  packages/web/src/scss/components/Dropdown/_theme.scss
  packages/web/src/scss/components/Dropdown/index.html
  packages/web/src/scss/components/Tooltip/README.md
  packages/web/src/scss/components/Tooltip/_Tooltip.scss
  packages/web/src/scss/components/Tooltip/_TooltipWrapper.scss
  packages/web/src/scss/components/Tooltip/_theme.scss
  packages/web/src/scss/components/Tooltip/_tools.scss
  packages/web/src/scss/components/Tooltip/index.html
  packages/web/src/scss/settings/_dictionaries.scss
  packages/web/src/scss/tools/_dictionaries.scss
  packages/web/src/scss/tools/_list.scss
  packages/web/src/scss/tools/_placement.scss
  packages/web/src/scss/tools/_string.scss
Labels: feature

#1093 Feat(web-twig): Use the new Placement dictionary in `Dropdown` and `Tooltip` #DS-923
  packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig
  packages/web-twig/src/Resources/components/Dropdown/README.md
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__fixtures__/dropdown.twig
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__fixtures__/dropdownDefault.twig
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__fixtures__/dropdownFull.twig
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__fixtures__/dropdownWrapper.twig
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__fixtures__/dropdownWrapperDefault.twig
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__snapshots__/dropdown.twig.snap.html
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__snapshots__/dropdownDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__snapshots__/dropdownFull.twig.snap.html
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__snapshots__/dropdownWrapper.twig.snap.html
  packages/web-twig/src/Resources/components/Tooltip/README.md
  packages/web-twig/src/Resources/components/Tooltip/Tooltip.stories.twig
  packages/web-twig/src/Resources/components/Tooltip/Tooltip.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__fixtures__/tooltip.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__fixtures__/tooltipDefault.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__fixtures__/tooltipDefaultPure.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__fixtures__/tooltipWrapper.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltip.twig.snap.html
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltipDefaultPure.twig.snap.html
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltipWrapper.twig.snap.html
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipOnHover.twig
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipPlacements.twig
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipStatic.twig
Labels: feature

#1099 Fix(web-twig): Fix pass custom classnames to the `Spinner` component
  packages/web-twig/src/Resources/components/Spinner/Spinner.twig
  packages/web-twig/src/Resources/components/Spinner/__tests__/__snapshots__/spinnerDefault.twig.snap.html
Labels: bug

#1112 Chore: Add @nrwl/cli to fix running tasks on local environment
  package.json
  yarn.lock
Labels: maintenance

#1114 Chore(ci): Skip Nx cache on Netlify builds
  netlify.toml
  packages/web-react/netlify.toml
Labels: maintenance

#1106 Fix(web-react): Removing unused prop #DS-933
  packages/web-react/src/components/FileUploader/FileUploader.tsx
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/types/fileUploader.ts
Labels: bug

#1113 Fix(web-react): ClickOutside working with Dialog and Dropdown #DS-945
  packages/web-react/src/components/Dialog/Dialog.tsx
  packages/web-react/src/hooks/useClickOutside.ts
Labels: bug

#1116 Revert "Deps: Update monorepo:storybook to v7.5.1"
  package.json
  yarn.lock
Labels: maintenance

#1103 Feat(web-react): Uncontrolled Pagination component
  packages/web-react/src/components/Pagination/README.md
  packages/web-react/src/components/Pagination/UncontrolledPagination.tsx
  packages/web-react/src/components/Pagination/__tests__/UncontrolledPagination.test.tsx
  packages/web-react/src/components/Pagination/index.ts
  packages/web-react/src/components/Pagination/stories/UncontrolledPagination.stories.tsx
  packages/web-react/src/components/Pagination/usePagination.tsx
  packages/web-react/src/types/pagination.ts
Labels: feature

#1119 Fix(exporter-scss): Allow negative numbers in unit printer
  exporters/scss/exporter.json
  exporters/scss/generated/functions.js
  exporters/scss/src/js/printers/__tests__/unit.test.ts
  exporters/scss/src/js/printers/unit.ts
Labels: bug
