Repository lmc-eu/spirit-design-system, pull requests merged in 2023-07, with the labels that each got.

#914 BREAKING CHANGE(web-twig): Remove `onClick` prop #DS-686
  packages/web-twig/src/Resources/components/Button/Button.twig
  packages/web-twig/src/Resources/components/Button/README.md
  packages/web-twig/src/Resources/components/Button/stories/ButtonColorsSizes.twig
  packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.twig
  packages/web-twig/src/Resources/components/ButtonLink/README.md
  packages/web-twig/src/Resources/components/Header/README.md
  packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig
  packages/web-twig/src/Resources/components/Link/Link.twig
  packages/web-twig/src/Resources/components/Link/README.md
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set buttonWithMainProps.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set headerDialogLink.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set headerLink.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set linkDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/buttonWithMainProps.twig
  packages/web-twig/tests/components-fixtures/headerDialogLink.twig
  packages/web-twig/tests/components-fixtures/headerLink.twig
  packages/web-twig/tests/components-fixtures/linkDefault.twig
Labels: BC

#929 Chore(repo): Remove Tomas Sychra and add Pavel Klibani to codeowners
  .github/CODEOWNERS
Labels: feature

#915 BREAKING CHANGE(web-react): Remove Header deprecations #DS-651
  packages/web-react/src/components/Header/Header.stories.ts
  packages/web-react/src/components/Header/README.md
  packages/web-react/src/components/Header/deprecated/Header.stories.ts
  packages/web-react/src/components/Header/deprecated/Header.tsx
  packages/web-react/src/components/Header/deprecated/HeaderActions.tsx
  packages/web-react/src/components/Header/deprecated/HeaderBackdrop.tsx
  packages/web-react/src/components/Header/deprecated/HeaderContext.tsx
  packages/web-react/src/components/Header/deprecated/Nav.tsx
  packages/web-react/src/components/Header/deprecated/NavItem.tsx
  packages/web-react/src/components/Header/deprecated/NavLink.tsx
  packages/web-react/src/components/Header/deprecated/Navbar.tsx
  packages/web-react/src/components/Header/deprecated/NavbarClose.tsx
  packages/web-react/src/components/Header/deprecated/NavbarToggler.tsx
  packages/web-react/src/components/Header/deprecated/README.md
  packages/web-react/src/components/Header/deprecated/__tests__/Header.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/HeaderActions.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/Nav.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/NavItem.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/NavLink.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/Navbar.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/NavbarClose.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/NavbarToggler.test.tsx
  packages/web-react/src/components/Header/deprecated/__tests__/useHeaderStyleProps.test.ts
  packages/web-react/src/components/Header/deprecated/stories/Header.tsx
  packages/web-react/src/components/Header/deprecated/stories/HeaderActions.tsx
  packages/web-react/src/components/Header/deprecated/stories/HeaderActionsProps.tsx
  packages/web-react/src/components/Header/deprecated/stories/HeaderHtml.tsx
  packages/web-react/src/components/Header/deprecated/stories/HeaderInverted.tsx
  packages/web-react/src/components/Header/deprecated/stories/HeaderProps.tsx
  packages/web-react/src/components/Header/deprecated/stories/HeaderSimpleInverted.tsx
  packages/web-react/src/components/Header/deprecated/stories/NavItemProps.tsx
  packages/web-react/src/components/Header/deprecated/stories/NavLinkProps.tsx
  packages/web-react/src/components/Header/deprecated/stories/NavProps.tsx
  packages/web-react/src/components/Header/deprecated/stories/NavbarProps.tsx
  packages/web-react/src/components/Header/deprecated/stories/SpiritLogo.tsx
  packages/web-react/src/components/Header/deprecated/useHeader.ts
  packages/web-react/src/components/Header/deprecated/useHeaderStyleProps.ts
  packages/web-react/src/components/Header/index.ts
  packages/web-react/tests/testUtils/renderWithHeaderContext.tsx
  packages/web-react/tests/testUtils/withHeaderContext.tsx
Labels: BC

#932 BREAKING CHANGE(web): Add underline to hover and active states to def…
  packages/web/src/scss/foundation/_links.scss
  packages/web/src/scss/helpers/links/index.html
Labels: BC

#936 BREAKING CHANGE(web-twig): Remove old Modal and rename ModalComposed …
  packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/src/Resources/components/Modal/ModalComposed.twig
  packages/web-twig/src/Resources/components/Modal/ModalFooter.twig
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/stories/ModalBasic.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalSimple.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalStacking.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalVerticalBodyPadding.twig
  packages/web-twig/src/Resources/twig-components/modalComposed.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalComposedDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
  packages/web-twig/tests/components-fixtures/modalComposedDefault.twig
  packages/web-twig/tests/components-fixtures/modalDefault.twig
Labels: BC

#934 BREAKING CHANGE(web-twig): Remove Twig `boolprop` filter and its extension
  packages/web-twig/src/Resources/config/services.yml
  packages/web-twig/src/Twig/BoolpropExtension.php
  packages/web-twig/tests/Helper/TwigHelper.php
  packages/web-twig/tests/Twig/BoolpropExtensionTest.php
Labels: BC

#924 Chore(web-twig): Remove old unused component snapshots
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set buttonDisabledDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set buttonWithDisabledFalseDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set buttonWithDisabledFalsePropDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set checkboxFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set checkboxFieldDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set containerDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set containerDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set gridDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set gridDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set gridLayoutDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set gridLayoutWithResetPropDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set headerDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set headerFull.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set headerSimpleInverted.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set passwordFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set stackDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set stackDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set textFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set textFieldDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__testShouldSnapshotComponents with data set textFieldWithInvisibleLabel.twig__1.html
Labels: maintenance

#941 Fix(web): Fix FileUploader Drag and Drop and duplicated validation messages
  packages/web/src/js/FileUploader.ts
  packages/web/src/js/__tests__/FileUploader.test.ts
Labels: bug

#944 Refactor(web-twig): Move FileUploader form demo script to Demo App
  apps/web-twig-demo/assets/app.ts
  packages/web-twig/src/Resources/components/FileUploader/stories/FileUploaderExampleOfJSControlledForm.twig
Labels: refactoring

#949 Chore(ci): Fix typo in PR template links to contributing documentation
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#948 Docs(repo): Introduce form validations package in main README file
  README.md
Labels: documentation

#955 Docs(web, web-react, web-twig): Minor typo fix
  packages/web-react/MIGRATION-v1.md
  packages/web-twig/MIGRATION-v2.md
  packages/web/MIGRATION-v1.md
Labels: documentation

#956 Fix(demo): Use builded icons for web-twig demo refs #DS-748
  apps/web-twig-demo/docker/docker-compose.override.yml
  packages/web-twig/Makefile
Labels: maintenance
