Repository lmc-eu/spirit-design-system, pull requests merged in 2023-04, with the labels that each got.

#745 Docs(web-twig): Introduce Button story
  packages/web-twig/src/Resources/components/Button/Button.stories.twig
  packages/web-twig/src/Resources/components/Button/stories/ButtonColorsSizes.twig
  packages/web-twig/src/Resources/components/Button/stories/ButtonDisabled.twig
Labels: documentation

#769 Docs(web-twig): Introduce Stack story refs #DS-247
  packages/web-twig/src/Resources/components/Stack/Stack.stories.twig
  packages/web-twig/src/Resources/components/Stack/stories/StackBlocks.twig
  packages/web-twig/src/Resources/components/Stack/stories/StackFormFields.twig
Labels: documentation

#749 Docs(web-twig): Introduce ButtonLink story refs #DS-247
  packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.stories.twig
  packages/web-twig/src/Resources/components/ButtonLink/stories/ButtonLinkColorsSizes.twig
  packages/web-twig/src/Resources/components/ButtonLink/stories/ButtonLinkDisabled.twig
Labels: documentation

#771 Docs(web-twig): Introduce Tag story refs #DS-247
  packages/web-twig/src/Resources/components/Tag/Tag.stories.twig
  packages/web-twig/src/Resources/components/Tag/stories/TagDefault.twig
Labels: documentation

#772 Docs(web-twig): Introduce Pill story refs #DS-247
  packages/web-twig/src/Resources/components/Pill/Pill.stories.twig
  packages/web-twig/src/Resources/components/Pill/stories/PillDefault.twig
Labels: documentation

#773 Docs(web-twig): Introduce Container story refs #DS-247
  packages/web-twig/src/Resources/components/Container/Container.stories.twig
  packages/web-twig/src/Resources/components/Container/stories/ContainerDefault.twig
Labels: documentation

#770 Docs(web-twig): Enable JS plugins in demo app
  apps/web-twig-demo/assets/app.js
  apps/web-twig-demo/package.json
  apps/web-twig-demo/templates/layout/base.html.twig
Labels: documentation

#777 Docs(web-twig): Introduce Collapse story refs #DS-247
  packages/web-twig/src/Resources/components/Collapse/Collapse.stories.twig
  packages/web-twig/src/Resources/components/Collapse/stories/CollapseDefaultWithButton.twig
  packages/web-twig/src/Resources/components/Collapse/stories/CollapseHelperClass.twig
  packages/web-twig/src/Resources/components/Collapse/stories/CollapseHideTrigger.twig
  packages/web-twig/src/Resources/components/Collapse/stories/CollapseMultipleTriggers.twig
  packages/web-twig/src/Resources/components/Collapse/stories/CollapseOpenOnInit.twig
  packages/web-twig/src/Resources/components/Collapse/stories/CollapseVisibilityBreakpoint.twig
Labels: documentation

#780 Docs(web-twig): Introduce Tabs story refs #DS-247
  packages/web-twig/src/Resources/components/Tabs/Tabs.stories.twig
  packages/web-twig/src/Resources/components/Tabs/stories/TabsDefault.twig
Labels: documentation

#763 Feat(web): Introduce `FileUploader` component #DS-664
  packages/web/src/scss/components/FileUploader/README.md
  packages/web/src/scss/components/FileUploader/_FileUploader.scss
  packages/web/src/scss/components/FileUploader/_FileUploaderAttachment.scss
  packages/web/src/scss/components/FileUploader/_FileUploaderInput.scss
  packages/web/src/scss/components/FileUploader/_FileUploaderList.scss
  packages/web/src/scss/components/FileUploader/_theme.scss
  packages/web/src/scss/components/FileUploader/index.html
  packages/web/src/scss/components/FileUploader/index.scss
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/foundation/_links.scss
  packages/web/src/scss/helpers/_links.scss
  packages/web/src/scss/settings/_links.scss
  packages/web/src/scss/tools/_form-fields.scss
Labels: feature

#788 Docs(web-twig): Stories path update
  apps/web-twig-demo/assets/styles/app.scss
  apps/web-twig-demo/webpack.config.js
Labels: documentation

#789 Docs(web-twig): Introduce Link story refs #DS-247
  packages/web-twig/src/Resources/components/Link/Link.stories.twig
  packages/web-twig/src/Resources/components/Link/README.md
  packages/web-twig/src/Resources/components/Link/stories/LinkColors.twig
  packages/web-twig/src/Resources/components/Link/stories/LinkDefault.twig
Labels: documentation

#790 Docs(web): Update recommended way to prefix CSS classes #DS-627
  packages/web/README.md
Labels: documentation

#787 Docs(web-twig): Introduce Text story refs #DS-247
  packages/web-twig/src/Resources/components/Text/Text.stories.twig
  packages/web-twig/src/Resources/components/Text/stories/TextDefault.twig
  packages/web-twig/src/Resources/components/Text/stories/TextEmphasis.twig
  packages/web-twig/src/Resources/components/Text/stories/TextSizes.twig
Labels: documentation

#786 Docs(web-twig): Introduce Heading story refs #DS-247
  packages/web-twig/src/Resources/components/Heading/Heading.stories.twig
  packages/web-twig/src/Resources/components/Heading/stories/HeadingDefault.twig
  packages/web-twig/src/Resources/components/Heading/stories/HeadingSizes.twig
Labels: documentation

#778 Docs(web-twig): Introduce Dropdown stories refs #DS-247
  packages/web-twig/src/Resources/components/Dropdown/Dropdown.stories.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownBasic.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownDisabledAutoclose.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidth.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthAll.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthMobile.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthMobileOnly.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownLongerContent.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownTopRight.twig
Labels: documentation

#791 Fix(web-twig): Condition for onClick deprecation
  packages/web-twig/src/Resources/components/Button/Button.twig
  packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.twig
  packages/web-twig/src/Resources/components/Header/_abstracts/Button.twig
  packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig
  packages/web-twig/src/Resources/components/Link/Link.twig
Labels: bug

#754 Feat(web): Extend Stack component #JALL-107
  packages/web/src/scss/components/Stack/README.md
  packages/web/src/scss/components/Stack/_Stack.scss
  packages/web/src/scss/components/Stack/_theme.scss
  packages/web/src/scss/components/Stack/index.html
Labels: feature

#776 Docs(web-twig): Introduction TextField stories
  packages/web-twig/src/Resources/components/TextField/TextField.stories.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextField.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextFieldFluid.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextFieldHelperText.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextFieldInline.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextFieldMessage.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextFieldPasswordToggle.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextFieldV1DisabledFeature.twig
  packages/web-twig/src/Resources/components/TextField/stories/TextFieldValidationState.twig
Labels: documentation

#781 Docs(web-twig): Introduction RadioField stories
  packages/web-twig/src/Resources/components/RadioField/RadioField.stories.twig
  packages/web-twig/src/Resources/components/RadioField/stories/RadioField.twig
  packages/web-twig/src/Resources/components/RadioField/stories/RadioFieldDisabled.twig
  packages/web-twig/src/Resources/components/RadioField/stories/RadioFieldHelperText.twig
  packages/web-twig/src/Resources/components/RadioField/stories/RadioFieldItem.twig
  packages/web-twig/src/Resources/components/RadioField/stories/RadioFieldValidationState.twig
Labels: documentation

#783 Docs(web-twig): Introduction CheckboxField stories
  packages/web-twig/src/Resources/components/CheckboxField/CheckboxField.stories.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxField.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldDisabled.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldHelperText.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldHiddenLabel.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldIndeterminate.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldItem.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldRequired.twig
  packages/web-twig/src/Resources/components/CheckboxField/stories/CheckboxFieldValidationState.twig
Labels: documentation

#810 Feat(web-twig): Allow style in inlineSvg and in Icon, deprecate class…
  packages/web-twig/src/Resources/components/Button/stories/ButtonColorsSizes.twig
  packages/web-twig/src/Resources/components/Button/stories/ButtonDisabled.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownBasic.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownDisabledAutoclose.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidth.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthAll.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthMobile.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthMobileOnly.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownLongerContent.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownTopRight.twig
  packages/web-twig/src/Resources/components/Icon/Icon.twig
  packages/web-twig/src/Resources/components/Icon/README.md
  packages/web-twig/src/Resources/components/Spinner/README.md
  packages/web-twig/src/Resources/components/Spinner/Spinner.twig
  packages/web-twig/src/Twig/SvgExtension.php
  packages/web-twig/tests/Twig/SvgExtensionTest.php
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set accordionDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set accordionStayOpen.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set alertDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set breadcrumbsDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set buttonLinkLoadingDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set buttonLoadingDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set headerDialogCloseButton.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set headerMobileActions.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set headerWithDialog.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set iconDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalComposedDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set spinnerDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldPasswordToggle.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tooltipDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set tooltipDefaultPure.twig__1.html
  packages/web-twig/tests/components-fixtures/spinnerDefault.twig
  packages/web-twig/tests/fixtures/test_with_style.svg
Labels: feature

#814 Chore(ci): Ignore demo package from CI builds
  package.json
Labels: maintenance

#815 Chore(ci): Fix typo in build directory
  .eslintignore
  examples/web-react/.gitignore
  examples/web-react/index.html
  examples/web-react/package.json
  examples/web-react/webpack.config.js
  yarn.lock
Labels: maintenance

#797 Feat(web): Introduction of JS for FileUploader component #DS-682
  packages/web/src/js/FileUploader.ts
  packages/web/src/js/__tests__/FileUploader.test.ts
  packages/web/src/js/index.esm.ts
  packages/web/src/js/index.umd.ts
  packages/web/src/scss/components/FileUploader/README.md
  packages/web/src/scss/components/FileUploader/index.html
Labels: feature
