Repository lmc-eu/spirit-design-system, pull requests merged in 2023-08, with the labels that each got.

#960 Chore(ci): Revert back npm-install action to v1
  .github/workflows/build.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/component-analysis.yaml
  .github/workflows/deploy.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: maintenance

#968 Chore(ci): Build icons before testing web-twig package
  .github/workflows/test-web-twig.yaml
Labels: maintenance

#964 Fix(web): Fix ModalDialog unset box-sizing #DS-878
  packages/web/src/scss/components/Modal/_ModalDialog.scss
Labels: bug

#947 Chore(repo): Automatically create GitHub release when creating version
  lerna.json
Labels: maintenance

#965 Fix(web): Use gap in Stack with spacing and without dividers #DS-880
  packages/web/src/scss/components/Stack/README.md
  packages/web/src/scss/components/Stack/_Stack.scss
  packages/web/src/scss/components/Stack/_theme.scss
Labels: bug

#972 Feat(web): FileUploader Image attachment preview #DS-850
  packages/web/src/js/FileUploader.ts
  packages/web/src/js/__tests__/FileUploader.test.ts
  packages/web/src/js/utils/Image2Base64Preview.ts
  packages/web/src/js/utils/index.ts
  packages/web/src/scss/components/FileUploader/README.md
  packages/web/src/scss/components/FileUploader/index.html
Labels: feature

#962 Fix(web-twig): Fix condition to render `aria-labelledby` attribute in the Modal component
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set modalDefault.twig__1.html
Labels: bug, feature

#989 Docs(web-react): FileUploader Storybook composition demo
  packages/web-react/docs/stories/examples/FileUploaderWithImagePreview.stories.tsx
Labels: documentation

#979 Feat(web-twig): Enable pass `formtarget` attribute to the `Button`
  packages/web-twig/src/Resources/components/Button/Button.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set buttonWithMainProps.twig__1.html
  packages/web-twig/tests/components-fixtures/buttonWithMainProps.twig
Labels: feature

#986 Fix(web): Prevent underline in ButtonLink on active state
  packages/web/src/scss/components/Button/_Button.scss
Labels: bug

#994 Fix(web): Remove unused data attribute in Accordion #DS-883
  packages/web-twig/src/Resources/components/Accordion/Accordion.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set accordionDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set accordionStayOpen.twig__1.html
  packages/web/src/js/__tests__/Collapse.test.ts
  packages/web/src/scss/components/Accordion/README.md
  packages/web/src/scss/components/Accordion/index.html
Labels: bug

#995 Fix(web): Set correct order of hover, focus and active states in CSS
  packages/web/src/scss/components/Button/_Button.scss
  packages/web/src/scss/components/Pagination/_Pagination.scss
  packages/web/src/scss/foundation/_links.scss
  packages/web/src/scss/helpers/links/_links.scss
Labels: bug

#988 Feat(web-react): Introduce FieldGroup component #DS-856
  .storybook/assets/stylesheets/index.scss
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/FieldGroup/FieldGroup.stories.ts
  packages/web-react/src/components/FieldGroup/FieldGroup.tsx
  packages/web-react/src/components/FieldGroup/README.md
  packages/web-react/src/components/FieldGroup/__tests__/FieldGroup.test.tsx
  packages/web-react/src/components/FieldGroup/__tests__/useFieldGroupStyleProps.test.tsx
  packages/web-react/src/components/FieldGroup/demo/index.tsx
  packages/web-react/src/components/FieldGroup/index.html
  packages/web-react/src/components/FieldGroup/index.ts
  packages/web-react/src/components/FieldGroup/stories/FieldGroup.tsx
  packages/web-react/src/components/FieldGroup/stories/argTypes.ts
  packages/web-react/src/components/FieldGroup/useFieldGroupStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/fieldGroup.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/shared/element.ts
Labels: feature

#996 Docs(web-react): Rename components in example compositions
  packages/web-react/docs/stories/examples/LoginForm.stories.tsx
  packages/web-react/docs/stories/examples/ModalStacked.stories.tsx
Labels: documentation

#997 Chore(web-react): Migrate Storybook to Vite builder
  .storybook/decorators/IconGlobalDecorator.jsx
  .storybook/main.js
  package.json
  yarn.lock
Labels: maintenance

#992 Default `icon` according to `color` variant in the `Alert`
  packages/web-react/src/components/Alert/README.md
  packages/web-twig/src/Resources/components/Alert/README.md
Labels: documentation

#999 Chore(web-react): Migration to Storybook v7 refs #DS-872
  .eslintrc.js
  .storybook/main.ts
  package.json
  yarn.lock
Labels: maintenance

#1004 Fix(web): Drop support of Windows high contrast mode in `Radio` to fix antialiasing issues
  packages/web/src/scss/components/Radio/_Radio.scss
Labels: bug

#1006 Docs(web-twig): Introduce showcase app localhost url
  packages/web-twig/CONTRIBUTING.md
Labels: documentation

#1005 Docs(web-twig): Introduce section about snapshot tests
  packages/web-twig/CONTRIBUTING.md
Labels: documentation

#991 Fix(web-twig): Deprecate `class` prop in the `Header` abstract components
  packages/web-twig/src/Resources/components/Header/_abstracts/Button.twig
  packages/web-twig/src/Resources/components/Header/_abstracts/Element.twig
  packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig
Labels: bug

#1011 Fix(web-react): The rest props were transfered twice on FieldGroup
  packages/web-react/src/components/FieldGroup/FieldGroup.tsx
Labels: bug
