Repository lmc-eu/spirit-design-system, pull requests merged in 2023-03, with the labels that each got.

#709 Validation state dictionary update
  docs/DICTIONARIES.md
  packages/web-react/src/components/CheckboxField/CheckboxField.stories.ts
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/CheckboxField/README.md
  packages/web-react/src/components/CheckboxField/__tests__/CheckboxField.test.tsx
  packages/web-react/src/components/CheckboxField/__tests__/useCheckboxFieldStyleProps.test.ts
  packages/web-react/src/components/CheckboxField/stories/CheckboxFieldHelperText.tsx
  packages/web-react/src/components/CheckboxField/stories/CheckboxFieldValidationState.tsx
  packages/web-react/src/components/CheckboxField/useCheckboxFieldStyleProps.ts
  packages/web-react/src/components/RadioField/README.md
  packages/web-react/src/components/RadioField/RadioField.stories.ts
  packages/web-react/src/components/RadioField/RadioField.tsx
  packages/web-react/src/components/RadioField/__tests__/RadioField.test.tsx
  packages/web-react/src/components/RadioField/__tests__/useRadioFieldStyleProps.test.ts
  packages/web-react/src/components/RadioField/stories/RadioFieldHelperText.tsx
  packages/web-react/src/components/RadioField/stories/RadioFieldValidationState.tsx
  packages/web-react/src/components/RadioField/useRadioFieldStyleProps.ts
  packages/web-react/src/components/TextArea/README.md
  packages/web-react/src/components/TextArea/__tests__/TextArea.test.tsx
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
  packages/web-react/src/components/TextFieldBase/README.md
  packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
  packages/web-react/src/hooks/useDeprecatedMessage.ts
  packages/web-react/src/types/checkboxField.ts
  packages/web-react/src/types/radioField.ts
  packages/web-react/src/types/shared/dictionaries.ts
  packages/web-react/src/types/shared/inputs.ts
  packages/web-react/tests/providerTests/dictionaryPropsTest.tsx
  packages/web-twig/src/Resources/components/CheckboxField/CheckboxField.twig
  packages/web-twig/src/Resources/components/CheckboxField/README.md
  packages/web-twig/src/Resources/components/RadioField/README.md
  packages/web-twig/src/Resources/components/RadioField/RadioField.twig
  packages/web-twig/src/Resources/components/TextArea/README.md
  packages/web-twig/src/Resources/components/TextField/README.md
  packages/web-twig/src/Resources/components/TextFieldBase/README.md
  packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set radioFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set radioFieldDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set radioFieldItem.twig__1.html
  packages/web/src/scss/components/CheckboxField/README.md
  packages/web/src/scss/components/CheckboxField/_CheckboxField.scss
  packages/web/src/scss/components/CheckboxField/index.html
  packages/web/src/scss/components/RadioField/README.md
  packages/web/src/scss/components/RadioField/_RadioField.scss
  packages/web/src/scss/components/RadioField/_theme.scss
  packages/web/src/scss/components/RadioField/index.html
  packages/web/src/scss/components/TextArea/README.md
  packages/web/src/scss/components/TextArea/_TextArea.scss
  packages/web/src/scss/components/TextArea/index.html
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/index.html
  packages/web/src/scss/theme/_form-fields.scss
  packages/web/src/scss/tools/_form-fields.scss
Labels: feature

#715 Docs(web-react): Remove link to detailed information about Icons
  packages/web-react/src/components/Icon/README.md
Labels: documentation

#716 Chore(web-react): Remove license file from builded package
  packages/web-react/config/webpack.js
  packages/web-react/package.json
  yarn.lock
Labels: maintenance

#719 Fix(web-twig): Fix bugs in Validation state error deprecation
  packages/web-twig/src/Resources/components/CheckboxField/CheckboxField.twig
  packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set checkboxFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set checkboxFieldDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set checkboxFieldItem.twig__1.html
  packages/web-twig/tests/components-fixtures/checkboxFieldDefault.twig
  packages/web-twig/tests/components-fixtures/checkboxFieldDefaultPure.twig
  packages/web-twig/tests/components-fixtures/checkboxFieldItem.twig
Labels: bug

#714 Feat(exporter-scss): Return 400 font weight for Ebony Semibold to mat…
  exporters/scss/README.md
  exporters/scss/exporter.json
  exporters/scss/generated/functions.js
  exporters/scss/src/js/constants/weight.ts
  exporters/scss/src/js/generators/__fixtures__/typographyTokens.json
  exporters/scss/src/js/generators/__tests__/__snapshots__/typography.test.ts.snap
  exporters/scss/src/js/generators/__tests__/typography.test.ts
  exporters/scss/src/js/generators/typography.ts
  exporters/scss/src/js/normalizers/__tests__/weight.test.js
  exporters/scss/src/js/normalizers/weight.ts
Labels: feature

#725 Fix(web): Fix link Button color on hover, focus and active
  packages/web/src/scss/components/Button/_theme.scss
  packages/web/src/scss/components/Button/index.html
Labels: bug

#728 Docs(web-react): Remove `jsx static` example format from ModalComposed
  packages/web-react/src/components/ModalComposed/README.md
Labels: documentation

#726 Feat(web-react): ForwardRef for Button and ButtonLink #DS-445
  packages/web-react/src/components/Button/Button.stories.ts
  packages/web-react/src/components/Button/Button.tsx
  packages/web-react/src/components/Button/ButtonLink.stories.tsx
  packages/web-react/src/components/Button/ButtonLink.tsx
  packages/web-react/src/components/Button/README.md
  packages/web-react/src/components/Button/stories/argTypes.ts
  packages/web-react/src/types/button.ts
Labels: feature

#727 Feat(web-react): Button component in docs #DS-598
  packages/web-react/src/components/Dropdown/stories/Dropdown.tsx
  packages/web-react/src/components/Tooltip/README.md
  packages/web-react/src/components/Tooltip/stories/Tooltip.tsx
  packages/web-react/src/components/Tooltip/stories/TooltipClickable.tsx
  packages/web-react/src/components/Tooltip/stories/TooltipDismissible.tsx
  packages/web-react/src/components/Tooltip/stories/TooltipDismissibleFloatingUi.tsx
  packages/web-react/src/components/Tooltip/stories/TooltipDismissibleUncontrolled.tsx
  packages/web-react/src/components/Tooltip/stories/TooltipFloatingUi.tsx
  packages/web-react/src/components/Tooltip/stories/TooltipUncontrolled.tsx
Labels: feature

#732 Fix(web): RadioField label in disabled state
  packages/web/src/scss/components/RadioField/_RadioField.scss
Labels: bug

#734 Fix(web): Remove Tabs trigger focus causing weird scroll placement #D…
  packages/web/src/js/Tabs.ts
Labels: bug

#720 Extension of React components props
  packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
  packages/web-react/src/types/checkboxField.ts
  packages/web-react/src/types/radioField.ts
  packages/web-react/src/types/shared/element.ts
  packages/web-react/src/types/shared/index.ts
  packages/web-react/src/types/shared/inputs.ts
  packages/web-react/src/types/shared/style.ts
  packages/web-react/src/types/textArea.ts
  packages/web-react/src/types/textField.ts
  packages/web-react/src/types/textFieldBase.ts
Labels: feature

#735 Feat(web): Add feature class to enable v1 disabled state style in Tex…
  packages/web/src/scss/components/TextArea/README.md
  packages/web/src/scss/components/TextArea/_TextArea.scss
  packages/web/src/scss/components/TextArea/index.html
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/index.html
  packages/web/src/scss/theme/_form-fields.scss
  packages/web/src/scss/tools/_form-fields.scss
Labels: feature

#739 omlet.dev analyze job
  .github/workflows/component-analysis.yaml
  package.json
  yarn.lock
Labels: maintenance

#753 Chore(ci): Disable shallow clone for Omlet analysis and upgrade actions
  .github/workflows/component-analysis.yaml
Labels: maintenance

#607 Feat(web): Add feature class to make links correctly underlined #DS-516
  packages/web/assets/demo.css
  packages/web/src/scss/components/Header/_Header.deprecated.scss
  packages/web/src/scss/components/Header/_tools.scss
  packages/web/src/scss/components/Pagination/_Pagination.scss
  packages/web/src/scss/components/Tabs/_Tabs.scss
  packages/web/src/scss/components/TextArea/index.html
  packages/web/src/scss/components/TextField/index.html
  packages/web/src/scss/foundation/_links.scss
  packages/web/src/scss/helpers/_links.scss
  packages/web/src/scss/helpers/index.html
Labels: feature

#761 Feat(icons): Add new icons manually because Supernova Figma import is…
  packages/icons/src/svg/download.svg
  packages/icons/src/svg/file.svg
  packages/icons/src/svg/spinner.svg
  packages/icons/src/svg/upload.svg
Labels: feature

#746 Feat(web-react): Extension and modification of Button and ButtonLink
  packages/web-react/src/components/Button/Button.stories.ts
  packages/web-react/src/components/Button/Button.tsx
  packages/web-react/src/components/Button/ButtonLink.tsx
  packages/web-react/src/components/Button/README.md
  packages/web-react/src/components/Button/stories/Button.tsx
  packages/web-react/src/components/Button/stories/ButtonLink.tsx
  packages/web-react/src/components/Button/stories/ButtonLinkHtml.tsx
  packages/web-react/src/components/Button/stories/ButtonLinkProps.tsx
  packages/web-react/src/components/Button/stories/ButtonProps.tsx
  packages/web-react/src/components/Button/stories/argTypes.ts
  packages/web-react/src/components/Button/useButtonAriaProps.ts
  packages/web-react/src/components/Button/useButtonStyleProps.ts
  packages/web-react/src/types/button.ts
  packages/web-react/src/types/shared/element.ts
Labels: feature

#764 Fix(icons): Add missing path to Upload icon
  packages/icons/src/svg/upload.svg
Labels: bug

#767 Chore(ci): Increase timeout for commitlint job
  .github/workflows/commitlint.yaml
Labels: maintenance
