Repository lmc-eu/spirit-design-system, pull requests merged in 2023-01, with the labels that each got.

#616 Fix(web-react): Make CheckboxField implementation same as in other pa…
  packages/web-react/src/components/CheckboxField/CheckboxField.tsx
  packages/web-react/src/components/CheckboxField/__tests__/CheckboxField.test.tsx
  packages/web-react/src/components/RadioField/__tests__/RadioField.test.tsx
  packages/web-react/tests/providerTests/itemPropsTest.tsx
Labels: bug

#619 Fix(web-twig): Make Collapse components props optional according to its readme
  packages/web-twig/src/Resources/components/Collapse/Collapse.twig
  packages/web-twig/src/Resources/components/Collapse/README.md
Labels: bug

#617 Chore(web-react): Remove unused variables
  packages/web-react/docs/stories/examples/LoginForm.stories.tsx
  packages/web-react/src/components/Accordion/__tests__/Accordion.test.tsx
  packages/web-react/src/components/Accordion/__tests__/AccordionItem.test.tsx
Labels: maintenance

#622 Fix(web): Fix Accordion arrow stacking context #DS-527
  packages/web/src/scss/components/Accordion/_Accordion.scss
Labels: bug

#623 Docs(web-react): Fix Accordion and Modal code examples
  packages/web-react/src/components/Accordion/README.md
  packages/web-react/src/components/Modal/README.md
Labels: documentation

#609 Feat(web): Collapse toggle with variable content #DS-501
  packages/web/src/scss/components/Collapse/_Collapse.scss
  packages/web/src/scss/components/Collapse/index.html
  packages/web/src/scss/helpers/_accessibility.scss
  packages/web/src/scss/helpers/index.html
Labels: feature

#628 Fix(icons): Ignore sprite.svg while generating React icon components
  packages/icons/scripts/prepareSvgReact.js
Labels: bug

#632 Fix(icons): Ignore sprite.svg while generating constants #DS-548
  packages/icons/scripts/buildConstants.js
  packages/icons/scripts/buildSvg.js
  packages/icons/scripts/shared.js
Labels: bug

#626 Refactor(web-twig): Unify quotes in attributes and print them raw
  packages/web-twig/src/Resources/components/Collapse/Collapse.twig
  packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig
Labels: refactoring

#629 Docs(web): Fix misleading headline in the `Collapse` demo
  packages/web/src/scss/components/Collapse/index.html
Labels: documentation

#637 Feat(web-react): Export all types in main index too #DS-532
  packages/web-react/src/index.ts
  packages/web-react/src/types/main.ts
Labels: feature

#604 Feat(web): Make `BaseComponent` available for building product design
  packages/web/src/js/dom/index.ts
  packages/web/src/js/index.esm.ts
  packages/web/src/js/index.umd.ts
  packages/web/src/js/utils/index.ts
Labels: feature

#633 Fix(web-react): Accordion and Collapse in Modal implementation
  packages/web-react/config/jest/config.js
  packages/web-react/docs/stories/examples/ModalWithAccordion.stories.tsx
  packages/web-react/docs/stories/examples/ModalWithCollapse.stories.tsx
  packages/web-react/package.json
  packages/web-react/src/components/Collapse/__tests__/useResizeHeight.test.ts
  packages/web-react/src/components/Collapse/__tests__/useResizeHeight.test.tsx
  packages/web-react/src/components/Collapse/useResizeHeight.ts
  yarn.lock
Labels: bug

#642 Docs(web-react): Introduce Bundlephobia badges about size and deps
  packages/web-react/README.md
Labels: documentation

#638 Feat(web-twig): Add `hasPasswordToggle` feature to the TextField #DS-509
  packages/web-twig/src/Resources/components/TextField/README.md
  packages/web-twig/src/Resources/components/TextFieldBase/README.md
  packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set passwordFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldBaseDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldDefault.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldDefaultPure.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldNotRequired.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldPasswordToggle.twig__1.html
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set textFieldWithInvisibleLabel.twig__1.html
  packages/web-twig/tests/components-fixtures/textFieldPasswordToggle.twig
Labels: feature

#644 Fix(web-twig): Define native return type to "Twig\Extension\ExtensionInterface::getFilters()"
  packages/web-twig/src/Twig/BoolpropExtension.php
Labels: bug

#645 Fix(web): Accordion(Collapse) content flashing #DS-538
  packages/web/src/js/Collapse.ts
  packages/web/src/scss/components/Collapse/README.md
  packages/web/src/scss/components/Collapse/_Collapse.scss
  packages/web/src/scss/components/Collapse/index.html
Labels: bug

#630 Docs(web): Improve `Accordion` README and demo preview
  packages/web/src/scss/components/Accordion/README.md
  packages/web/src/scss/components/Accordion/index.html
Labels: documentation

#654 Refactor(web-react): Fix spelling `adorment` -> `adornment`
  packages/web-react/src/components/TextFieldBase/withPasswordToggle.tsx
  packages/web-react/src/types/shared/adornments.ts
  packages/web-react/src/types/textField.ts
  packages/web-react/src/types/textFieldBase.ts
Labels: refactoring

#655 Feat(web-twig): Enable reusability of SVG icons
  packages/web-twig/src/Resources/components/Icon/Icon.twig
  packages/web-twig/src/Resources/components/Icon/README.md
Labels: feature

#652 Docs(web, web-react): Fix external links in README's
  packages/web-react/README.md
  packages/web/README.md
  packages/web/src/scss/components/Header/README.md
Labels: documentation

#646 Chore(ci): Separate test builds from code quality checks
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: maintenance

#661 Docs(web-react): Fix renderToggle to renderTrigger
  packages/web-react/src/components/Collapse/README.md
Labels: documentation
