Repository lmc-eu/spirit-design-system, pull requests merged in 2024-10, with the labels that each got.

#1673 Fix(variables-scss): Fix SCSS typography font family export
  exporters/variables-scss/generated/exporter.cjs
  exporters/variables-scss/src/generators/__tests__/stylesObjectGenerator.test.ts
  exporters/variables-scss/src/helpers/tokenHelper.ts
  exporters/variables-scss/tests/fixtures/exampleTypographyTokens.ts
Labels: bug

#1667 Fix(web-react): FileUploader document object not found for SSR #DS-1470
  examples/next-with-pages-router/src/pages/index.tsx
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
Labels: bug

#1670 Feat(variables-scss): Add shadow and gradient color variables
  exporters/variables-scss/.eslintrc.cjs
  exporters/variables-scss/generated/exporter.cjs
  exporters/variables-scss/src/generators/__tests__/stylesGenerator.test.ts
  exporters/variables-scss/src/generators/stylesGenerator.ts
  exporters/variables-scss/src/helpers/__tests__/colorHelper.test.ts
  exporters/variables-scss/src/helpers/colorHelper.ts
Labels: feature

#1675 Docs(web-twig): Redesign the demo app #DS-1479
  apps/demo/partials/web/helpers.hbs
  apps/demo/partials/web/tabs.hbs
  apps/web-twig-demo/templates/assets/spiritLogoInverted.html.twig
  apps/web-twig-demo/templates/default.html.twig
  apps/web-twig-demo/templates/helpers.html.twig
  apps/web-twig-demo/templates/layout/base.html.twig
  apps/web-twig-demo/templates/layout/default.html.twig
  apps/web-twig-demo/templates/layout/plain.html.twig
  apps/web-twig-demo/templates/partials/cover.html.twig
  apps/web-twig-demo/templates/partials/footer.html.twig
  apps/web-twig-demo/templates/partials/header.html.twig
  apps/web-twig-demo/templates/partials/tabs.html.twig
  apps/web-twig-demo/templates/validations.html.twig
  packages/web-twig/src/Resources/components/Accordion/Accordion.stories.twig
  packages/web-twig/src/Resources/components/Alert/Alert.stories.twig
  packages/web-twig/src/Resources/components/Breadcrumbs/Breadcrumbs.stories.twig
  packages/web-twig/src/Resources/components/Button/Button.stories.twig
  packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.stories.twig
  packages/web-twig/src/Resources/components/Checkbox/Checkbox.stories.twig
  packages/web-twig/src/Resources/components/Collapse/Collapse.stories.twig
  packages/web-twig/src/Resources/components/Container/Container.stories.twig
  packages/web-twig/src/Resources/components/Divider/Divider.stories.twig
  packages/web-twig/src/Resources/components/Dropdown/Dropdown.stories.twig
  packages/web-twig/src/Resources/components/FieldGroup/FieldGroup.stories.twig
  packages/web-twig/src/Resources/components/FileUploader/FileUploader.stories.twig
  packages/web-twig/src/Resources/components/Grid/Grid.stories.twig
  packages/web-twig/src/Resources/components/Header/Header.stories.twig
  packages/web-twig/src/Resources/components/Heading/Heading.stories.twig
  packages/web-twig/src/Resources/components/Item/Item.stories.twig
  packages/web-twig/src/Resources/components/Link/Link.stories.twig
  packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
  packages/web-twig/src/Resources/components/Pagination/Pagination.stories.twig
  packages/web-twig/src/Resources/components/Pill/Pill.stories.twig
  packages/web-twig/src/Resources/components/Radio/Radio.stories.twig
  packages/web-twig/src/Resources/components/ScrollView/ScrollView.stories.twig
  packages/web-twig/src/Resources/components/Select/Select.stories.twig
  packages/web-twig/src/Resources/components/Spinner/Spinner.stories.twig
  packages/web-twig/src/Resources/components/Stack/Stack.stories.twig
  packages/web-twig/src/Resources/components/Tabs/Tabs.stories.twig
  packages/web-twig/src/Resources/components/Tag/Tag.stories.twig
  packages/web-twig/src/Resources/components/Text/Text.stories.twig
  packages/web-twig/src/Resources/components/TextArea/TextArea.stories.twig
  packages/web-twig/src/Resources/components/TextField/TextField.stories.twig
  packages/web-twig/src/Resources/components/Toast/Toast.stories.twig
  packages/web-twig/src/Resources/components/Tooltip/Tooltip.stories.twig
  packages/web-twig/src/Resources/components/UNSTABLE_ActionLayout/UNSTABLE_ActionLayout.stories.twig
  packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/UNSTABLE_EmptyState.stories.twig
  packages/web-twig/src/Resources/helpers/accessibility/accessibility.stories.twig
  packages/web-twig/src/Resources/helpers/animations/animations.stories.twig
  packages/web-twig/src/Resources/helpers/breakout/breakout.stories.twig
  packages/web-twig/src/Resources/helpers/images/images.stories.twig
  packages/web-twig/src/Resources/helpers/links/links.stories.twig
  packages/web-twig/src/Resources/helpers/lists/lists.stories.twig
  packages/web-twig/src/Resources/helpers/scroll-control/scroll-control.stories.twig
  packages/web-twig/src/Resources/helpers/text/text.stories.twig
  packages/web-twig/src/Resources/helpers/typography/typography.stories.twig
  packages/web-twig/src/Resources/icons/Icons.stories.twig
Labels: documentation

#1677 Test(web,web-react): Update visual snapshots after demo apps redesign #DS-1479
  apps/demo/partials/cover.hbs
  apps/demo/partials/footer.hbs
  apps/demo/partials/header.hbs
  apps/web-twig-demo/templates/partials/cover.html.twig
  apps/web-twig-demo/templates/partials/footer.html.twig
  apps/web-twig-demo/templates/partials/header.html.twig
  tests/e2e/components/demo-modal-compare.spec.ts
  tests/e2e/demo-components-compare.spec.ts
  tests/e2e/demo-components-compare.spec.ts-snapshots/flex-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/grid-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/scrollview-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-emptystate-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
  tests/helpers/hideFromVisualTests.ts
  tests/helpers/index.ts
Labels: run-visual-tests

#1682 Fix(form-validations): Fix form IDs in form-validations demo
  packages/form-validations/index.html
Labels: bug

#1685 Feat(variables-scss): Sort barrel files by alphabet #DS-1502
  exporters/variables-scss/generated/exporter.cjs
  exporters/variables-scss/src/generators/__fixtures__/barrelFileMock.scss
  exporters/variables-scss/src/generators/__tests__/fileGenerator.test.ts
  exporters/variables-scss/src/generators/fileGenerator.ts
Labels: feature

#1683 Feat(variables-scss): Add debug option for exporter #DS-1505
  exporters/variables-scss/README.md
  exporters/variables-scss/config.json
  exporters/variables-scss/config.local.json
  exporters/variables-scss/config.ts
  exporters/variables-scss/generated/exporter.cjs
  exporters/variables-scss/src/helpers/__tests__/safeStringify.test.ts
  exporters/variables-scss/src/helpers/safeStringify.ts
  exporters/variables-scss/src/index.ts
Labels: feature

#1699 Fix(ci): Ensure running cleanup even previous job fails
  .github/workflows/test.yaml
Labels: maintenance

#1700 Chore(ci): Use `dist-tag` only if it is present in command
  Makefile
Labels: maintenance

#1701 Chore(ci): Introduce new `preversion` and `graduate` targets for creating a prerelease version
  Makefile
Labels: maintenance

#1694 Refactor(web-react): No longer use default props in the rest of the c…
  packages/web-react/src/components/FileUploader/AttachmentImagePreview.tsx
  packages/web-react/src/components/Tabs/TabLink.tsx
  packages/web-react/src/components/Tooltip/TooltipTrigger.tsx
  packages/web-react/src/types/fileUploader.ts
Labels: refactoring

#1717 Chore(ci): Fix indentation in Makefile
  Makefile
Labels: maintenance

#1696 Docs(web): Introduce General Changes into the Migration Guide #DS-1489
  docs/migrations/web/MIGRATION-v3.md
Labels: documentation

#1697 Docs(web): Document component changes into the Migration Guide #DS-1489
  docs/migrations/web/MIGRATION-v3.md
Labels: documentation

#1737 Refactor(web-react): Remove forgotten deprecation message
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
Labels: refactoring

#1729 Fix(exporter-tokens): Pass all tokens to the `computeTokensByApplyingThemes` so references work
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/generators/fileGenerator.ts
Labels: bug

#1736 Feat(exporter-tokens): Document Themes naming rules #DS-1497
  exporters/tokens/README.md
Labels: feature

#1734 Refactor(web): Unify generation of responsive spacing and alignment in layout components #DS-1423
  packages/web/src/scss/components/Flex/_Flex.scss
  packages/web/src/scss/components/Grid/_Grid.scss
  packages/web/src/scss/components/Grid/_theme.scss
  packages/web/src/scss/components/Grid/_tools.scss
  packages/web/src/scss/components/Stack/_Stack.scss
  packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
  packages/web/src/scss/tools/__tests__/_spacing.test.scss
  packages/web/src/scss/tools/_dictionaries.scss
  packages/web/src/scss/tools/_spacing.scss
Labels: refactoring

#1738 Feat(design-tokens): Add maps of tokens to color-tokens
  packages/design-tokens/src/scss/themes/_color-tokens.scss
Labels: feature
