Repository lmc-eu/spirit-design-system, pull requests merged in 2024-07, with the labels that each got.

#1534 Docs: Change relative path to absolute path in md #DS-1364
  CONTRIBUTING.md
  DEPRECATIONS-v3.md
  MIGRATION.md
  README.md
  configs/jest-config-spirit/README.md
  configs/prettier-config-spirit/README.md
  configs/stylelint-config-spirit/README.md
  docs/decisions/README.md
  docs/postmortems/README.md
  packages/codemods/README.md
  packages/codemods/src/transforms/v2/web-react/README.md
  packages/web-twig/CONTRIBUTING.md
  packages/web-twig/README.md
  packages/web/README.md
Labels: documentation

#1543 Feat(web): Introduce UNSTABLE Toggle component #DS-1345
  packages/web/src/scss/components/UNSTABLE_Toggle/README.md
  packages/web/src/scss/components/UNSTABLE_Toggle/_UNSTABLE_Toggle.scss
  packages/web/src/scss/components/UNSTABLE_Toggle/_theme.scss
  packages/web/src/scss/components/UNSTABLE_Toggle/index.html
  packages/web/src/scss/components/UNSTABLE_Toggle/index.scss
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/theme/_form-fields.scss
  packages/web/src/scss/tools/_form-fields.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-toggle-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
Labels: feature, run-visual-tests

#1541 Feat(web-react): Introduce UNSTABLE_Truncate component #DS-1098
  packages/web-react/src/components/UNSTABLE_Truncate/README.md
  packages/web-react/src/components/UNSTABLE_Truncate/UNSTABLE_Truncate.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/__tests__/UNSTABLE_Truncate.test.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/__tests__/useTruncateStyleProps.test.ts
  packages/web-react/src/components/UNSTABLE_Truncate/demo/TruncateDefault.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/demo/index.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/index.html
  packages/web-react/src/components/UNSTABLE_Truncate/index.ts
  packages/web-react/src/components/UNSTABLE_Truncate/stories/UNSTABLE_Truncate.stories.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/useTruncateStyleProps.ts
  packages/web-react/src/types/truncate.ts
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-truncate-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: feature, run-visual-tests

#1544 Fix(web-react): Tooltip - fix reported bugs
  packages/web-react/src/components/Tooltip/UncontrolledTooltip.tsx
  packages/web-react/src/components/Tooltip/useTooltip.ts
  packages/web-twig/src/Resources/components/Tooltip/README.md
Labels: bug

#1555 Chore(ci): Build temporarily only on Node.js v18
  .github/workflows/build.yaml
Labels: maintenance

#1545 Feat(web-react): Introduce UNSTABLE_Toggle component #DS-1346
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/UNSTABLE_Toggle/README.md
  packages/web-react/src/components/UNSTABLE_Toggle/UNSTABLE_Toggle.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/__tests__/UNSTABLE_Toggle.test.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/__tests__/useToggleStyleProps.test.ts
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleDefault.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleDisabled.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleFluid.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleHelperText.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleHiddenLabel.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleIndicators.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleRequired.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/ToggleValidation.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/demo/index.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/index.html
  packages/web-react/src/components/UNSTABLE_Toggle/index.ts
  packages/web-react/src/components/UNSTABLE_Toggle/stories/UNSTABLE_Toggle.stories.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/useToggleStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/toggle.ts
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: feature, run-visual-tests

#1558 Fix(exporter-js,exporter-scss): Refactor color normalization to make it actually work #DS-1394
  exporters/js/exporter.json
  exporters/js/generated/functions.js
  exporters/js/src/js/formatters/color.ts
  exporters/js/src/js/normalizers/__tests__/color.test.js
  exporters/js/src/js/normalizers/color.ts
  exporters/scss/exporter.json
  exporters/scss/generated/functions.js
  exporters/scss/src/js/formatters/color.ts
  exporters/scss/src/js/normalizers/__tests__/color.test.js
  exporters/scss/src/js/normalizers/color.ts
Labels: bug

#1547 Test(e2e): Modal Visual Tests #DS-1247
  packages/web-react/src/components/Modal/demo/ModalDefault.tsx
  packages/web-react/src/components/Modal/demo/ModalDisabledBackdropClick.tsx
  packages/web-react/src/components/Modal/demo/ModalHiddenCloseButton.tsx
  packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
  packages/web-react/src/components/Modal/demo/ModalStacking.tsx
  packages/web-twig/src/Resources/components/Modal/stories/ModalDefault.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalDisabledBackdropClick.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalHiddenCloseButton.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalStacking.twig
  packages/web/src/scss/components/Modal/index.html
  tests/e2e/components/demo-modal-compare.spec.ts
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-basic-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-closed-modals-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-disabled-backdrop-click-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-hidden-close-button-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-stacking-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-custom-height-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-dropdown-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-form-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-long-content-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-scrolling-inside-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-scrollview-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts
  tests/e2e/demo-homepages.spec.ts
  tests/helpers/formatPackageName.ts
  tests/helpers/getServerUrl.ts
  tests/helpers/index.ts
  tests/helpers/takeScreenshot.ts
  tests/helpers/waitForPageLoad.ts
Labels: feature, run-visual-tests

#1557 Feat(web-react): Introduce `positionStrategy` prop for Tooltip CSS positions
  packages/web-react/src/components/Tooltip/README.md
  packages/web-react/src/components/Tooltip/Tooltip.tsx
  packages/web-react/src/components/Tooltip/useFloating.ts
  packages/web-react/src/types/tooltip.ts
Labels: feature

#1560 Fix(web-react): Make Tooltip positionStrategy actually work
  packages/web-react/src/components/Tooltip/Tooltip.tsx
  packages/web-react/src/components/Tooltip/TooltipContext.ts
  packages/web-react/src/components/Tooltip/TooltipPopover.tsx
  packages/web-react/src/components/Tooltip/__tests__/useFloatingUI.test.ts
  packages/web-react/src/components/Tooltip/stories/Tooltip.stories.tsx
  packages/web-react/src/components/Tooltip/useFloating.ts
Labels: bug

#1562 Fix(web-twig): Add unintentionally removed content of the composer.json
  packages/web-twig/composer.json
Labels: bug

#1548 Feat(web): Add responsive variants to breakout-container helper #DS-1386
  packages/web/src/scss/helpers/breakout/_breakout.scss
  packages/web/src/scss/helpers/breakout/index.html
Labels: feature
