Repository lmc-eu/spirit-design-system, pull requests merged in 2024-06, with the labels that each got.

#1449 Fix(web-react): Fix types in Dropdown #DS-1221
  packages/web-react/src/components/Dropdown/DropdownTrigger.tsx
  packages/web-react/src/components/Modal/demo/ModalDefault.tsx
  packages/web-react/src/types/dropdown.ts
Labels: bug

#1442 BREAKING CHANGE(web-react): Rename height and maxHeight ModalDialog props and enhance them #DS-1134
  docs/migrations/web-react/MIGRATION-v2.md
  packages/codemods/src/transforms/v2/web-react/README.md
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-custom-height.input.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-custom-height.output.tsx
  packages/codemods/src/transforms/v2/web-react/__tests__/modal-custom-height.test.ts
  packages/codemods/src/transforms/v2/web-react/modal-custom-height.ts
  packages/web-react/src/components/Modal/ModalDialog.tsx
  packages/web-react/src/components/Modal/README.md
  packages/web-react/src/components/Modal/__tests__/ModalDialog.test.tsx
  packages/web-react/src/components/Modal/__tests__/useModalDialogStyleProps.test.ts
  packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
  packages/web-react/src/components/Modal/stories/ModalDialog.stories.tsx
  packages/web-react/src/components/Modal/useModalDialogStyleProps.ts
  packages/web-react/src/types/modal.ts
Labels: BC

#1464 Fix(web-react): Import components from file intead of the index
  packages/web-react/src/components/Toast/UncontrolledToast.tsx
Labels: bug

#1470 Fix(web-twig): Make ValidationText and HelperText ID optional #DS-1336
  packages/web-twig/src/Resources/components/Checkbox/Checkbox.twig
  packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxDefaultPure.twig.snap.html
  packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxItem.twig.snap.html
  packages/web-twig/src/Resources/components/Field/HelperText.twig
  packages/web-twig/src/Resources/components/Field/ValidationText.twig
  packages/web-twig/src/Resources/components/Field/__tests__/__fixtures__/helperText.twig
  packages/web-twig/src/Resources/components/Field/__tests__/__fixtures__/validationText.twig
  packages/web-twig/src/Resources/components/Field/__tests__/__snapshots__/helperText.twig.snap.html
  packages/web-twig/src/Resources/components/Field/__tests__/__snapshots__/validationText.twig.snap.html
  packages/web-twig/src/Resources/components/FieldGroup/FieldGroup.twig
  packages/web-twig/src/Resources/components/FieldGroup/__tests__/__snapshots__/fieldGroup.twig.snap.html
  packages/web-twig/src/Resources/components/FileUploader/FileUploaderInput.twig
  packages/web-twig/src/Resources/components/FileUploader/__tests__/__snapshots__/fileUploaderInput.twig.snap.html
  packages/web-twig/src/Resources/components/Item/Item.twig
  packages/web-twig/src/Resources/components/Radio/Radio.twig
  packages/web-twig/src/Resources/components/Select/Select.twig
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectHelperText.twig.snap.html
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectValidationState.twig.snap.html
  packages/web-twig/src/Resources/components/TextArea/__tests__/__snapshots__/textAreaDefault.twig.snap.html
  packages/web-twig/src/Resources/components/TextArea/__tests__/__snapshots__/textAreaWithAutoResize.twig.snap.html
  packages/web-twig/src/Resources/components/TextArea/__tests__/__snapshots__/textAreaWithHelperText.twig.snap.html
  packages/web-twig/src/Resources/components/TextArea/__tests__/__snapshots__/textAreaWithMultilineMessage.twig.snap.html
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/passwordFieldDefault.twig.snap.html
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldDefault.twig.snap.html
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldDefaultPure.twig.snap.html
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldWithHelperText.twig.snap.html
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldWithMultilineMessage.twig.snap.html
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldWithUnsafe.twig.snap.html
  packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig
  packages/web-twig/src/Resources/components/TextFieldBase/__tests__/__snapshots__/textFieldBaseDefault.twig.snap.html
  packages/web-twig/src/Resources/components/TextFieldBase/__tests__/__snapshots__/textFieldBaseMultiline.twig.snap.html
Labels: bug

#1487 Fix(web-react): Remove unsupported style props from modified props in style hook
  packages/web-react/src/hooks/__tests__/styleProps.test.ts
  packages/web-react/src/hooks/styleProps.ts
Labels: bug

#1491 Docs: Introduce decision about release names
  docs/decisions/007-release-names.md
Labels: documentation

#1471 Feat(web): Introduce UNSTABLE_Slider component #DS-1321
  packages/web/src/scss/components/UNSTABLE_Slider/README.md
  packages/web/src/scss/components/UNSTABLE_Slider/_UNSTABLE_Slider.scss
  packages/web/src/scss/components/UNSTABLE_Slider/_theme.scss
  packages/web/src/scss/components/UNSTABLE_Slider/_tools.scss
  packages/web/src/scss/components/UNSTABLE_Slider/index.html
  packages/web/src/scss/components/UNSTABLE_Slider/index.scss
  packages/web/src/scss/components/index.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-slider-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
Labels: feature

#1475 Style(web-twig): Update to latest version of Alma Career Czechia PHP coding style
  packages/web-twig/composer.json
  packages/web-twig/easy-coding-standard.yaml
  packages/web-twig/ecs.php
  packages/web-twig/src/DependencyInjection/SpiritWebTwigExtension.php
  packages/web-twig/src/Factory/TwigFactory.php
  packages/web-twig/src/Resources/components/Accordion/__tests__/AccordionSnapshotTest.php
  packages/web-twig/src/Resources/components/Alert/__tests__/AlertSnapshotTest.php
  packages/web-twig/src/Resources/components/Breadcrumbs/__tests__/BreadcrumbsSnapshotTest.php
  packages/web-twig/src/Resources/components/Button/__tests__/ButtonSnapshotTest.php
  packages/web-twig/src/Resources/components/ButtonLink/__tests__/ButtonLinkSnapshotTest.php
  packages/web-twig/src/Resources/components/Checkbox/__tests__/CheckboxSnapshotTest.php
  packages/web-twig/src/Resources/components/Collapse/__tests__/CollapseSnapshotTest.php
  packages/web-twig/src/Resources/components/Container/__tests__/ContainerSnapshotTest.php
  packages/web-twig/src/Resources/components/Dropdown/__tests__/DropdownSnapshotTest.php
  packages/web-twig/src/Resources/components/Field/__tests__/FieldSnapshotTest.php
  packages/web-twig/src/Resources/components/FieldGroup/__tests__/FieldGroupSnapshotTest.php
  packages/web-twig/src/Resources/components/FileUploader/__tests__/FileUploaderSnapshotTest.php
  packages/web-twig/src/Resources/components/Grid/__tests__/GridSnapshotTest.php
  packages/web-twig/src/Resources/components/Header/__tests__/HeaderSnapshotTest.php
  packages/web-twig/src/Resources/components/Heading/__tests__/HeadingSnapshotTest.php
  packages/web-twig/src/Resources/components/Icon/__tests__/IconSnapshotTest.php
  packages/web-twig/src/Resources/components/Item/__tests__/ItemSnapshotTest.php
  packages/web-twig/src/Resources/components/Link/__tests__/LinkSnapshotTest.php
  packages/web-twig/src/Resources/components/Modal/__tests__/ModalSnapshotTest.php
  packages/web-twig/src/Resources/components/Pagination/__tests__/PaginationSnapshotTest.php
  packages/web-twig/src/Resources/components/Pill/__tests__/PillSnapshotTest.php
  packages/web-twig/src/Resources/components/Radio/__tests__/RadioSnapshotTest.php
  packages/web-twig/src/Resources/components/ScrollView/__tests__/ScrollViewSnapshotTest.php
  packages/web-twig/src/Resources/components/Select/__tests__/SelectSnapshotTest.php
  packages/web-twig/src/Resources/components/Spinner/__tests__/SpinnerSnapshotTest.php
  packages/web-twig/src/Resources/components/Stack/__tests__/StackSnapshotTest.php
  packages/web-twig/src/Resources/components/Tabs/__tests__/TabsSnapshotTest.php
  packages/web-twig/src/Resources/components/Tag/__tests__/TagSnapshotTest.php
  packages/web-twig/src/Resources/components/Text/__tests__/TextSnapshotTest.php
  packages/web-twig/src/Resources/components/TextArea/__tests__/TextAreaSnapshotTest.php
  packages/web-twig/src/Resources/components/TextField/__tests__/TextFieldSnapshotTest.php
  packages/web-twig/src/Resources/components/TextFieldBase/__tests__/TextFieldBaseSnapshotTest.php
  packages/web-twig/src/Resources/components/Toast/__tests__/ToastSnapshotTest.php
  packages/web-twig/src/Resources/components/Tooltip/__tests__/TooltipSnapshotTest.php
  packages/web-twig/src/Resources/components/VisuallyHidden/__tests__/VisuallyHiddenSnapshotTest.php
  packages/web-twig/src/Twig/PropsExtension.php
  packages/web-twig/src/Twig/SvgExtension.php
  packages/web-twig/tests/AbstractComponentSnapshotTest.php
  packages/web-twig/tests/ComponentTest.php
  packages/web-twig/tests/DependencyInjection/CompilerPass/OverrideServiceCompilerPassTest.php
  packages/web-twig/tests/DependencyInjection/ConfigurationTest.php
  packages/web-twig/tests/DependencyInjection/SpiritWebTwigExtensionTest.php
  packages/web-twig/tests/Helper/TwigHelper.php
  packages/web-twig/tests/Twig/PropsExtensionTest.php
  packages/web-twig/tests/Twig/SvgExtensionTest.php
Labels: feature

#1498 Chore(ci): Disable NX cloud caching
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: maintenance

#1497 Fix(web, web-twig): Demo - Checkbox indeterminate
  packages/web-twig/src/Resources/components/Checkbox/Checkbox.stories.twig
  packages/web/src/scss/components/Checkbox/index.html
Labels: bug

#1502 Refactor(web-twig): Rename unstable Divider to fix case insensitive problem
  packages/web-twig/src/Resources/twig-components/unstable_Divider.twig
Labels: bug

#1504 Chore(demo): Add path alias to web-twig-demo to fix missing module
  apps/web-twig-demo/webpack.config.js
Labels: bug

#1516 Chore(repo): Update lockfile due to dependency conflicts
  yarn.lock
Labels: maintenance

#1520 Test(ci): Allow unstable components safely fail E2E tests
  tests/e2e/demo-components-compare.spec.ts
Labels: maintenance, run-visual-tests
