Repository lmc-eu/spirit-design-system, pull requests merged in 2024-01, with the labels that each got.

#1199 Deps: Update browserslist database
  yarn.lock
Labels: maintenance

#1205 Chore(web): Require `sass` from v1.57.0 above due to `string.split`
  packages/web/package.json
Labels: maintenance

#1179 Fix(web-react): Do not render empty `style` prop
  packages/web-react/src/hooks/__tests__/styleProps.test.ts
  packages/web-react/src/hooks/styleProps.ts
Labels: bug

#1231 Docs(web): Record our convention for CSS and JS selectors to avoid confusion
  packages/web/CONTRIBUTING.md
Labels: documentation

#1235 Fix(web-twig): Do not render CSS property in the `GridItem` style attribute if the value is empty
  packages/web-twig/src/Resources/components/Grid/GridItem.twig
  packages/web-twig/src/Resources/components/Grid/__tests__/__fixtures__/gridItemDefault.twig
  packages/web-twig/src/Resources/components/Grid/__tests__/__snapshots__/gridItemDefault.twig.snap.html
Labels: feature

#1241 Feat(web-twig): Introduce vertical alignment options for `Modal` #DS-940
  packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
  packages/web-twig/src/Resources/components/Modal/Modal.twig
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
  packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDisabledBackdropClick.twig.snap.html
  packages/web-twig/src/Resources/components/Modal/stories/ModalDefault.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalUniformModalOnMobile.twig
Labels: feature

#1242 Refactor(web-react): Clean up shared non-dictionary types and constants
  packages/web-react/src/components/FileUploader/constants.ts
  packages/web-react/src/components/FileUploader/useFileUploaderStyleProps.ts
  packages/web-react/src/components/ScrollView/useScrollPosition.ts
  packages/web-react/src/constants/dictionaries.ts
  packages/web-react/src/constants/index.ts
  packages/web-react/src/constants/position.ts
  packages/web-react/src/types/shared/alignments.ts
  packages/web-react/src/types/shared/colors.ts
  packages/web-react/src/types/shared/dictionaries.ts
  packages/web-react/src/types/shared/index.ts
  packages/web-react/src/types/shared/positions.ts
Labels: refactoring

#1243 Feat(web-react): Introduce vertical alignment options for `Modal` #DS…
  packages/web-react/src/components/Modal/Modal.tsx
  packages/web-react/src/components/Modal/ModalFooter.tsx
  packages/web-react/src/components/Modal/README.md
  packages/web-react/src/components/Modal/__tests__/useModalStyleProps.test.ts
  packages/web-react/src/components/Modal/demo/ModalDefault.tsx
  packages/web-react/src/components/Modal/demo/ModalUniformModalOnMobile.tsx
  packages/web-react/src/components/Modal/stories/Modal.stories.tsx
  packages/web-react/src/components/Modal/useModalStyleProps.ts
  packages/web-react/src/constants/dictionaries.ts
  packages/web-react/src/types/modal.ts
  packages/web-react/src/types/shared/dictionaries.ts
  packages/web-twig/src/Resources/components/Modal/stories/ModalUniformModalOnMobile.twig
  packages/web/src/scss/components/Modal/index.html
Labels: feature

#1244 Chore(ci): Rename label that runs visual tests on PR
  .github/workflows/e2e.yml
Labels: maintenance

#1239 Fix(web-react): Cleanup scrolling when Modal is unmounted
  packages/web-react/src/hooks/__tests__/useScrollControl.test.ts
  packages/web-react/src/hooks/useScrollControl.ts
Labels: bug

#1251 Chore(ci): Test builds also on Node.js v20
  .github/workflows/build.yaml
Labels: maintenance

#1252 Chore(repo): Ignore Nx cache files by Git
  .gitignore
Labels: maintenance
