Repository lmc-eu/spirit-design-system, pull requests merged in 2024-02, with the labels that each got.

#1263 Feat(web-react): Introduce option to disable scrolling inside Modal #…
  packages/web-react/src/components/Modal/ModalDialog.tsx
  packages/web-react/src/components/Modal/README.md
  packages/web-react/src/components/Modal/__tests__/ModalDialog.test.tsx
  packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
  packages/web-react/src/components/Modal/demo/ModalUniformModalOnMobile.tsx
  packages/web-react/src/components/Modal/stories/ModalDialog.stories.tsx
  packages/web-react/src/components/Modal/useModalStyleProps.ts
  packages/web-react/src/types/modal.ts
Labels: feature

#1264 Feat(web-twig): Introduce option to disable scrolling inside Modal #D…
  packages/web-twig/src/Resources/components/Modal/Modal.stories.twig
  packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
  packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
  packages/web-twig/src/Resources/components/Modal/stories/ModalUniformModalOnMobile.twig
Labels: feature

#1265 Docs(web-react): Improve additional API options info #DS-1099
  packages/web-react/README.md
  packages/web-react/src/components/Accordion/README.md
  packages/web-react/src/components/Alert/README.md
  packages/web-react/src/components/Breadcrumbs/README.md
  packages/web-react/src/components/Button/README.md
  packages/web-react/src/components/ButtonLink/README.md
  packages/web-react/src/components/Checkbox/README.md
  packages/web-react/src/components/Collapse/README.md
  packages/web-react/src/components/Container/README.md
  packages/web-react/src/components/Dialog/README.md
  packages/web-react/src/components/Dropdown/README.md
  packages/web-react/src/components/FieldGroup/README.md
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/components/Grid/README.md
  packages/web-react/src/components/Header/README.md
  packages/web-react/src/components/Heading/README.md
  packages/web-react/src/components/Icon/README.md
  packages/web-react/src/components/Item/README.md
  packages/web-react/src/components/Link/README.md
  packages/web-react/src/components/Modal/README.md
  packages/web-react/src/components/Pagination/README.md
  packages/web-react/src/components/Pill/README.md
  packages/web-react/src/components/Radio/README.md
  packages/web-react/src/components/ScrollView/README.md
  packages/web-react/src/components/Select/README.md
  packages/web-react/src/components/Spinner/README.md
  packages/web-react/src/components/Stack/README.md
  packages/web-react/src/components/Tabs/README.md
  packages/web-react/src/components/Tag/README.md
  packages/web-react/src/components/Text/README.md
  packages/web-react/src/components/TextArea/README.md
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/components/TextFieldBase/README.md
  packages/web-react/src/components/Tooltip/README.md
  packages/web-react/src/components/VisuallyHidden/README.md
Labels: documentation

#1258 Docs(web-twig): Improve additional API options info #DS-1099
  packages/web-twig/README.md
  packages/web-twig/src/Resources/components/Accordion/README.md
  packages/web-twig/src/Resources/components/Alert/README.md
  packages/web-twig/src/Resources/components/Breadcrumbs/README.md
  packages/web-twig/src/Resources/components/Button/README.md
  packages/web-twig/src/Resources/components/ButtonLink/README.md
  packages/web-twig/src/Resources/components/Checkbox/README.md
  packages/web-twig/src/Resources/components/Collapse/README.md
  packages/web-twig/src/Resources/components/Container/README.md
  packages/web-twig/src/Resources/components/Dropdown/README.md
  packages/web-twig/src/Resources/components/FieldGroup/README.md
  packages/web-twig/src/Resources/components/FileUploader/README.md
  packages/web-twig/src/Resources/components/Grid/README.md
  packages/web-twig/src/Resources/components/Header/README.md
  packages/web-twig/src/Resources/components/Heading/README.md
  packages/web-twig/src/Resources/components/Icon/README.md
  packages/web-twig/src/Resources/components/Item/README.md
  packages/web-twig/src/Resources/components/Link/README.md
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/components/Pagination/README.md
  packages/web-twig/src/Resources/components/Pill/README.md
  packages/web-twig/src/Resources/components/Radio/README.md
  packages/web-twig/src/Resources/components/ScrollView/README.md
  packages/web-twig/src/Resources/components/Select/README.md
  packages/web-twig/src/Resources/components/Spinner/README.md
  packages/web-twig/src/Resources/components/Stack/README.md
  packages/web-twig/src/Resources/components/Tabs/README.md
  packages/web-twig/src/Resources/components/Tag/README.md
  packages/web-twig/src/Resources/components/Text/README.md
  packages/web-twig/src/Resources/components/TextArea/README.md
  packages/web-twig/src/Resources/components/TextField/README.md
  packages/web-twig/src/Resources/components/TextFieldBase/README.md
  packages/web-twig/src/Resources/components/Tooltip/README.md
  packages/web-twig/src/Resources/components/VisuallyHidden/README.md
Labels: documentation

#1270 Fix(web-react): Remove unnecessary rest props on Tooltip Trigger #DS-…
  packages/web-react/src/components/Tooltip/TooltipTrigger.tsx
  packages/web-react/src/components/TooltipModern/demo/TooltipDismissible.tsx
Labels: bug

#1253 Feat(web): Unify naming in SCSS, use padding or gap #DS-782
  packages/web/src/scss/components/Accordion/_Accordion.scss
  packages/web/src/scss/components/Accordion/_theme.scss
  packages/web/src/scss/components/Checkbox/_Checkbox.scss
  packages/web/src/scss/components/Item/_Item.scss
  packages/web/src/scss/components/Item/_theme.scss
  packages/web/src/scss/components/Radio/_Radio.scss
  packages/web/src/scss/theme/_form-fields.scss
  packages/web/src/scss/tools/_form-fields.scss
Labels: feature

#1273 Feat(web-twig): Deprecate Dropdown non flow placements DS-1132
  packages/web-twig/src/Resources/components/Dropdown/Dropdown.twig
  packages/web-twig/src/Resources/components/Dropdown/README.md
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__fixtures__/dropdown.twig
  packages/web-twig/src/Resources/components/Dropdown/__tests__/__snapshots__/dropdown.twig.snap.html
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownDisabledAutoclose.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFeatureEnhancedShadow.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthAll.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownFullwidthMobileOnly.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownLongerContent.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownPlacements.twig
  packages/web-twig/src/Resources/components/Dropdown/stories/DropdownVariousItems.twig
Labels: feature

#1271 Feat(web): Deprecate Dropdown non flow and modifier placement DS-1132
  packages/web/src/scss/components/Dropdown/README.md
  packages/web/src/scss/components/Dropdown/index.html
  packages/web/src/scss/components/Item/README.md
Labels: feature

#1274 Feat(web-react): Deprecate Dropdown non flow placements DS-1132
  packages/web-react/src/components/Dropdown/Dropdown.tsx
  packages/web-react/src/components/Dropdown/DropdownContext.ts
  packages/web-react/src/components/Dropdown/DropdownPopover.tsx
  packages/web-react/src/components/Dropdown/README.md
  packages/web-react/src/components/Dropdown/__tests__/useDropdownAriaProps.test.ts
  packages/web-react/src/components/Dropdown/__tests__/useDropdownStyleProps.test.ts
  packages/web-react/src/components/Dropdown/demo/DropdownEnhancedShadow.tsx
  packages/web-react/src/components/Dropdown/demo/DropdownFullwidthAll.tsx
  packages/web-react/src/components/Dropdown/demo/DropdownFullwidthMobileOnly.tsx
  packages/web-react/src/components/Dropdown/demo/DropdownPlacements.tsx
  packages/web-react/src/components/Dropdown/stories/Dropdown.stories.tsx
  packages/web-react/src/components/Dropdown/useDropdownAriaProps.ts
  packages/web-react/src/components/Dropdown/useDropdownStyleProps.ts
  packages/web-twig/src/Resources/components/Dropdown/README.md
Labels: feature

#1289 Fix(web-react): Replace usage of `html-react-parser` in CommonJS files
  packages/web-react/package.json
  packages/web-react/scripts/postProcess.js
Labels: bug

#1292 Docs(repo): Comment info for contributors in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#1299 Chore(web-twig): Use Node v18 for development since the Docker image for v16 no longer exists
  apps/web-twig-demo/docker/docker-compose.override.yml
Labels: maintenance

#1293 Feat(web): Introduce the `Toast` component #DS-1112
  packages/web/src/scss/components/Grid/_tools.scss
  packages/web/src/scss/components/Toast/README.md
  packages/web/src/scss/components/Toast/_Toast.scss
  packages/web/src/scss/components/Toast/_ToastBar.scss
  packages/web/src/scss/components/Toast/_theme.scss
  packages/web/src/scss/components/Toast/index.html
  packages/web/src/scss/components/Toast/index.scss
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/tools/__tests__/_breakpoint.test.scss
  packages/web/src/scss/tools/_breakpoint.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/offcanvas-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/toast-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
Labels: feature, run visual tests
