Repository lmc-eu/spirit-design-system, pull requests merged in 2024-05, with the labels that each got.

#1386 BREAKING CHANGE(web-react): Remove deprecated buttonLabel and editBut…
  packages/web-react/DEPRECATIONS-v2.md
  packages/web-react/src/components/FileUploader/FileUploaderAttachment.tsx
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/types/fileUploader.ts
Labels: BC

#1390 Docs(form-validations): Fix typo in a destroy function
  packages/form-validations/README.md
Labels: documentation

#1391 BREAKING CHANGE(web-twig): Remove deprecated warning icon for the dan…
  packages/web-twig/DEPRECATIONS-v3.md
  packages/web-twig/src/Resources/components/Alert/Alert.twig
  packages/web-twig/src/Resources/components/Alert/README.md
  packages/web-twig/src/Resources/components/Alert/__tests__/__snapshots__/alertDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Alert/stories/AlertCentered.twig
  packages/web-twig/src/Resources/components/Alert/stories/AlertColors.twig
Labels: BC

#1393 BREAKING CHANGE(web): PaginationItem has the same width as the Pagina…
  packages/web/src/scss/components/Pagination/_theme.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/pagination-chromium-linux.png
Labels: BC, run-visual-tests

#1401 Chore(repo): Fix title package name check
  apps/demo/partials/header.hbs
  apps/demo/partials/layout/base.hbs
Labels: maintenance

#1404 Style(repo): Ignore `lock` files by Prettier formatter
  .prettierignore
Labels: maintenance

#1417 Test: Update Toast screenshot
  tests/e2e/demo-components-compare.spec.ts-snapshots/toast-chromium-linux.png
Labels: bug, run-visual-tests

#1421 Fix(web-react): Warn when icon asset is missing from the map
  packages/web-react/src/hooks/__tests__/useIcon.test.tsx
  packages/web-react/src/hooks/useIcon.ts
Labels: bug

#1412 BREAKING CHANGE(web): Turn off scrolling inside `ModalDialog` by default #DS-1184
  docs/migrations/web/MIGRATION-v2.md
  packages/web/DEPRECATIONS-v2.md
  packages/web/src/scss/components/Modal/README.md
  packages/web/src/scss/components/Modal/_Modal.scss
  packages/web/src/scss/components/Modal/_ModalBody.scss
  packages/web/src/scss/components/Modal/_ModalDialog.scss
  packages/web/src/scss/components/Modal/_theme.scss
  packages/web/src/scss/components/Modal/index.html
Labels: BC

#1427 Chore(form-validations): Add missing TypeScript dependency
  packages/form-validations/package.json
  yarn.lock
Labels: maintenance

#1418 Test(web): Remove unnecessary stylelint disable and rename sass-true module
  packages/web/src/scss/tools/__tests__/_accessibility.test.scss
  packages/web/src/scss/tools/__tests__/_breakpoint.test.scss
  packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
  packages/web/src/scss/tools/__tests__/_form-fields.test.scss
  packages/web/src/scss/tools/__tests__/_links.test.scss
  packages/web/src/scss/tools/__tests__/_list.test.scss
  packages/web/src/scss/tools/__tests__/_placement.test.scss
  packages/web/src/scss/tools/__tests__/_reset.test.scss
  packages/web/src/scss/tools/__tests__/_string.test.scss
  packages/web/src/scss/tools/__tests__/_svg.test.scss
  packages/web/src/scss/tools/__tests__/_typography.test.scss
  packages/web/src/scss/tools/__tests__/_utilities.test.scss
Labels: bug

#1425 BREAKING CHANGE(web-react): Tooltip remove off placement #DS-1193
  packages/web-react/DEPRECATIONS-v2.md
Labels: BC

#1409 Style: Switch from `pretty-quick` to `lint-staged`
  .husky/pre-commit
  .lintstagedrc.mjs
  package.json
  yarn.lock
Labels: maintenance

#1419 Docs(codemods): Add list of all current codemods we have #DS-1214
  packages/codemods/README.md
  packages/codemods/src/transforms/v2/web-react/README.md
Labels: documentation

#1428 Fix(form-validations): Use GridItem instead of GridSpan in demo #DS-1279
  apps/web-twig-demo/templates/validations.html.twig
  packages/form-validations/index.html
Labels: bug

#1430 BREAKING CHANGE(web-react): Turn off scrolling inside ModalDialog by default #DS-1184
  docs/migrations/web-react/MIGRATION-v2.md
  packages/web-react/DEPRECATIONS-v2.md
  packages/web-react/src/components/Modal/README.md
  packages/web-react/src/components/Modal/__tests__/Modal.test.tsx
  packages/web-react/src/components/Modal/__tests__/ModalCloseButton.test.tsx
  packages/web-react/src/components/Modal/__tests__/ModalDialog.test.tsx
  packages/web-react/src/components/Modal/demo/ModalDefault.tsx
  packages/web-react/src/components/Modal/demo/ModalDisabledBackdropClick.tsx
  packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
  packages/web-react/src/components/Modal/demo/ModalStacked.tsx
  packages/web-react/src/components/Modal/demo/ModalStacking.tsx
  packages/web-react/src/components/Modal/demo/ModalWithCustomHeight.tsx
  packages/web-react/src/components/Modal/demo/ModalWithLongText.tsx
  packages/web-react/src/components/Modal/useModalStyleProps.ts
  tests/e2e/demo-components-compare.spec.ts-snapshots/modal-chromium-linux.png
Labels: BC, run-visual-tests

#1438 Fix(web-react): Tooltip closing by outside click when `isDismissible` prop set
  packages/web-react/src/components/Tooltip/Tooltip.tsx
  packages/web-react/src/components/Tooltip/__tests__/useFloatingUI.test.ts
  packages/web-react/src/components/Tooltip/useFloating.ts
Labels: bug

#1422 BREAKING CHANGE(web): Enhance custom height and max height options of `ModalDialog` #DS-1134
  docs/migrations/web/MIGRATION-v2.md
  packages/web/src/scss/components/Modal/README.md
  packages/web/src/scss/components/Modal/_ModalDialog.scss
  packages/web/src/scss/components/Modal/_theme.scss
  packages/web/src/scss/components/Modal/index.html
Labels: BC, run-visual-tests

#1434 BREAKING CHANGE(web-twig): Rename height and maxHeight ModalDialog props and enhance them #DS-1134
  docs/migrations/web-twig/MIGRATION-v3.md
  packages/web-twig/src/Resources/components/Modal/ModalDialog.twig
  packages/web-twig/src/Resources/components/Modal/README.md
  packages/web-twig/src/Resources/components/Modal/__tests__/__fixtures__/modalDefault.twig
  packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
Labels: BC

#1441 BREAKING CHANGE(web-twig): Make TooltipPopover hidden by default
  docs/migrations/web-twig/MIGRATION-v3.md
  packages/web-twig/src/Resources/components/Tooltip/README.md
  packages/web-twig/src/Resources/components/Tooltip/TooltipPopover.twig
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltipPopover.twig.snap.html
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipClickable.twig
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipDismissibleViaJS.twig
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipEnableHover.twig
  packages/web-twig/src/Resources/components/Tooltip/stories/TooltipIcon.twig
Labels: BC
