Repository lmc-eu/spirit-design-system, pull requests merged in 2024-12, with the labels that each got.

#1727 fix(codemods): Codemods create extra parentheses
  packages/codemods/src/helpers/index.ts
  packages/codemods/src/helpers/removeParentheses.ts
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/button-isSquare-prop-name.input.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/button-isSquare-prop-name.output.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/buttonLink-isSquare-prop-name.input.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/buttonLink-isSquare-prop-name.output.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/heading-elementType-prop.input.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/heading-elementType-prop.output.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/link-underlined-prop.input.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/link-underlined-prop.output.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/toastbar-inverted-neutral.input.tsx
  packages/codemods/src/transforms/v3/web-react/__testfixtures__/toastbar-inverted-neutral.output.tsx
  packages/codemods/src/transforms/v3/web-react/button-isSquare-prop-name.ts
  packages/codemods/src/transforms/v3/web-react/buttonLink-isSquare-prop-name.ts
  packages/codemods/src/transforms/v3/web-react/heading-elementType-prop.ts
  packages/codemods/src/transforms/v3/web-react/link-hasVisitedStyleAllowed-prop.ts
  packages/codemods/src/transforms/v3/web-react/link-underlined-prop.ts
  packages/codemods/src/transforms/v3/web-react/toastbar-inverted-neutral.ts
  packages/codemods/tsconfig.json
Labels: bug

#1789 Docs: Add missing migration links to packages
  packages/web-react/MIGRATIONS.md
  packages/web-twig/MIGRATIONS.md
  packages/web/MIGRATIONS.md
Labels: documentation

#1763 Docs: Introduce Tokens Structure Decision
  docs/decisions/009-tokens-structure.md
Labels: documentation

#1799 Chore(repo): Add New Cover Image
  README.md
  static/spirit.svg
Labels: feature

#1757 Feat(web-react): Introduce Card component #1535
  packages/web-react/docs/stories/examples/CardComposition.stories.tsx
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Card/Card.tsx
  packages/web-react/src/components/Card/CardArtwork.tsx
  packages/web-react/src/components/Card/CardBody.tsx
  packages/web-react/src/components/Card/CardEyebrow.tsx
  packages/web-react/src/components/Card/CardFooter.tsx
  packages/web-react/src/components/Card/CardLink.tsx
  packages/web-react/src/components/Card/CardLogo.tsx
  packages/web-react/src/components/Card/CardMedia.tsx
  packages/web-react/src/components/Card/CardTitle.tsx
  packages/web-react/src/components/Card/README.md
  packages/web-react/src/components/Card/__tests__/Card.test.tsx
  packages/web-react/src/components/Card/__tests__/CardArtwork.test.tsx
  packages/web-react/src/components/Card/__tests__/CardBody.test.tsx
  packages/web-react/src/components/Card/__tests__/CardEyebrow.test.tsx
  packages/web-react/src/components/Card/__tests__/CardFooter.test.tsx
  packages/web-react/src/components/Card/__tests__/CardLink.test.tsx
  packages/web-react/src/components/Card/__tests__/CardLogo.test.tsx
  packages/web-react/src/components/Card/__tests__/CardMedia.test.tsx
  packages/web-react/src/components/Card/__tests__/CardTitle.test.tsx
  packages/web-react/src/components/Card/__tests__/__fixtures__/CardStylePropsDataProvider.ts
  packages/web-react/src/components/Card/__tests__/useCardStyleProps.test.ts
  packages/web-react/src/components/Card/demo/CardContentOptions.tsx
  packages/web-react/src/components/Card/demo/CardCustom.tsx
  packages/web-react/src/components/Card/demo/CardFooterAlignment.tsx
  packages/web-react/src/components/Card/demo/CardFooterContent.tsx
  packages/web-react/src/components/Card/demo/CardGeneralOptions.tsx
  packages/web-react/src/components/Card/demo/CardHorizontalLayout.tsx
  packages/web-react/src/components/Card/demo/CardLogo.tsx
  packages/web-react/src/components/Card/demo/CardMediaOptions.tsx
  packages/web-react/src/components/Card/demo/CardMediaSizes.tsx
  packages/web-react/src/components/Card/demo/CardReversedHorizontalLayout.tsx
  packages/web-react/src/components/Card/demo/CardText.tsx
  packages/web-react/src/components/Card/demo/CardTitleOptions.tsx
  packages/web-react/src/components/Card/demo/constants.tsx
  packages/web-react/src/components/Card/demo/index.tsx
  packages/web-react/src/components/Card/index.html
  packages/web-react/src/components/Card/index.ts
  packages/web-react/src/components/Card/stories/Card.stories.tsx
  packages/web-react/src/components/Card/stories/CardArtwork.stories.tsx
  packages/web-react/src/components/Card/stories/CardBody.stories.tsx
  packages/web-react/src/components/Card/stories/CardEyebrow.stories.tsx
  packages/web-react/src/components/Card/stories/CardFooter.stories.tsx
  packages/web-react/src/components/Card/stories/CardLink.stories.tsx
  packages/web-react/src/components/Card/stories/CardLogo.stories.tsx
  packages/web-react/src/components/Card/stories/CardMedia.stories.tsx
  packages/web-react/src/components/Card/stories/CardTitle.stories.tsx
  packages/web-react/src/components/Card/useCardStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/card.ts
  packages/web-react/src/types/index.ts
  packages/web-react/tests/providerTests/dictionaryPropsTest.tsx
Labels: feature

#1775 Chore(web): Allow duplicate headings in docs
  .remarkrc.mjs
  packages/web/src/scss/components/Accordion/README.md
  packages/web/src/scss/components/FileUploader/README.md
  packages/web/src/scss/components/Header/README.md
  packages/web/src/scss/components/Modal/README.md
  packages/web/src/scss/components/Toast/README.md
Labels: documentation

#1814 Fix(web-react): Add missing exports to components index
  packages/web-react/src/components/index.ts
Labels: bug

#1790 Docs(repo): Introduce Spirit release schedule document
  .prettierignore
  docs/contribution/release-schedule.md
  static/release-schedule.svg
Labels: documentation

#1805 Docs(web-react): Add IconsProvider documentation #DS-815
  packages/web-react/src/components/Accordion/README.md
  packages/web-react/src/components/Alert/README.md
  packages/web-react/src/components/Breadcrumbs/README.md
  packages/web-react/src/components/Button/README.md
  packages/web-react/src/components/ButtonLink/README.md
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/components/Header/README.md
  packages/web-react/src/components/Icon/README.md
  packages/web-react/src/components/Item/README.md
  packages/web-react/src/components/Modal/README.md
  packages/web-react/src/components/Pagination/README.md
  packages/web-react/src/components/Select/README.md
  packages/web-react/src/components/Spinner/README.md
  packages/web-react/src/components/Toast/README.md
  packages/web-react/src/components/Tooltip/README.md
  packages/web-react/src/components/UNSTABLE_Avatar/README.md
Labels: documentation

#1795 Feat(web): Introduce Navigation and NavigationLink components #DS-1551 #DS-1530
  packages/web/src/scss/components/Navigation/README.md
  packages/web/src/scss/components/Navigation/_Navigation.scss
  packages/web/src/scss/components/Navigation/_NavigationLink.scss
  packages/web/src/scss/components/Navigation/_theme.scss
  packages/web/src/scss/components/Navigation/index.html
  packages/web/src/scss/components/Navigation/index.scss
  packages/web/src/scss/components/UNSTABLE_Header/README.md
  packages/web/src/scss/components/UNSTABLE_Header/index.html
  packages/web/src/scss/components/index.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/navigation-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-header-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
Labels: feature, run-visual-tests

#1786 Chore(deps): Group dependency updates into smaller PRs
  .renovaterc.json
Labels: maintenance

#1821 Chore(ci): Check for the clean working directory after the build
  .github/workflows/build.yaml
Labels: maintenance

#1288 Chore(web-react): Web package is optional peer dependency
  packages/web-react/package.json
  yarn.lock
Labels: maintenance

#1824 Fix(web): Wrap `Card` demos in Containers
  packages/web/src/scss/components/Card/index.html
Labels: bug, run-visual-tests
