Repository lmc-eu/spirit-design-system, pull requests merged in 2024-09, with the labels that each got.

#1592 Feat(variables-scss): Variables-scss exporter can export new tokens structure #DS-1435
  .prettierignore
  exporters/variables-scss/.eslintrc.cjs
  exporters/variables-scss/.eslintrc.js
  exporters/variables-scss/exporter.json
  exporters/variables-scss/generated/exporter.cjs
  exporters/variables-scss/generated/exporter.js
  exporters/variables-scss/package.json
  exporters/variables-scss/src/content/token.ts
  exporters/variables-scss/src/formatters/__fixtures__/exampleFileContent.scss
  exporters/variables-scss/src/formatters/__fixtures__/formattedExample.scss
  exporters/variables-scss/src/formatters/__fixtures__/mockedExampleTokens.ts
  exporters/variables-scss/src/formatters/__fixtures__/unformattedExample.scss
  exporters/variables-scss/src/formatters/__tests__/cssFormatter.test.ts
  exporters/variables-scss/src/formatters/cssFormatter.ts
  exporters/variables-scss/src/generators/__tests__/contentGenerator.test.ts
  exporters/variables-scss/src/generators/__tests__/cssGenerator.test.ts
  exporters/variables-scss/src/generators/__tests__/cssObjectGenerator.test.ts
  exporters/variables-scss/src/generators/__tests__/fileGenerator.test.ts
  exporters/variables-scss/src/generators/contentGenerator.ts
  exporters/variables-scss/src/generators/cssGenerator.ts
  exporters/variables-scss/src/generators/cssObjectGenerator.ts
  exporters/variables-scss/src/generators/fileGenerator.ts
  exporters/variables-scss/src/generators/simple.ts
  exporters/variables-scss/src/helpers/__tests__/specialCaseHelper.test.ts
  exporters/variables-scss/src/helpers/__tests__/stringHelper.test.ts
  exporters/variables-scss/src/helpers/__tests__/tokenHelper.test.ts
  exporters/variables-scss/src/helpers/specialCaseHelper.ts
  exporters/variables-scss/src/helpers/stringHelper.ts
  exporters/variables-scss/src/helpers/tokenHelper.ts
  exporters/variables-scss/src/index.ts
  exporters/variables-scss/tsconfig.eslint.json
Labels: feature

#1614 Feat(web): Switch Pagination component to v3 design tokens #DS-1450
  packages/web/src/scss/components/Pagination/_Pagination.scss
  packages/web/src/scss/components/Pagination/_theme.scss
  packages/web/src/scss/components/Pagination/index.html
  packages/web/src/scss/components/index.scss
  tests/e2e/demo-components-compare.spec.ts
  tests/e2e/demo-components-compare.spec.ts-snapshots/pagination-chromium-linux.png
Labels: feature, run-visual-tests

#1627 Chore(exporter-variables-scss): Make package private
  exporters/variables-scss/package.json
Labels: maintenance

#1629 Fix(web-react): Export `Flex` component in components index file
  packages/web-react/src/components/index.ts
Labels: bug

#1554 Chore(repo): Cachable Yarn installs
  .github/workflows/build.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/component-analysis.yaml
  .github/workflows/e2e.yml
  .github/workflows/publish.yaml
  .github/workflows/test-web-twig.yaml
  .github/workflows/test.yaml
  Makefile
Labels: maintenance

#1609 Feat(web): Switch Radio component to v3 design tokens #DS-1447
  packages/web/src/scss/components/Radio/_Radio.scss
  packages/web/src/scss/components/Radio/_theme.scss
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/tools/_form-fields.scss
  tests/e2e/demo-components-compare.spec.ts
  tests/e2e/demo-components-compare.spec.ts-snapshots/radio-chromium-linux.png
Labels: feature, run-visual-tests

#1640 BREAKING CHANGE(web): Switch FieldGroup component to v3 design tokens and improve alignment #DS-1447
  packages/web/src/scss/components/FieldGroup/_FieldGroup.scss
  packages/web/src/scss/components/FieldGroup/_theme.scss
  packages/web/src/scss/components/index.scss
  tests/e2e/demo-components-compare.spec.ts
  tests/e2e/demo-components-compare.spec.ts-snapshots/fieldgroup-chromium-linux.png
Labels: feature, run-visual-tests

#1645 Feat(web-react): Use different resize observer hook
  packages/web-react/package.json
  packages/web-react/src/components/Collapse/__tests__/useResizeHeight.test.tsx
  packages/web-react/src/components/Collapse/useResizeHeight.ts
  yarn.lock
Labels: bug

#1650 Fix(web-react): Fix `underlined` prop default value name in Link
  packages/web-react/src/components/Link/Link.tsx
Labels: bug, run-visual-tests

#1652 Feat(variables-scss): Add export for shadows, gradients and typography
  .prettierignore
  exporters/variables-scss/generated/exporter.cjs
  exporters/variables-scss/src/config/fileConfig.ts
  exporters/variables-scss/src/formatters/cssFormatter.ts
  exporters/variables-scss/src/generators/__tests__/contentGenerator.test.ts
  exporters/variables-scss/src/generators/__tests__/fileGenerator.test.ts
  exporters/variables-scss/src/generators/contentGenerator.ts
  exporters/variables-scss/src/generators/cssGenerator.ts
  exporters/variables-scss/src/generators/cssObjectGenerator.ts
  exporters/variables-scss/src/generators/fileGenerator.ts
  exporters/variables-scss/src/helpers/__tests__/cssObjectHelper.test.ts
  exporters/variables-scss/src/helpers/__tests__/tokenHelper.test.ts
  exporters/variables-scss/src/helpers/cssObjectHelper.ts
  exporters/variables-scss/src/helpers/tokenHelper.ts
  exporters/variables-scss/tests/fixtures/formattedExample.scss
  exporters/variables-scss/tests/fixtures/mockedExampleTokens.ts
  exporters/variables-scss/tests/fixtures/unformattedExample.scss
Labels: feature

#1618 Feat(web): Introduce `Footer` composition #DS-1419
  packages/web/src/scss/components/Footer/README.md
  packages/web/src/scss/components/Footer/index.html
  tests/e2e/demo-components-compare.spec.ts-snapshots/footer-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
Labels: feature, run-visual-tests

#1649 Test(e2e): Enable visual testing of rest of the components
  tests/e2e/demo-components-compare.spec.ts
  tests/e2e/demo-components-compare.spec.ts-snapshots/accordion-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/dropdown-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/stack-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-truncate-chromium-linux.png
Labels: run-visual-tests
