Repository lmc-eu/spirit-design-system, pull requests merged in 2024-11, with the labels that each got.

#1746 Fix(exporter-tokens): Use css-variable-prefix token instead of token-prefix
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/helpers/findTokenPrefix.ts
  exporters/tokens/tests/fixtures/examplePrefixToken.ts
Labels: bug

#1739 Refactor(web): Abstract spacing tools to generate any custom properties cascade #DS-1546
  packages/web/src/scss/components/Flex/_Flex.scss
  packages/web/src/scss/components/Flex/_theme.scss
  packages/web/src/scss/components/Grid/_Grid.scss
  packages/web/src/scss/components/Grid/_GridItem.scss
  packages/web/src/scss/components/Grid/_theme.scss
  packages/web/src/scss/components/Grid/_tools.scss
  packages/web/src/scss/components/Grid/index.scss
  packages/web/src/scss/components/Stack/_Stack.scss
  packages/web/src/scss/components/Stack/_theme.scss
  packages/web/src/scss/tools/__tests__/_responsive-properties.test.scss
  packages/web/src/scss/tools/__tests__/_spacing.test.scss
  packages/web/src/scss/tools/_responsive-properties.scss
  packages/web/src/scss/tools/_spacing.scss
Labels: refactoring, run-visual-tests

#1741 Feat(exporter-tokens): Add mixin css-variables to theme colors #DS-1542
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/config/fileConfig.ts
  exporters/tokens/src/constants.ts
  exporters/tokens/src/formatters/stylesFormatter.ts
  exporters/tokens/src/generators/__fixtures__/mockedRootThemeFile.scss
  exporters/tokens/src/generators/__tests__/fileGenerator.test.ts
  exporters/tokens/src/generators/__tests__/mixinGenerator.test.ts
  exporters/tokens/src/generators/__tests__/stylesGenerator.test.ts
  exporters/tokens/src/generators/contentGenerator.ts
  exporters/tokens/src/generators/fileGenerator.ts
  exporters/tokens/src/generators/mixinGenerator.ts
  exporters/tokens/src/generators/stylesGenerator.ts
  exporters/tokens/src/generators/stylesObjectGenerator.ts
  exporters/tokens/src/helpers/objectHelper.ts
Labels: feature

#1748 Chore: Disable SASS deprecation warnings #DS-1514
  apps/demo/config/vite/app.ts
Labels: feature

#1743 Feat(exporter-tokens): Export only Theme tokens collection
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/constants.ts
  exporters/tokens/src/generators/fileGenerator.ts
  exporters/tokens/src/helpers/__tests__/colorHelper.test.ts
  exporters/tokens/src/helpers/colorHelper.ts
  exporters/tokens/tests/fixtures/exampleCollectionTokens.ts
Labels: feature

#1753 Docs(web-react): Fix typo in supported attributes in README.md
  packages/web-react/README.md
Labels: documentation

#1759 Test(e2e): Do not open reporter in Playwright after test
  playwright.config.ts
Labels: run-visual-tests

#1761 Fix(web-react): Failing type in PaginationLink #DS-1586
  packages/web-react/src/components/Pagination/PaginationLink.tsx
  packages/web-react/src/components/Pagination/UncontrolledPagination.tsx
  packages/web-react/src/components/Pagination/usePagination.tsx
Labels: bug

#1760 Feat(exporter-tokens): Add `color` prefix to css-variables mixin
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/generators/__tests__/fileGenerator.test.ts
  exporters/tokens/src/generators/__tests__/mixinGenerator.test.ts
  exporters/tokens/src/generators/contentGenerator.ts
  exporters/tokens/src/generators/mixinGenerator.ts
Labels: feature

#1766 Docs(icons): Transpile icons #DS-987
  packages/icons/README.md
Labels: feature

#1777 Fix(exporter-tokens): Use correct casing in collections filter
  exporters/tokens/exporter.json
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/helpers/colorHelper.ts
  exporters/tokens/tests/fixtures/exampleCollectionTokens.ts
Labels: bug

#1779 Chore(demo): Hide elements in Supernova component preview
  apps/demo/partials/layout/base.hbs
Labels: bug
