Repository lmc-eu/spirit-design-system, pull requests merged in 2024-03, with the labels that each got.

#1303 Feat(codmods): Introduce codemods package and first React codemod #DS-1142
  .github/CODEOWNERS
  packages/codemods/.eslintignore
  packages/codemods/README.md
  packages/codemods/config/jest.config.js
  packages/codemods/package.json
  packages/codemods/scripts/copyTransforms.js
  packages/codemods/src/bin/spirit-codemod.js
  packages/codemods/src/bin/spirit-codemods.js
  packages/codemods/src/cli.ts
  packages/codemods/src/helpers/index.ts
  packages/codemods/src/helpers/message.ts
  packages/codemods/src/helpers/path.ts
  packages/codemods/src/index.ts
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.input.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.output.tsx
  packages/codemods/src/transforms/v2/web-react/__tests__/button-text.test.ts
  packages/codemods/src/transforms/v2/web-react/button-text.ts
  packages/codemods/tsconfig.json
  yarn.lock
Labels: feature

#1310 Fix(codemods): FileuploaderAttachment codemods
  packages/codemods/CONTRIBUTING.md
  packages/codemods/README.md
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.input.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/button-text.output.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/fileuploader-prop-names.input.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/fileuploader-prop-names.output.tsx
  packages/codemods/src/transforms/v2/web-react/__tests__/fileuploader-prop-names.test.ts
  packages/codemods/src/transforms/v2/web-react/fileuploader-prop-names.ts
Labels: bug

#1301 Docs(web): List Deprecations in the web package #DS-1043
  DEPRECATIONS-v2.md
  DEPRECATIONS-v3.md
  packages/web/DEPRECATIONS-v2.md
Labels: documentation

#1314 Docs(readme): Add `codemods` to package table in root readme
  README.md
Labels: documentation

#1309 Docs(web-twig): List Deprecations in the web twig package #DS-1148
  packages/web-twig/DEPRECATIONS-v3.md
Labels: feature

#1313 Chore(GA): Send slack message on e2e test failure
  .github/workflows/e2e.yml
Labels: feature, run-visual-tests
