Repository lmc-eu/spirit-design-system, pull requests merged in 2024-04, with the labels that each got.

#1325 Feat(web): Print all design tokens as CSS root variables #DS-1200
  packages/web/src/scss/foundation/_tokens.scss
Labels: feature

#1329 Feat(web-react): Introduce Toast component #DS-1113
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Toast/README.md
  packages/web-react/src/components/Toast/Toast.tsx
  packages/web-react/src/components/Toast/ToastBar.tsx
  packages/web-react/src/components/Toast/ToastCloseButton.tsx
  packages/web-react/src/components/Toast/__tests__/Toast.test.tsx
  packages/web-react/src/components/Toast/__tests__/ToastBar.test.tsx
  packages/web-react/src/components/Toast/__tests__/useToastBarStyleProps.test.ts
  packages/web-react/src/components/Toast/__tests__/useToastIcon.test.tsx
  packages/web-react/src/components/Toast/__tests__/useToastStyleProps.test.ts
  packages/web-react/src/components/Toast/constants.ts
  packages/web-react/src/components/Toast/demo/ToastAlignment.tsx
  packages/web-react/src/components/Toast/demo/ToastColors.tsx
  packages/web-react/src/components/Toast/demo/ToastContentVariations.tsx
  packages/web-react/src/components/Toast/demo/index.tsx
  packages/web-react/src/components/Toast/index.html
  packages/web-react/src/components/Toast/index.ts
  packages/web-react/src/components/Toast/stories/Toast.stories.tsx
  packages/web-react/src/components/Toast/stories/ToastBar.stories.tsx
  packages/web-react/src/components/Toast/useToastBarStyleProps.ts
  packages/web-react/src/components/Toast/useToastIcon.tsx
  packages/web-react/src/components/Toast/useToastStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/hooks/useIconName.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/toast.ts
Labels: feature

#1328 Feat(web-react): Deprecate optional id prop in Collapse component #DS…
  packages/web-react/DEPRECATIONS-v2.md
  packages/web-react/src/components/Collapse/Collapse.tsx
  packages/web-react/src/components/Collapse/README.md
  packages/web-react/src/components/Collapse/UncontrolledCollapse.tsx
  packages/web-react/src/components/Collapse/useCollapseAriaProps.ts
  packages/web-react/src/components/Dropdown/README.md
  packages/web-react/src/types/collapse.ts
Labels: feature

#1336 Test(ci): Update E2E snapshot with missing TooltipModern
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: run-visual-tests

#1332 Fix(web): `Dropdown` can be placed in non-scrollable `Modal` #DS-939
  packages/web/src/scss/components/Modal/README.md
  packages/web/src/scss/components/Modal/_ModalBody.scss
  packages/web/src/scss/components/Modal/_ModalDialog.scss
  packages/web/src/scss/components/Modal/index.html
Labels: bug

#1340 Feat(codemods): Add codemod to update Tooltip and Dropdown non-flow p…
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/dropdown-tooltip-flow-placement.input.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/dropdown-tooltip-flow-placement.output.tsx
  packages/codemods/src/transforms/v2/web-react/__tests__/dropdown-tooltip-flow-placement.test.ts
  packages/codemods/src/transforms/v2/web-react/dropdown-tooltip-flow-placement.ts
  packages/web-react/DEPRECATIONS-v2.md
Labels: feature

#1338 Feat(codemods): Add codemods for Modal deprecations #DS-1184 #DS-1201…
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-isdockedonmobile-prop.input.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-isdockedonmobile-prop.output.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-isscrollable-prop.input.tsx
  packages/codemods/src/transforms/v2/web-react/__testfixtures__/modal-isscrollable-prop.output.tsx
  packages/codemods/src/transforms/v2/web-react/__tests__/modal-isdockedonmobile-prop.test.ts
  packages/codemods/src/transforms/v2/web-react/__tests__/modal-isscrollable-prop.test.ts
  packages/codemods/src/transforms/v2/web-react/modal-isdockedonmobile-prop.ts
  packages/codemods/src/transforms/v2/web-react/modal-isscrollable-prop.ts
  packages/web-react/DEPRECATIONS-v2.md
Labels: feature

#1343 Fix(web-twig): Don't render the `name` attribute of `Checkbox` when empty
  packages/web-twig/src/Resources/components/Checkbox/Checkbox.twig
  packages/web-twig/src/Resources/components/Checkbox/__tests__/__fixtures__/checkboxDefault.twig
  packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxDefaultPure.twig.snap.html
  packages/web-twig/src/Resources/components/Checkbox/__tests__/__snapshots__/checkboxItem.twig.snap.html
Labels: bug

#1267 Refactor(web-react): Move away from the `defaultProps`
  packages/web-react/src/components/Alert/Alert.tsx
  packages/web-react/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/web-react/src/components/Breadcrumbs/BreadcrumbsItem.tsx
  packages/web-react/src/components/Button/Button.tsx
  packages/web-react/src/components/ButtonLink/ButtonLink.tsx
  packages/web-react/src/components/Collapse/Collapse.tsx
  packages/web-react/src/components/Collapse/UncontrolledCollapse.tsx
  packages/web-react/src/components/Collapse/__tests__/UncontrolledCollapse.test.tsx
  packages/web-react/src/components/Dropdown/Dropdown.tsx
  packages/web-react/src/components/Field/HelperText.tsx
  packages/web-react/src/components/Field/ValidationText.tsx
  packages/web-react/src/components/Field/types.ts
  packages/web-react/src/components/Heading/Heading.tsx
  packages/web-react/src/components/Icon/Icon.tsx
  packages/web-react/src/components/Link/Link.tsx
  packages/web-react/src/components/Pill/Pill.tsx
  packages/web-react/src/components/Stack/Stack.tsx
  packages/web-react/src/components/Tag/Tag.tsx
  packages/web-react/src/components/Text/Text.tsx
  packages/web-react/src/components/VisuallyHidden/VisuallyHidden.tsx
  packages/web-react/src/types/collapse.ts
Labels: refactoring

#1248 Docs(ci): Introduce manual testing section with Netlify links tweak
  CONTRIBUTING.md
Labels: documentation

#1346 Feat(web-react): TooltipModern tooltip hover
  packages/web-react/src/components/Tooltip/README.md
  packages/web-react/src/components/Tooltip/TooltipModern.tsx
  packages/web-react/src/components/Tooltip/useFloating.ts
  packages/web-react/src/components/TooltipModern/demo/TooltipWithFloatingUI.tsx
  packages/web-react/src/components/TooltipModern/stories/TooltipModern.stories.tsx
  packages/web-react/src/types/tooltip.ts
Labels: feature

#1344 Feat(web-react): Introduce Uncontrollable Toast
  packages/web-react/src/components/Toast/README.md
  packages/web-react/src/components/Toast/ToastContext.tsx
  packages/web-react/src/components/Toast/UncontrolledToast.tsx
  packages/web-react/src/components/Toast/__tests__/UncontrolledToast.test.tsx
  packages/web-react/src/components/Toast/__tests__/useToast.test.ts
  packages/web-react/src/components/Toast/demo/UncontrolledToastDemo.tsx
  packages/web-react/src/components/Toast/index.ts
  packages/web-react/src/components/Toast/stories/UncontrolledToast.stories.tsx
  packages/web-react/src/components/Toast/useToast.ts
  packages/web-react/src/components/Toast/useToastIcon.ts
  packages/web-react/src/types/toast.ts
Labels: feature

#1353 Fix(web-react): Add backward compatibility for CJS when building to it
  packages/web-react/src/utils/htmlReactParser.ts
Labels: bug

#1355 Chore(demo): Correctly resolve alias to the icons in demos
  apps/demo/config/vite/app.ts
Labels: bug, run-visual-tests

#1350 Docs(web-twig): Document correctly when the goBackTitle prop is required in Breadcrumbs #DS-921
  packages/web-twig/DEPRECATIONS-v3.md
  packages/web-twig/src/Resources/components/Breadcrumbs/Breadcrumbs.twig
  packages/web-twig/src/Resources/components/Breadcrumbs/README.md
Labels: documentation

#1374 Chore(web-react): Fix missing `.js` extensions in ESM distribution
  packages/web-react/scripts/helpers.ts
Labels: maintenance

#1367 BREAKING CHANGE(web-react): Remove `Alert` danger icon deprecation
  packages/web-react/DEPRECATIONS-v2.md
  packages/web-react/src/components/Alert/Alert.tsx
  packages/web-react/src/components/Alert/README.md
  packages/web-react/src/components/Alert/__tests__/useAlertIcon.test.ts
  packages/web-react/src/hooks/useIcon.ts
Labels: BC

#1369 BREAKING CHANGE(web-react): Label prop is required for `TextField` component
  docs/migrations/web-react/MIGRATION-v2.md
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/types/textField.ts
Labels: BC

#1377 Chore(repo): Introduce Jakub Curda to the codeowners
  .github/CODEOWNERS
Labels: maintenance

#1381 BREAKING CHANGE(web-twig): Remove class and style from abstract Header components #DS-920
  packages/web-twig/DEPRECATIONS-v3.md
  packages/web-twig/src/Resources/components/Header/_abstracts/Button.twig
  packages/web-twig/src/Resources/components/Header/_abstracts/Element.twig
  packages/web-twig/src/Resources/components/Header/_abstracts/Link.twig
Labels: BC

#1385 BREAKING CHANGE(web): Remove Dropdown combined placement classes #DS-1139
  packages/web/DEPRECATIONS-v2.md
  packages/web/src/scss/components/Dropdown/README.md
  packages/web/src/scss/components/Dropdown/_Dropdown.scss
Labels: BC

#1388 Test: Update web-react homepage screenshot
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: bug

#1384 Chore(repo): Replace the unmaintaned auto-assign GitHub action
  .github/auto_assign.yml
  .github/workflows/pr-meta.yaml
Labels: maintenance
