Repository lmc-eu/spirit-design-system, pull requests merged in 2024-08, with the labels that each got.

#1567 Test: Update all screenshots of visual tests, because there is a new Inter font release
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-basic-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-closed-modals-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-disabled-backdrop-click-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-hidden-close-button-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-stacking-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-custom-height-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-dropdown-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-form-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-long-content-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-scrolling-inside-chromium-linux.png
  tests/e2e/components/demo-modal-compare.spec.ts-snapshots/modal-with-scrollview-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/accordion-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/alert-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/breadcrumbs-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/button-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/buttonlink-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/checkbox-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/collapse-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/container-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/divider-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/dropdown-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/fieldgroup-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/fileuploader-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/grid-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/header-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/heading-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/icon-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/item-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/link-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/modal-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/pagination-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/pill-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/radio-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/scrollview-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/select-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/spinner-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/stack-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/tabs-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/tag-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/text-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/textarea-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/textfield-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/toast-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/tooltip-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-actionlayout-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-avatar-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-emptystate-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-partnerlogo-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-productlogo-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-section-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-slider-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-toggle-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-truncate-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: bug, run-visual-tests

#1569 Feat(design-tokens): Update JS Design Tokens manually #DS-1394
  packages/design-tokens/src/js/generated/colors.ts
  packages/design-tokens/src/js/generated/gradients.ts
  packages/design-tokens/src/js/generated/shadows.ts
  packages/design-tokens/src/js/generated/typography.ts
Labels: feature

#1568 Fix(web-twig): Use `docker compose` instead of removed `docker-compose`
  packages/web-twig/Makefile
Labels: bug

#1559 Feat(web): Remove `Accordion` Header active background change
  packages/web/src/scss/components/Accordion/_Accordion.scss
Labels: feature

#1570 Refactor(web-react): Use Spacing hook in Grid component #DS-1425
  packages/web-react/src/components/Grid/useGridStyleProps.ts
  packages/web-react/src/constants/direction.ts
  packages/web-react/src/hooks/__tests__/useSpacingStyles.test.ts
  packages/web-react/src/hooks/useSpacingStyle.ts
Labels: refactoring

#1571 Feat(web-react): Improve Docs components - add StyleProps, remove def…
  packages/web-react/docs/DocsBox.tsx
  packages/web-react/docs/DocsSections.tsx
  packages/web-react/docs/DocsStack.tsx
Labels: feature

#1576 Introduce `Flex` layout component #DS-1415
  packages/web/src/scss/components/Flex/README.md
  packages/web/src/scss/components/Flex/_Flex.scss
  packages/web/src/scss/components/Flex/_theme.scss
  packages/web/src/scss/components/Flex/index.html
  packages/web/src/scss/components/Flex/index.scss
  packages/web/src/scss/components/Grid/_Grid.scss
  packages/web/src/scss/components/Grid/index.html
  packages/web/src/scss/components/Stack/_Stack.scss
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/settings/_dictionaries.scss
  packages/web/src/scss/tools/__tests__/_alignment.test.scss
  packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
  packages/web/src/scss/tools/__tests__/_reset.test.scss
  packages/web/src/scss/tools/__tests__/_spacing.test.scss
  packages/web/src/scss/tools/_alignment.scss
  packages/web/src/scss/tools/_dictionaries.scss
  packages/web/src/scss/tools/_reset.scss
  packages/web/src/scss/tools/_spacing.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/flex-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
Labels: feature, run-visual-tests

#1578 Feat: Example NextJS app with app router #DS-1393
  .eslintrc.js
  examples/next-with-app-router/.eslintignore
  examples/next-with-app-router/.eslintrc.js
  examples/next-with-app-router/.gitignore
  examples/next-with-app-router/README.md
  examples/next-with-app-router/next.config.mjs
  examples/next-with-app-router/package.json
  examples/next-with-app-router/src/app/favicon.ico
  examples/next-with-app-router/src/app/globals.scss
  examples/next-with-app-router/src/app/layout.tsx
  examples/next-with-app-router/src/app/page.tsx
  examples/next-with-app-router/tsconfig.eslint.json
  examples/next-with-app-router/tsconfig.json
  package.json
  yarn.lock
Labels: feature

#1577 Feat: Example NextJS app with pages router #DS-1393
  .prettierignore
  examples/next-with-pages-router/.eslintignore
  examples/next-with-pages-router/.eslintrc.js
  examples/next-with-pages-router/.gitignore
  examples/next-with-pages-router/README.md
  examples/next-with-pages-router/next.config.mjs
  examples/next-with-pages-router/package.json
  examples/next-with-pages-router/public/favicon.ico
  examples/next-with-pages-router/src/pages/_app.tsx
  examples/next-with-pages-router/src/pages/_document.tsx
  examples/next-with-pages-router/src/pages/index.tsx
  examples/next-with-pages-router/src/styles/globals.scss
  examples/next-with-pages-router/tsconfig.eslint.json
  examples/next-with-pages-router/tsconfig.json
  yarn.lock
Labels: feature

#1581 Test: Temporarily disable all visual tests and SCSS loading
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/foundation/index.scss
  packages/web/src/scss/helpers/index.scss
  packages/web/src/scss/utilities/index.scss
  packages/web/tests/scss.test-disabled.ts
  tests/e2e/components/demo-modal-compare.spec.ts
  tests/e2e/demo-components-compare.spec.ts
  tests/e2e/demo-homepages.spec.ts
Labels: bug

#1603 BREAKING CHANGE(web): Set default color to body and each theme selector
  packages/web/src/scss/foundation/_typography.scss
Labels: BC

#1602 Feat(web): Switch PartnerLogo component to v3 design tokens #DS-1450
  packages/web/src/scss/components/UNSTABLE_PartnerLogo/_UNSTABLE_PartnerLogo.scss
  packages/web/src/scss/components/UNSTABLE_PartnerLogo/_theme.scss
  packages/web/src/scss/components/UNSTABLE_PartnerLogo/_tools.scss
  packages/web/src/scss/components/index.scss
  packages/web/src/scss/tools/__tests__/_string.test.scss
  packages/web/src/scss/tools/_dictionaries.scss
  packages/web/src/scss/tools/_string.scss
  tests/e2e/demo-components-compare.spec.ts
Labels: feature, run-visual-tests

#1599 Feat(web): Switch Flex component to v3 design tokens #DS-1444
  packages/web/src/scss/components/Flex/_theme.scss
  packages/web/src/scss/components/Flex/index.html
  packages/web/src/scss/components/index.scss
  tests/e2e/demo-components-compare.spec.ts
Labels: feature, run-visual-tests
