Repository lmc-eu/spirit-design-system, pull requests merged in 2025-05, with the labels that each got.

#2051 Docs(web): Custom Sass functions and mixins are for internal usage only #DS-1883
  packages/web/README.md
Labels: documentation

#2045 Feat(design-tokens): Change form helper text, selected content basic and selected header item colors
  packages/design-tokens/src/scss/themes/theme-light-default/_colors.scss
  packages/design-tokens/src/scss/themes/theme-light-on-brand/_colors.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/checkbox-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/fieldgroup-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/fileuploader-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/item-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/radio-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/segmentedcontrol-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/select-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/slider-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/textarea-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/textfield-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/toast-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/toggle-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-actionlayout-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-emptystate-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-section-chromium-linux.png
  tests/e2e/demo-components-compare.spec.ts-snapshots/unstable-truncate-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: feature, run-visual-tests

#2048 Refactor(web): Refactor component size variants to use custom properties for typography #DS-1689
  packages/web/src/scss/components/Alert/_Alert.scss
  packages/web/src/scss/components/Alert/_theme.scss
  packages/web/src/scss/components/Avatar/_Avatar.scss
  packages/web/src/scss/components/Avatar/_theme.scss
  packages/web/src/scss/components/Button/_Button.scss
  packages/web/src/scss/components/Button/_theme.scss
  packages/web/src/scss/components/Card/_CardMedia.scss
  packages/web/src/scss/components/Card/_theme.scss
  packages/web/src/scss/components/Checkbox/_Checkbox.scss
  packages/web/src/scss/components/Container/_Container.scss
  packages/web/src/scss/components/Container/_theme.scss
  packages/web/src/scss/components/FileUploader/_FileUploaderAttachment.scss
  packages/web/src/scss/components/FileUploader/_FileUploaderInput.scss
  packages/web/src/scss/components/PartnerLogo/_PartnerLogo.scss
  packages/web/src/scss/components/PartnerLogo/_theme.scss
  packages/web/src/scss/components/Pill/_Pill.scss
  packages/web/src/scss/components/Pill/_theme.scss
  packages/web/src/scss/components/Radio/_Radio.scss
  packages/web/src/scss/components/Radio/_theme.scss
  packages/web/src/scss/components/Select/_Select.scss
  packages/web/src/scss/components/Tag/_Tag.scss
  packages/web/src/scss/components/Tag/_theme.scss
  packages/web/src/scss/components/TextArea/_TextArea.scss
  packages/web/src/scss/components/TextArea/_theme.scss
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/Toast/_ToastBar.scss
  packages/web/src/scss/components/Toast/_theme.scss
  packages/web/src/scss/components/Toggle/_Toggle.scss
  packages/web/src/scss/settings/_form-fields.scss
  packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
  packages/web/src/scss/tools/__tests__/_form-fields.test.scss
  packages/web/src/scss/tools/__tests__/_typography.test.scss
  packages/web/src/scss/tools/_dictionaries.scss
  packages/web/src/scss/tools/_form-fields.scss
  packages/web/src/scss/tools/_typography.scss
Labels: refactoring, run-visual-tests

#2054 Refactor(web-react): Refactor breakpoint types #DS-1701
  packages/web-react/src/components/Modal/demo/ModalScrollingLongContent.tsx
  packages/web-react/src/components/Section/useSectionSizeProps.ts
  packages/web-react/src/types/shared/tokens.ts
Labels: refactoring, run-visual-tests

#2058 Refactor(web): Hover background for a moment overlaps the active bg #DS-1902
  packages/web/src/scss/components/SegmentedControl/_SegmentedControlItem.scss
  packages/web/src/scss/components/SegmentedControl/_theme.scss
Labels: refactoring, run-visual-tests

#2066 Fix(web-react): Export `SegmentedControl` from component's barrel file
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/index.ts
Labels: bug

#2067 Fix(web): Do not export `border-focus` as utility class
  packages/web/src/scss/settings/_utilities.scss
Labels: bug

#2076 Feat(web-react): Introduce `size` and `iconBoxSize` property on `DrawerCloseButton` #DS-1870
  packages/web-react/src/components/Drawer/DrawerCloseButton.tsx
  packages/web-react/src/components/Drawer/README.md
  packages/web-react/src/components/Drawer/__tests__/DrawerCloseButton.test.tsx
  packages/web-react/src/components/Drawer/stories/DrawerCloseButton.stories.tsx
  packages/web-react/src/types/drawer.ts
Labels: feature, run-visual-tests

#2075 Feat(exporter-tokens): Introduce export of color token maps #DS-1880
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/generators/__tests__/fileGenerator.test.ts
  exporters/tokens/src/generators/fileGenerator.ts
  exporters/tokens/src/generators/stylesGenerator.ts
  exporters/tokens/src/generators/stylesObjectGenerator.ts
  exporters/tokens/src/helpers/__tests__/objectHelper.test.ts
  exporters/tokens/src/helpers/objectHelper.ts
Labels: feature

#2080 Fix(web): Check if utility values list is not empty before generating
  packages/web/src/scss/tools/__tests__/_utilities.test.scss
  packages/web/src/scss/tools/_utilities.scss
Labels: bug, run-visual-tests
