Repository lmc-eu/spirit-design-system, pull requests merged in 2025-03, with the labels that each got.

#1961 Feat(web-react): HelperText and ValidationText use UNSAFE_className
  packages/web-react/src/components/Checkbox/Checkbox.tsx
  packages/web-react/src/components/Field/HelperText.tsx
  packages/web-react/src/components/Field/README.md
  packages/web-react/src/components/Field/ValidationText.tsx
  packages/web-react/src/components/Field/__tests__/HelperText.test.tsx
  packages/web-react/src/components/Field/__tests__/ValidationText.test.tsx
  packages/web-react/src/components/Field/types.ts
  packages/web-react/src/components/FieldGroup/FieldGroup.tsx
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
  packages/web-react/src/components/Item/Item.tsx
  packages/web-react/src/components/Radio/Radio.tsx
  packages/web-react/src/components/Select/Select.tsx
  packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
  packages/web-react/src/components/UNSTABLE_Slider/UNSTABLE_Slider.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/UNSTABLE_Toggle.tsx
Labels: feature, run-visual-tests

#1971 Fix(web-react): Forgotten hasValidationIcon prop on DOM element
  packages/web-react/src/components/Checkbox/Checkbox.tsx
  packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
  packages/web-react/src/components/UNSTABLE_Slider/UNSTABLE_Slider.tsx
Labels: bug, run-visual-tests

#1964 Fix(web): Prevent Skeleton SCSS from failing if tokens are not found #DS-1692
  packages/web/DEPRECATIONS.md
  packages/web/src/scss/components/Skeleton/README.md
  packages/web/src/scss/components/Skeleton/_Skeleton.scss
  packages/web/src/scss/components/Skeleton/_theme.scss
  packages/web/src/scss/tools/_tokens.scss
Labels: bug, run-visual-tests

#1970 Fix(web-react): Forgotten elementType in useStyleProps hook
  packages/web-react/src/components/Accordion/Accordion.tsx
  packages/web-react/src/components/Collapse/Collapse.tsx
  packages/web-react/src/components/Stack/Stack.tsx
  packages/web-react/src/components/Tabs/TabLink.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/UNSTABLE_Truncate.tsx
  packages/web-react/src/components/VisuallyHidden/VisuallyHidden.tsx
Labels: bug

#1979 Refactor(demo): Use path aliases for packages in Storybook
  apps/storybook/decorators/IconGlobalDecorator.tsx
  apps/storybook/main.ts
Labels: maintenance

#1966 Docs(web-react): Unify Icons demo style
  apps/demo/partials/web-react/tabs.hbs
  packages/web-react/src/icons/demo/icons.tsx
Labels: documentation, run-visual-tests

#1983 Chore(repo): Introduce @dlouhak and @vmilersky between Spirit Design System code owners
  .github/CODEOWNERS
Labels: maintenance

#1980 Docs(repo): Use lighter colors in demo header
  apps/demo/partials/cover.hbs
  apps/demo/partials/header.hbs
  apps/demo/partials/web/assets/spiritLogo.hbs
  apps/demo/partials/web/assets/spiritLogoInverted.hbs
  apps/web-twig-demo/templates/assets/spiritLogo.svg.twig
  apps/web-twig-demo/templates/assets/spiritLogoInverted.html.twig
  apps/web-twig-demo/templates/partials/cover.html.twig
  apps/web-twig-demo/templates/partials/header.html.twig
  index.html
  packages/demo/scss/index.scss
  tests/e2e/demo-homepages.spec.ts-snapshots/web-chromium-linux.png
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: documentation, run-visual-tests

#1986 Fix(web-twig): Remove additional Container demo causing failing Twig e2e tests
  packages/web-twig/src/Resources/components/Container/stories/ContainerTextAlignment.twig
Labels: bug, run-visual-tests

#1984 Chore(web-react): Partial revert of `Chore(web-react): Building with TypeScript v5`
  packages/web-react/config/tsconfig.prod.json
Labels: maintenance

#1982 Fix(web-react): Pass href to Nextjs Link in NavigationAction #DS-1714
  packages/web-react/src/components/Navigation/__tests__/useNavigationActionProps.test.ts
  packages/web-react/src/components/Navigation/useNavigationActionProps.ts
Labels: bug

#1987 Feat(web-react): Allow color prop in DrawerCloseButton #DS-1755
  packages/web-react/src/components/Button/__tests__/Button.test.tsx
  packages/web-react/src/components/ButtonLink/__tests__/ButtonLink.test.tsx
  packages/web-react/src/components/Drawer/DrawerCloseButton.tsx
  packages/web-react/src/components/Drawer/README.md
  packages/web-react/src/components/Drawer/__tests__/DrawerCloseButton.test.tsx
  packages/web-react/src/components/Drawer/stories/DrawerCloseButton.stories.tsx
  packages/web-react/src/types/drawer.ts
  packages/web-react/tests/providerTests/dictionaryPropsTest.tsx
Labels: feature, run-visual-tests

#1997 Fix: Password field button role switch has valid attribute aria-checked instead of aria-pressed
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldPasswordToggle.twig.snap.html
  packages/web-twig/src/Resources/components/TextFieldBase/TextFieldBase.twig
  packages/web/src/js/Password.ts
  packages/web/src/js/__tests__/Password.test.ts
  packages/web/src/scss/components/TextField/README.md
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/index.html
Labels: bug

#1998 Feat(web-react): Add currentId to `Tab` onSelectionChange callback
  packages/web-react/src/components/Tabs/README.md
  packages/web-react/src/components/Tabs/TabContext.tsx
  packages/web-react/src/components/Tabs/TabItem.tsx
  packages/web-react/src/components/Tabs/__tests__/TabItem.test.tsx
  packages/web-react/src/types/tabs.ts
Labels: feature, run-visual-tests

#1999 Fix(web-react): Do not pass the `placement` prop to the DOM of the TooltipPopover #DS-1790
  packages/web-react/src/components/Tooltip/TooltipPopover.tsx
Labels: bug, run-visual-tests

#1996 Refactor(scripts): Migrate post-changelog script to TypeScript
  scripts/post-changelog/README.md
  scripts/post-changelog/package.json
  scripts/post-changelog/post-changelog.ts
  scripts/post-changelog/tsconfig.json
  yarn.lock
Labels: refactoring
