Repository lmc-eu/spirit-design-system, pull requests merged in 2025-04, with the labels that each got.

#1945 Test: Make Playwright UI mode work with Docker environment
  bin/make/e2e.sh
  package.json
Labels: feature

#2012 Fix(examples): Add postcss configuration to suppress flexbox warning #DS-1778
  examples/next-with-app-router/README.md
  examples/next-with-app-router/postcss.config.json
Labels: bug

#2017 Docs(web): Warn when `border-style` is set without border color and width #DS-1799
  packages/web/src/scss/components/Box/README.md
Labels: documentation

#2010 Chore(ci): Publish Supernova.io docs only if tags were created
  .github/actions/has-tags/action.yaml
  .github/workflows/publish.yaml
  .github/workflows/supernova.yaml
Labels: maintenance

#2018 Chore(ci): Repository must be cloned first to access the composite action
  .github/actions/has-tags/action.yaml
  .github/workflows/publish.yaml
  .github/workflows/supernova.yaml
Labels: maintenance

#2019 Chore(ci): Add required missing property `shell` to composite action
  .github/actions/has-tags/action.yaml
Labels: maintenance

#2015 Fix(web): SegmentedControl isn't occasionally initialised #DS-1822
  packages/web/src/js/SegmentedControl.ts
  packages/web/src/js/__tests__/SegmentedControl.test.ts
  packages/web/src/scss/components/SegmentedControl/_SegmentedControlItem.scss
Labels: bug, run-visual-tests

#2005 Refactor(web, web-react): Introduce Shape Variant dictionary and use it for `NavigationAction`
  docs/DICTIONARIES.md
  packages/web-react/src/components/Navigation/NavigationAction.tsx
  packages/web-react/src/components/Navigation/README.md
  packages/web-react/src/components/Navigation/__tests__/useNavigationStyleProps.test.ts
  packages/web-react/src/components/Navigation/constants.ts
  packages/web-react/src/components/Navigation/stories/NavigationAction.stories.tsx
  packages/web-react/src/components/Navigation/useNavigationStyleProps.ts
  packages/web-react/src/components/UNSTABLE_Header/demo/HeaderWithNavigation/MainNavigation.tsx
  packages/web-react/src/components/UNSTABLE_Header/demo/HeaderWithPillNavigation.tsx
  packages/web-react/src/constants/dictionaries.ts
  packages/web-react/src/types/navigation.ts
  packages/web-react/src/types/shared/dictionaries.ts
  packages/web/src/scss/components/Navigation/_NavigationAction.scss
  packages/web/src/scss/components/Navigation/_theme.scss
  packages/web/src/scss/components/SegmentedControl/_SegmentedControl.scss
  packages/web/src/scss/components/SegmentedControl/_SegmentedControlItem.scss
  packages/web/src/scss/settings/_dictionaries.scss
  packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
  packages/web/src/scss/tools/_dictionaries.scss
Labels: refactoring, run-visual-tests

#2027 Chore(ci): Fetch tags when running version workflow
  .github/workflows/version.yaml
Labels: maintenance

#2028 Chore(ci): Version dry run also on private packages
  .github/workflows/version.yaml
Labels: maintenance

#2029 Chore(ci): Confirm version push manually
  .github/workflows/version.yaml
Labels: maintenance

#2030 Chore/version workflow
  .github/workflows/version.yaml
Labels: maintenance

#2031 Chore(ci): Use PAT token for version push
  .github/workflows/version.yaml
Labels: maintenance

#2023 Feat(web-react,web-twig): Remove aria-selected from Item #DS-1851
  packages/web-react/src/components/Item/Item.tsx
  packages/web-twig/src/Resources/components/Item/Item.twig
  packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemDisabled.twig.snap.html
  packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemHelperText.twig.snap.html
  packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemIcon.twig.snap.html
  packages/web-twig/src/Resources/components/Item/__tests__/__snapshots__/itemSelected.twig.snap.html
Labels: feature, run-visual-tests

#2042 Docs(form-validations,web,web-react,web-twig): Drawer opening button set as symmetrical
  apps/demo/partials/header.hbs
  apps/web-twig-demo/templates/partials/header.html.twig
Labels: bug, documentation

#2020 Feat(web,web-react,web-twig): Add tabindex to ScrollView #DS-1851
  packages/web-react/src/components/ScrollView/ScrollView.tsx
  packages/web-react/src/components/ScrollView/__tests__/ScrollView.test.tsx
  packages/web-twig/src/Resources/components/ScrollView/README.md
  packages/web-twig/src/Resources/components/ScrollView/ScrollView.twig
  packages/web-twig/src/Resources/components/ScrollView/__tests__/__snapshots__/scrollViewDefault.twig.snap.html
  packages/web/src/scss/components/ScrollView/README.md
  packages/web/src/scss/components/ScrollView/index.html
Labels: feature, run-visual-tests

#2022 Feat(web): Set correct aria in SegmentedControl with Tooltip #DS-1851
  packages/web/src/scss/components/SegmentedControl/README.md
  packages/web/src/scss/components/SegmentedControl/index.html
Labels: feature, run-visual-tests

#2025 Chore(web,web-react): Improve demos to be accessibility compatible #DS-1851
  apps/demo/partials/cover.hbs
  apps/demo/partials/web-react/layout/default.hbs
  apps/demo/partials/web-react/tabs.hbs
  apps/demo/partials/web/layout/default.hbs
  apps/demo/partials/web/tabs.hbs
  apps/web-twig-demo/templates/layout/default.html.twig
  apps/web-twig-demo/templates/partials/cover.html.twig
  packages/web-react/src/components/Button/demo/ButtonDemoFactory.tsx
  packages/web-react/src/components/ButtonLink/demo/ButtonLinkDemoFactory.tsx
  packages/web-react/src/components/FileUploader/demo/FileUploaderAttachment.tsx
  packages/web-react/src/components/FileUploader/demo/FileUploaderFluidWidth.tsx
  packages/web-react/src/components/FileUploader/demo/FileUploaderInputWithAttachment.tsx
  packages/web/src/scss/components/Avatar/index.html
  packages/web/src/scss/components/Card/index.html
  packages/web/src/scss/components/FileUploader/index.html
  packages/web/src/scss/components/Footer/index.html
Labels: feature, run-visual-tests

#2021 Feat(web-react): Remove aria-describedby from form elements if no helper or validation #DS-1851
  packages/web-react/src/components/Checkbox/Checkbox.tsx
  packages/web-react/src/components/Field/HelperText.tsx
  packages/web-react/src/components/FieldGroup/FieldGroup.tsx
  packages/web-react/src/components/FileUploader/FileUploaderInput.tsx
  packages/web-react/src/components/Radio/Radio.tsx
  packages/web-react/src/components/Select/Select.tsx
  packages/web-react/src/components/Slider/Slider.tsx
  packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
  packages/web-react/src/components/Toggle/Toggle.tsx
  packages/web-react/src/hooks/__tests__/useAriaDescribedBy.test.ts
  packages/web-react/src/hooks/index.ts
  packages/web-react/src/hooks/useAriaDescribedBy.ts
Labels: feature, run-visual-tests

#2024 Fix(web,web-react,web-twig): Remove aria-selected and role from TabLink #DS-1851
  packages/web-react/src/components/Tabs/README.md
  packages/web-react/src/components/Tabs/TabLink.tsx
  packages/web-twig/src/Resources/components/Tabs/README.md
  packages/web-twig/src/Resources/components/Tabs/TabLink.twig
  packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacing.twig.snap.html
  packages/web-twig/src/Resources/components/Tabs/__tests__/__snapshots__/tabsWithCustomSpacingForEachBreakpoint.twig.snap.html
  packages/web/src/scss/components/Tabs/README.md
Labels: bug, run-visual-tests

#2033 Fix(web, web-react): Make individual items in vertical `Flex` reflect `alignmentX` #DS-1820
  packages/web-react/src/components/Flex/demo/FlexHorizontalLayoutHorizontalAlignment.tsx
  packages/web-react/src/components/Flex/demo/FlexResponsiveAlignment.tsx
  packages/web-react/src/components/Flex/demo/FlexVerticalLayoutHorizontalAlignment.tsx
  packages/web-react/src/components/Flex/demo/index.tsx
  packages/web/src/scss/components/Flex/_Flex.scss
  packages/web/src/scss/components/Flex/index.html
  packages/web/src/scss/components/Grid/_Grid.scss
  packages/web/src/scss/tools/__tests__/_dictionaries.test.scss
  packages/web/src/scss/tools/_dictionaries.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/flex-chromium-linux.png
Labels: bug, run-visual-tests

#2044 Fix(web): Update `Drawer` width according to the latest design
  packages/web/src/scss/components/Drawer/_theme.scss
  tests/e2e/components/demo-drawer-compare.spec.ts
  tests/e2e/components/demo-drawer-compare.spec.ts-snapshots/drawer-left-backdrop-click-chromium-linux.png
  tests/e2e/components/demo-drawer-compare.spec.ts-snapshots/drawer-right-backdrop-click--chromium-linux.png
  tests/e2e/components/demo-unstable-header-compare.spec.ts-snapshots/unstable-header-with-navigation-and-nested-items-chromium-linux.png
  tests/e2e/components/demo-unstable-header-compare.spec.ts-snapshots/unstable-header-with-navigation-chromium-linux.png
  tests/e2e/components/demo-unstable-header-compare.spec.ts-snapshots/unstable-header-with-pill-navigation-chromium-linux.png
Labels: bug, run-visual-tests

#2037 Feat(exporter-tokens): Introduce configuration for typography #DS-1713
  exporters/tokens/README.md
  exporters/tokens/config.json
  exporters/tokens/config.ts
  exporters/tokens/exporter.json
  exporters/tokens/generated/exporter.cjs
  exporters/tokens/src/constants.ts
  exporters/tokens/src/generators/__tests__/contentGenerator.test.ts
  exporters/tokens/src/generators/__tests__/fileGenerator.test.ts
  exporters/tokens/src/generators/__tests__/mixinGenerator.test.ts
  exporters/tokens/src/generators/__tests__/stylesGenerator.test.ts
  exporters/tokens/src/generators/__tests__/stylesObjectGenerator.test.ts
  exporters/tokens/src/helpers/__tests__/tokenHelper.test.ts
  exporters/tokens/src/helpers/__tests__/tokenHelperWithConfiguration.ts
  exporters/tokens/src/helpers/tokenHelper.ts
  exporters/tokens/src/index.ts
  exporters/tokens/tests/fixtures/exampleTypographyTokens.ts
  exporters/tokens/tests/fixtures/sampleConfiguration.ts
Labels: feature

#2049 Fix(web): Prevent password toggle icon from expanding the `TextField`
  packages/web/src/scss/components/TextField/_TextField.scss
  packages/web/src/scss/components/TextField/_theme.scss
  tests/e2e/demo-components-compare.spec.ts-snapshots/textfield-chromium-linux.png
Labels: bug, run-visual-tests

#2050 Feat(web): Introduce utility classes for new accent colors #DS-1773
  packages/web/src/scss/settings/_utilities.scss
  packages/web/src/scss/tools/__tests__/_utilities.test.scss
  packages/web/src/scss/tools/_utilities.scss
Labels: feature, run-visual-tests
