Repository lmc-eu/spirit-design-system, pull requests merged in 2025-08, with the labels that each got.

#2140 Fix(web-react): Set default height of opened Collapse to undefined #DS-2048
  packages/web-react/src/components/Collapse/useResizeHeight.ts
Labels: bug

#2144 Feat(web-twig): Allow rel attribute in Link & ButtonLink
  packages/web-twig/src/Resources/components/ButtonLink/ButtonLink.twig
  packages/web-twig/src/Resources/components/ButtonLink/README.md
  packages/web-twig/src/Resources/components/Link/Link.twig
  packages/web-twig/src/Resources/components/Link/README.md
Labels: feature

#2143 Docs(exporter-tokens): Devices Tokens section and clarify Theme Tokens #DS-2103
  exporters/tokens/README.md
Labels: documentation

#2142 Test(icons): Add unit tests for icon scripts #DS-1750
  packages/icons/jest.config.ts
  packages/icons/package.json
  packages/icons/scripts/__tests__/buildConstants.test.ts
  packages/icons/scripts/__tests__/buildSvg.test.ts
  packages/icons/scripts/__tests__/prepareSvgReact.test.ts
  packages/icons/scripts/__tests__/shared.test.ts
  packages/icons/scripts/buildConstants.js
  packages/icons/scripts/buildSvg.js
  packages/icons/scripts/prepareSvgReact.js
  yarn.lock
Labels: run-visual-tests
