Repository lmc-eu/spirit-design-system, pull requests merged in 2025-01, with the labels that each got.

#1841 Chore: Add E2E workflow Slack message @channel tag
  .github/workflows/e2e.yml
Labels: run-visual-tests

#1838 Feat(web): Introduce `button-unstyled` helper
  packages/web/src/scss/helpers/buttons/_buttons.scss
  packages/web/src/scss/helpers/buttons/index.html
  packages/web/src/scss/helpers/buttons/index.scss
  packages/web/src/scss/helpers/index.scss
Labels: feature

#1848 Feat(web-react): Add prefixed utility class #DS-1618
  packages/web-react/src/components/Box/__tests__/Box.test.tsx
  packages/web-react/src/components/Box/useBoxStyleProps.ts
  packages/web-react/src/components/Footer/__tests__/Footer.test.tsx
  packages/web-react/src/components/Footer/useFooterStyleProps.ts
  packages/web-react/src/components/Item/__tests__/Item.test.tsx
  packages/web-react/src/components/TextFieldBase/__tests__/TextFieldBase.test.tsx
  packages/web-react/src/components/Tooltip/__tests__/Tooltip.test.tsx
  packages/web-react/src/components/UNSTABLE_Slider/__tests__/UNSTABLE_Slider.test.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/UNSTABLE_Truncate.tsx
  packages/web-react/src/components/UNSTABLE_Truncate/useTruncateStyleProps.ts
Labels: feature, run-visual-tests

#1856 Fix(web, web-react, e2e): Flex reverse dictionary change
  docs/DICTIONARIES.md
  packages/web-react/src/components/Flex/README.md
  packages/web-react/src/components/Flex/demo/FlexHorizontalReversedLayout.tsx
  packages/web-react/src/components/Flex/demo/index.tsx
  packages/web-react/src/constants/direction.ts
  packages/web/src/scss/components/Flex/_Flex.scss
  packages/web/src/scss/components/Flex/index.html
  tests/e2e/demo-components-compare.spec.ts-snapshots/flex-chromium-linux.png
Labels: run-visual-tests

#1858 Docs(repo): Generalization of the deprecations lists
  DEPRECATIONS-v2.md
  DEPRECATIONS-v3.md
  DEPRECATIONS.md
Labels: documentation

#1792 Feat(lts-schedule): Introduce fork of the Node.js LTS schedule script
  .commitlintrc.mjs
  docs/contribution/release-schedule.md
  package.json
  scripts/lts-schedule/README.md
  scripts/lts-schedule/bin/lts.js
  scripts/lts-schedule/lib/index.js
  scripts/lts-schedule/lts.json
  scripts/lts-schedule/package.json
  static/release-schedule.svg
  yarn.lock
Labels: feature

#1862 Feat(web-react): ReactNode type for labels #DS-1632
  packages/web-react/src/components/Checkbox/README.md
  packages/web-react/src/components/Checkbox/__tests__/Checkbox.test.tsx
  packages/web-react/src/components/Field/README.md
  packages/web-react/src/components/Field/__tests__/HelperText.test.tsx
  packages/web-react/src/components/Field/__tests__/ValidationText.test.tsx
  packages/web-react/src/components/FieldGroup/README.md
  packages/web-react/src/components/FieldGroup/__tests__/FieldGroup.test.tsx
  packages/web-react/src/components/FileUploader/README.md
  packages/web-react/src/components/FileUploader/__tests__/FileUploaderInput.test.tsx
  packages/web-react/src/components/Radio/README.md
  packages/web-react/src/components/Radio/__tests__/Radio.test.tsx
  packages/web-react/src/components/Select/README.md
  packages/web-react/src/components/Select/__tests__/Select.test.tsx
  packages/web-react/src/components/TextArea/README.md
  packages/web-react/src/components/TextArea/__tests__/TextArea.test.tsx
  packages/web-react/src/components/TextField/README.md
  packages/web-react/src/components/TextField/__tests__/TextField.test.tsx
  packages/web-react/src/components/TextFieldBase/TextFieldBase.tsx
  packages/web-react/src/components/UNSTABLE_Slider/README.md
  packages/web-react/src/components/UNSTABLE_Slider/__tests__/UNSTABLE_Slider.test.tsx
  packages/web-react/src/components/UNSTABLE_Toggle/README.md
  packages/web-react/src/components/UNSTABLE_Toggle/__tests__/UNSTABLE_Toggle.test.tsx
  packages/web-react/src/types/checkbox.ts
  packages/web-react/src/types/fieldGroup.ts
  packages/web-react/src/types/fileUploader.ts
  packages/web-react/src/types/radio.ts
  packages/web-react/src/types/select.ts
  packages/web-react/src/types/shared/element.ts
  packages/web-react/src/types/shared/inputs.ts
  packages/web-react/src/types/slider.ts
  packages/web-react/src/types/textArea.ts
  packages/web-react/src/types/textField.ts
  packages/web-react/src/types/textFieldBase.ts
  packages/web-react/src/types/toggle.ts
Labels: feature, run-visual-tests

#1874 Chore(scripts): Make the scripts packages private
  scripts/lts-schedule/package.json
  scripts/post-changelog/package.json
Labels: maintenance

#1880 Docs(repo): Add corepack steps to quick setup of the repository
  README.md
Labels: documentation

#1890 Fix(web-react): `ActionGroup` and `Box` exports
  packages/web-react/src/components/index.ts
Labels: bug

#1888 Revert: Deps: Update Playwright from 1.49.1 to 1.50.0
  .github/workflows/e2e.yml
  bin/make/e2e.sh
  package.json
  yarn.lock
Labels: run-visual-tests

#1885 Chore(ci): Replace auto assign GitHub action
  .github/workflows/pr-meta.yaml
Labels: maintenance

#1891 Fix(web-twig): SVG id must have a valid ID attribute value
  packages/web-twig/src/Resources/components/Accordion/__tests__/__snapshots__/accordionDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Accordion/__tests__/__snapshots__/accordionStayOpen.twig.snap.html
  packages/web-twig/src/Resources/components/Alert/__tests__/__snapshots__/alertDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Breadcrumbs/__tests__/__snapshots__/breadcrumbsDefault.twig.snap.html
  packages/web-twig/src/Resources/components/ButtonLink/__tests__/__snapshots__/buttonLinkLoadingDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Header/__tests__/__snapshots__/headerDialogCloseButton.twig.snap.html
  packages/web-twig/src/Resources/components/Header/__tests__/__snapshots__/headerMobileActions.twig.snap.html
  packages/web-twig/src/Resources/components/Header/__tests__/__snapshots__/headerWithDialog.twig.snap.html
  packages/web-twig/src/Resources/components/Icon/__tests__/__snapshots__/icon.twig.snap.html
  packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Modal/__tests__/__snapshots__/modalDisabledBackdropClick.twig.snap.html
  packages/web-twig/src/Resources/components/Pagination/__tests__/__snapshots__/paginationDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectDefault.twig.snap.html
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectDisabled.twig.snap.html
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectFluid.twig.snap.html
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectHelperText.twig.snap.html
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectLabelHidden.twig.snap.html
  packages/web-twig/src/Resources/components/Select/__tests__/__snapshots__/selectValidationState.twig.snap.html
  packages/web-twig/src/Resources/components/Spinner/__tests__/__snapshots__/spinnerDefault.twig.snap.html
  packages/web-twig/src/Resources/components/TextField/__tests__/__snapshots__/textFieldPasswordToggle.twig.snap.html
  packages/web-twig/src/Resources/components/Tooltip/__tests__/__snapshots__/tooltipPopover.twig.snap.html
  packages/web-twig/src/Resources/components/UNSTABLE_ActionLayout/__tests__/__snapshots__/UNSTABLE_EmptyState.twig.snap.html
  packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/__tests__/__snapshots__/UNSTABLE_EmptyState.twig.snap.html
  packages/web-twig/src/Twig/SvgExtension.php
  packages/web-twig/tests/__snapshots__/ComponentsSnapshotTest__test with data set spinnerIconProps.twig__1.html
  packages/web-twig/tests/fixtures/test.svg
  packages/web-twig/tests/fixtures/test_reusable.svg
  packages/web-twig/tests/fixtures/test_with_class.svg
  packages/web-twig/tests/fixtures/test_with_size.svg
  packages/web-twig/tests/fixtures/test_with_style.svg
  packages/web-twig/tests/fixtures/test_with_title.svg
Labels: bug

#1857 Docs(exporter-tokens): Update tokens exporter documentation #DS-1544
  exporters/tokens/README.md
Labels: documentation

#1893 Fix(web-react): Remove duplicated `id` on the `DropdownTrigger` component
  packages/web-react/src/components/Dropdown/DropdownTrigger.tsx
Labels: bug, run-visual-tests
