Repository lmc-eu/spirit-design-system, pull requests merged in 2025-07, with the labels that each got.

#2121 Fix(web-react): Fix undefined `window` reference in server-side call #DS-2029
  packages/web-react/src/components/ScrollView/useScrollPosition.ts
  packages/web-react/src/hooks/index.ts
Labels: bug, run-visual-tests

#2124 Feat(web-react): Add ReactNode type to PricingPlanFeature description
  packages/web-react/src/components/PricingPlan/README.md
  packages/web-react/src/components/PricingPlan/stories/PricingPlanBody.stories.tsx
  packages/web-react/src/types/pricingPlan.ts
Labels: feature

#2130 Chore(eslint-config): Upgrade `eslint-config-prettier` to 9.1.2
  configs/eslint-config-spirit/package.json
  packages/web-react/package.json
  yarn.lock
Labels: maintenance
