Repository lmc-eu/spirit-design-system, pull requests merged in 2025-02, with the labels that each got.

#1899 Feat(design-tokens): Introduce Skeleton Gradient tokens
  packages/design-tokens/src/js/global-tokens/gradients.ts
  packages/design-tokens/src/js/themes/theme-light-default/colors.ts
  packages/design-tokens/src/js/themes/theme-light-on-brand/colors.ts
  packages/design-tokens/src/scss/global-tokens/_gradients.scss
  packages/design-tokens/src/scss/themes/_color-tokens.scss
  packages/design-tokens/src/scss/themes/theme-light-default/_colors.scss
  packages/design-tokens/src/scss/themes/theme-light-on-brand/_colors.scss
Labels: feature

#1897 Chore(ci): Fetch full history on publish workflow
  .github/workflows/publish.yaml
Labels: maintenance

#1909 Revert: Deps: Update Playwright from 1.49.1 to 1.50.1
  .github/workflows/e2e.yml
  package.json
  yarn.lock
Labels: maintenance

#1901 Docs(repo): Remove duplicated Next Major Release Plans in release schedule
  docs/contribution/release-schedule.md
Labels: documentation

#1913 Feat(design-tokens): Update Skeleton gradient configuration
  packages/design-tokens/src/js/global-tokens/gradients.ts
  packages/design-tokens/src/scss/global-tokens/_gradients.scss
Labels: feature

#1912 Fix(web-react): Remove `validationState` from passed props of the TextFieldBase style hook
  packages/web-react/src/components/TextFieldBase/__tests__/useTextFieldBaseStyleProps.test.ts
  packages/web-react/src/components/TextFieldBase/useTextFieldBaseStyleProps.ts
Labels: bug, run-visual-tests

#1903 Fix(scripts): Move env file to appropriate location
  scripts/post-changelog/.env.example
  scripts/post-changelog/post-changelog.mjs
Labels: maintenance

#1895 Feat(web-react): Introduced Skeleton component #DS-1625
  packages/web-react/scripts/entryPoints.js
  packages/web-react/src/components/Skeleton/README.md
  packages/web-react/src/components/Skeleton/SkeletonHeading.tsx
  packages/web-react/src/components/Skeleton/SkeletonItem.tsx
  packages/web-react/src/components/Skeleton/SkeletonShape.tsx
  packages/web-react/src/components/Skeleton/SkeletonText.tsx
  packages/web-react/src/components/Skeleton/__tests__/SkeletonHeading.test.tsx
  packages/web-react/src/components/Skeleton/__tests__/SkeletonShape.test.tsx
  packages/web-react/src/components/Skeleton/__tests__/SkeletonText.test.tsx
  packages/web-react/src/components/Skeleton/__tests__/useSkeletonStyleProps.test.ts
  packages/web-react/src/components/Skeleton/constants.ts
  packages/web-react/src/components/Skeleton/demo/SkeletonCombined.tsx
  packages/web-react/src/components/Skeleton/demo/SkeletonHeadings.tsx
  packages/web-react/src/components/Skeleton/demo/SkeletonShapes.tsx
  packages/web-react/src/components/Skeleton/demo/SkeletonTexts.tsx
  packages/web-react/src/components/Skeleton/demo/index.tsx
  packages/web-react/src/components/Skeleton/index.html
  packages/web-react/src/components/Skeleton/index.ts
  packages/web-react/src/components/Skeleton/stories/Skeleton.stories.tsx
  packages/web-react/src/components/Skeleton/stories/SkeletonHeading.stories.tsx
  packages/web-react/src/components/Skeleton/stories/SkeletonShape.stories.tsx
  packages/web-react/src/components/Skeleton/useSkeletonShapeStyleProps.ts
  packages/web-react/src/components/Skeleton/useSkeletonStyleProps.ts
  packages/web-react/src/components/index.ts
  packages/web-react/src/types/index.ts
  packages/web-react/src/types/skeleton.ts
  tests/e2e/demo-homepages.spec.ts-snapshots/web-react-chromium-linux.png
Labels: feature, run-visual-tests

#1920 Chore(demo): Setup allowed hosts for demo app
  apps/demo/config/vite/app.ts
Labels: maintenance

#1937 Fix(demo): Move Divider from `Experimental` to `Components` in Storybook
  packages/web-react/src/components/Divider/stories/Divider.stories.tsx
Labels: bug

#1933 Fix(web-react): Remove duplicated id on the DropdownTrigger component
  packages/web-react/src/components/Dropdown/DropdownTrigger.tsx
  packages/web-react/src/components/Dropdown/__tests__/Dropdown.test.tsx
  packages/web-react/src/components/Dropdown/__tests__/useDropdownAriaProps.test.ts
  packages/web-react/src/components/Dropdown/useDropdownAriaProps.ts
Labels: bug

#1940 Docs(web): Use correct Flex reversed class in Empty State
  packages/web/src/scss/components/UNSTABLE_EmptyState/index.html
Labels: documentation, run-visual-tests

#1938 Fix(ci): Use correct env for changelog posting
  .github/workflows/publish.yaml
Labels: maintenance

#1954 Docs(web-twig): Use correct Flex reversed class in Empty State
  packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/__tests__/__fixtures__/UNSTABLE_EmptyState.twig
  packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/__tests__/__snapshots__/UNSTABLE_EmptyState.twig.snap.html
  packages/web-twig/src/Resources/components/UNSTABLE_EmptyState/stories/EmptyStateDefault.twig
Labels: documentation

#1949 Feat(web-react): Introduce `UncontrolledSplitButton` #DS-1656
  packages/web-react/src/components/SplitButton/README.md
  packages/web-react/src/components/SplitButton/UncontrolledSplitButton.tsx
  packages/web-react/src/components/SplitButton/__tests__/UncontrolledSplitButton.test.tsx
  packages/web-react/src/components/SplitButton/demo/UncontrolledSplitButton.tsx
  packages/web-react/src/components/SplitButton/index.ts
  packages/web-react/src/components/SplitButton/stories/UncontrolledSplitButton.stories.tsx
  packages/web-react/src/types/splitButton.ts
Labels: feature

#1960 Fix(web-react): Remove `focus` from available border colors
  docs/DICTIONARIES.md
  packages/web-react/src/components/Box/README.md
  packages/web-react/src/components/Box/demo/BoxWithBackgroundColor.tsx
  packages/web-react/src/components/Box/demo/BoxWithBorder.tsx
  packages/web-react/src/components/Box/demo/BoxWithCustomPadding.tsx
  packages/web-react/src/constants/dictionaries.ts
  packages/web/src/scss/components/Box/index.html
  tests/e2e/demo-components-compare.spec.ts-snapshots/box-chromium-linux.png
Labels: bug, run-visual-tests
